<?php
declare(strict_types=1);
if (isset($_GET['source'])) {
    $index = file_get_contents(__DIR__ . '/index.php');
    if (preg_match('~href="([^"]+/2004/08/another-of-moms-wonderful-breakfasts\\.html)"~', $index, $match)) {
        header('Location: ' . html_entity_decode($match[1], ENT_QUOTES), true, 302); exit;
    }
    http_response_code(404); exit('Please find the source in the gallery.');
}
?><!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="theme-color" content="#f6eedc"><title>The Breakfast Synchronizer</title>
<style>
@font-face{font-family:Kitchen;src:url('assets/tomorrows-bouquet-lato.ttf')}@font-face{font-family:Cookbook;src:url('assets/tomorrows-bouquet-bookman.otf')}
:root{--cream:#f6eedc;--ink:#173d42;--red:#b93d2d;--gold:#efb83f;--paper:#fffaf0;--line:#c8bda4}*{box-sizing:border-box}
body{margin:0;background:var(--cream);color:var(--ink);font:17px Kitchen,'Trebuchet MS',sans-serif;background-image:repeating-linear-gradient(0deg,transparent 0 5px,#ded4bb18 5px 6px)}main{max-width:1190px;margin:auto;padding:26px 28px 40px}a{color:inherit}nav{display:flex;justify-content:space-between;gap:20px;font-size:12px;text-transform:uppercase;letter-spacing:.12em;padding-bottom:22px;border-bottom:1px solid var(--line)}header{display:grid;grid-template-columns:1.3fr .7fr;align-items:end;gap:40px;padding:34px 0}.eyebrow{color:var(--red);font-size:12px;letter-spacing:.18em;font-weight:bold;text-transform:uppercase}h1{font:clamp(38px,5.5vw,70px)/1.03 Cookbook,Georgia,serif;margin:13px 0 0;letter-spacing:-.055em}h1 em{font-style:normal;color:var(--red)}header p{line-height:1.7;margin:0;max-width:360px}
.worktop{display:grid;grid-template-columns:1.55fr 1fr;align-items:start;gap:25px}.kitchen{border:2px solid var(--ink);border-radius:4px;overflow:hidden;background:var(--paper);box-shadow:6px 6px 0 #d2c5a9}.scene{position:relative;aspect-ratio:3/2;overflow:hidden;background:#d8bd8e}.scene img{width:100%;height:100%;object-fit:cover;display:block}.clock{position:absolute;left:18px;top:18px;border:2px solid var(--ink);border-radius:50%;background:var(--paper);width:77px;height:77px;display:flex;flex-direction:column;align-items:center;justify-content:center;box-shadow:3px 3px 0 #173d4222}.clock b{font:27px Cookbook,Georgia,serif}.clock span{font-size:10px;letter-spacing:.1em;text-transform:uppercase}.scene-label{position:absolute;bottom:15px;right:15px;background:var(--paper);padding:8px 13px;font-size:12px;border:1px solid var(--ink);transform:rotate(-3deg)}.stations{display:grid;grid-template-columns:repeat(3,1fr);gap:0}.station{padding:17px 12px;border-top:2px solid var(--ink);min-width:0;text-align:center}.station+.station{border-left:1px solid var(--line)}.station h2{font:18px Cookbook,Georgia,serif;margin:0 0 8px}.duration{font-size:12px;margin-bottom:13px}.bar{height:8px;background:#e7dfcb;margin:10px 0;overflow:hidden;border-radius:8px}.bar span{display:block;height:100%;width:0;background:var(--red);transition:width .3s}.station.done .bar span{background:#517961}.state{min-height:35px;font-size:12px;line-height:1.4}.station button{width:100%;margin-top:7px;padding:8px 3px}
button{font:inherit;font-weight:bold;min-height:44px;border:1.5px solid var(--ink);background:var(--paper);color:var(--ink);border-radius:4px;cursor:pointer;transition:transform .15s,background .15s}button:hover:not(:disabled){transform:translateY(-2px);background:#f4d994}button:disabled{opacity:.5;cursor:default}button:focus-visible,a:focus-visible,summary:focus-visible{outline:3px solid var(--red);outline-offset:4px}.primary{background:var(--ink);color:var(--paper)}.primary:hover:not(:disabled){background:#28626a}.ticket{background:var(--paper);padding:24px;border:1px solid var(--line);box-shadow:3px 5px 0 #dcd1b9;position:relative}.ticket:before{content:'';width:65px;height:17px;background:#e9c36b99;position:absolute;top:-8px;left:40%;transform:rotate(-4deg)}.ticket h2{font:27px Cookbook,Georgia,serif;margin:12px 0}.ticket p{line-height:1.5}.rounds{display:flex;gap:7px;margin:20px 0}.rounds button{flex:1;font-size:13px}.rounds button[aria-pressed=true]{background:var(--red);color:white;border-color:var(--red)}.rounds button.solved:after{content:' ✓'}.order-note{padding-bottom:15px;border-bottom:1px dashed var(--line)}.actions{display:grid;gap:10px;margin-top:20px}.row{display:flex;gap:10px}.row button{flex:1;font-size:14px}.feedback{min-height:85px;padding:15px 0 0;font-size:15px;line-height:1.55}.receipt{border-top:1px dashed var(--line);font:14px/1.8 'Courier New',monospace;padding-top:13px;white-space:pre-wrap;min-height:67px}.instructions{display:grid;grid-template-columns:1fr 1fr;gap:40px;margin-top:38px;border-top:1px solid var(--line);padding-top:25px}.instructions h2{font:23px Cookbook,Georgia,serif;margin:0 0 12px}.instructions p{font-size:15px;line-height:1.7}details{font-size:15px;line-height:1.7}summary{cursor:pointer;font-weight:bold}footer{font-size:13px;line-height:1.7;margin-top:30px;padding-top:20px;border-top:1px solid var(--line)}.success{color:#316844}.plate{display:none;position:absolute;inset:0;background:#f6eedce8;align-items:center;justify-content:center;flex-direction:column;gap:20px}.plate.visible{display:flex}.plate svg{width:75%;max-height:75%}.plate strong{font:23px Cookbook,Georgia,serif;text-align:center}
@media(max-width:800px){main{padding:20px 16px 35px}header{grid-template-columns:1fr;gap:20px;padding:28px 0}header p{max-width:none}.worktop{grid-template-columns:1fr;gap:30px}.instructions{grid-template-columns:1fr;gap:15px}nav{font-size:10px}.station h2{font-size:16px}.station{padding:14px 8px}.clock{width:62px;height:62px;top:12px;left:12px}.scene-label{font-size:10px}.ticket{padding:23px}.feedback{min-height:65px}}
@media(prefers-reduced-motion:reduce){*{transition:none!important}}
</style></head><body><main>
<nav><a href="index.php">← Chloe Reads Jon</a><span>Family kitchen • no rush</span></nav>
<header><div><div class="eyebrow">A small puzzle, sunny side up</div><h1>The Breakfast<br><em>Synchronizer.</em></h1></div><p>Three things. One lovely breakfast.<br>Can you make the toast, eggs, and cheese finish together? Time only moves when you say so.</p></header>
<div class="worktop"><section class="kitchen" aria-label="Your cooking stations">
<div class="scene"><img src="assets/breakfast-synchronizer-counter.webp" alt="Original painted breakfast counter with a chrome toaster, eggs in a frying pan, and a blue cheese dish"><div class="clock"><b id="turn">0</b><span>Kitchen tick</span></div><div class="scene-label">The secret ingredient is timing.</div>
<div class="plate" id="plate" aria-hidden="true"><svg viewBox="0 0 400 280"><ellipse cx="200" cy="150" rx="185" ry="118" fill="#fffaf0" stroke="#173d42" stroke-width="4"/><ellipse cx="200" cy="150" rx="159" ry="96" fill="none" stroke="#afc4ba" stroke-width="3"/><path d="M112 94 Q104 53 147 58 L250 58 Q292 54 286 96 L280 225 L120 225 Z" fill="#ae6334" stroke="#713b20" stroke-width="5"/><path d="M126 98 Q120 71 151 73 L249 73 Q276 69 270 100 L267 211 L135 211 Z" fill="#edbd69"/><path d="M142 110 L250 103 L260 186 L140 197 Z" fill="#f3ba39"/><path d="M146 129 Q148 98 179 108 Q209 94 224 115 Q259 123 246 147 Q258 185 221 185 Q206 209 180 189 Q143 194 138 165 Q122 142 146 129Z" fill="#fff8e2" stroke="#dacfb0" stroke-width="2"/><circle cx="193" cy="148" r="29" fill="#f1ac28"/><path d="M177 135 Q184 125 198 126" fill="none" stroke="#ffdd69" stroke-width="6" stroke-linecap="round"/></svg><strong id="plateTitle">Breakfast is served.</strong></div></div>
<div class="stations" id="stations"></div></section>
<section class="ticket" aria-label="Breakfast order"><div class="eyebrow" id="orderNumber">Order 01 / 03</div><h2 id="orderTitle"></h2><p class="order-note" id="orderNote"></p><div class="rounds" id="rounds" aria-label="Choose an order"></div><div class="eyebrow">At the pass</div><p style="font-size:14px">Start any station, then advance one tick. Finished food stays fresh for <strong id="window"></strong>. Serve all three while they’re still fresh.</p>
<div class="actions"><button class="primary" id="tick">Advance one kitchen tick →</button><button id="serve">Plate the breakfast</button><div class="row"><button id="reset">Try this order again</button><button id="hint">A chef’s hint</button></div><button id="next" hidden>Next breakfast →</button></div>
<div class="feedback" id="feedback" aria-live="polite"></div><div class="receipt" id="receipt" aria-label="Cooking timeline"></div></section></div>
<section class="instructions"><div><h2>Not fast. Just together.</h2><p>Starting a station costs no time. A tick advances <em>all</em> running stations at once. Watch the slowest ingredient and work backwards. There’s no countdown, no score, and nothing you can burn. Experiment freely.</p></div><details><summary>Why the puzzle works</summary><p>If eggs take four ticks and toast takes three, start the eggs one tick before the toast. Both finish at tick four. Cheese that takes two ticks can start at tick two. That’s backward scheduling, in the most delicious possible disguise.</p><p>These ticks are puzzle units, not actual cooking times. The three orders deliberately change the timings. A perfect plate has all three finish on the same tick; a warm plate is lovely too.</p></details></section>
<footer>Inspired by Jon’s <a href="?source=1">post about another of his mom’s wonderful breakfasts</a>: “cheese and eggs on toast.” An ordinary breakfast, a tiny act of care. Original kitchen artwork created for this page.</footer>
</main><script>
'use strict';
const orders=[
{title:'Mom’s wonderful breakfast',note:'Golden toast, sunny eggs, and a little melted cheese. A tribute to a very short, very good blog post.',times:[3,4,2],fresh:2},
{title:'The slow-pan special',note:'The eggs are taking their time today. Give them a head start so the toast doesn’t have to wait.',times:[2,5,3],fresh:1},
{title:'The thick-slice finale',note:'A chunky slice is slow to toast, but the cheese melts in a blink. Bring everything home on the same tick.',times:[4,3,1],fresh:0}
];
const names=['Toast','Eggs','Cheese'];const $=id=>document.getElementById(id);
let round=0,turn=0,items=[],served=false;const solved=new Set();
function begin(r){round=r;turn=0;served=false;items=names.map(()=>({start:null,end:null}));$('plate').classList.remove('visible');$('plate').setAttribute('aria-hidden','true');$('next').hidden=true;$('feedback').className='feedback';$('feedback').textContent='Which ingredient needs the biggest head start?';render()}
function status(i){const x=items[i],duration=orders[round].times[i];if(x.start===null)return 'Ready to start';if(x.end===null)return (duration-(turn-x.start))+' ticks remaining';const age=turn-x.end;return age===0?'Just finished!':age<=orders[round].fresh?'Fresh · waiting '+age+' tick'+(age===1?'':'s'):'Gone cool · waiting '+age+' ticks'}
function render(){
const order=orders[round];$('turn').textContent=turn;$('orderNumber').textContent='Order 0'+(round+1)+' / 03';$('orderTitle').textContent=order.title;$('orderNote').textContent=order.note;$('window').textContent=order.fresh===0?'the finishing tick only':order.fresh+' extra tick'+(order.fresh===1?'':'s');
$('rounds').replaceChildren();orders.forEach((o,i)=>{const b=document.createElement('button');b.textContent='Order '+(i+1);b.setAttribute('aria-pressed',String(round===i));if(solved.has(i))b.classList.add('solved');b.onclick=()=>begin(i);$('rounds').append(b)});
$('stations').replaceChildren();items.forEach((x,i)=>{const el=document.createElement('div');el.className='station'+(x.end!==null?' done':'');const h=document.createElement('h2');h.textContent=names[i];const d=document.createElement('div');d.className='duration';d.textContent=order.times[i]+' kitchen ticks';const bar=document.createElement('div');bar.className='bar';const fill=document.createElement('span');fill.style.width=(x.start===null?0:Math.min(100,(turn-x.start)/order.times[i]*100))+'%';bar.append(fill);const state=document.createElement('div');state.className='state';state.textContent=status(i);const b=document.createElement('button');b.textContent=x.start===null?'Start '+names[i].toLowerCase():x.end===null?'Cooking…':'Ready';b.disabled=x.start!==null||served;b.onclick=()=>start(i);el.append(h,d,bar,state,b);$('stations').append(el)});
$('tick').disabled=served||turn>=30;$('serve').disabled=served||!items.every(x=>x.end!==null);
$('receipt').textContent=items.map((x,i)=>names[i].padEnd(7)+' '+(x.start===null?'not started':'start '+x.start+' → '+(x.end===null?'finish '+(x.start+order.times[i]):'done '+x.end))).join('\n');
}
function start(i){if(served||items[i].start!==null)return;items[i].start=turn;$('feedback').textContent=names[i]+' started at tick '+turn+'. Start another station or advance time.';render()}
function tick(){if(served||turn>=30)return;turn++;items.forEach((x,i)=>{if(x.start!==null&&x.end===null&&turn-x.start>=orders[round].times[i])x.end=turn});const cold=items.some(x=>x.end!==null&&turn-x.end>orders[round].fresh);$('feedback').textContent=cold?'Something has gone cool. Reset whenever you want and try a different starting order.':items.every(x=>x.end!==null)?'All three are ready. This is your moment to plate!':'Tick '+turn+'. Have a look at what’s cooking.';render()}
function serve(){if(served||!items.every(x=>x.end!==null))return;const ages=items.map(x=>turn-x.end);if(ages.some(a=>a>orders[round].fresh)){$('feedback').textContent='A little too late: '+names.filter((n,i)=>ages[i]>orders[round].fresh).join(' and ')+' went cool. Try again, giving the slower stations a head start.';return}served=true;solved.add(round);const perfect=ages.every(a=>a===0);$('feedback').className='feedback success';$('feedback').textContent=perfect?'Perfectly synchronized. All three finished together. That’s a breakfast worth sitting down for.':'A lovely warm plate! For a perfect synchronisation, aim to finish all three on the same tick.';$('plateTitle').textContent=perfect?'Three things. One perfect moment.':'A lovely warm breakfast.';$('plate').classList.add('visible');$('plate').setAttribute('aria-hidden','false');$('next').hidden=false;$('next').textContent=round===2?'Back to the first breakfast →':'Next breakfast →';render()}
$('tick').onclick=tick;$('serve').onclick=serve;$('reset').onclick=()=>begin(round);$('next').onclick=()=>begin((round+1)%orders.length);
$('hint').onclick=()=>{const t=orders[round].times,max=Math.max(...t);$('feedback').textContent='For a perfect plate: '+names.map((n,i)=>'start '+n.toLowerCase()+' at tick '+(max-t[i])).join(', ')+'. Serve at tick '+max+'.'};
begin(0);
</script></body></html>
