<?php
declare(strict_types=1);
$sourceUrl = 'https://jona.ca/2010/01/my-desert-island-books.html';
?>
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="theme-color" content="#173f3a">
<title>The Ten-Year Shelf</title>
<style>
:root{--sea:#173f3a;--deep:#0c2725;--paper:#eee1bd;--ink:#29261f;--coral:#df694c;--sun:#edbb4f;--foam:#dbe8db;--muted:#756d5a;--shadow:rgba(7,30,27,.24)}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;color:var(--ink);background:var(--sea);font-family:Georgia,'Times New Roman',serif;min-height:100vh}
button,input{font:inherit}.ocean{position:fixed;inset:0;pointer-events:none;overflow:hidden;background:radial-gradient(circle at 75% 8%,rgba(237,187,79,.25),transparent 23%),linear-gradient(165deg,#25645c 0%,#173f3a 43%,#0c2725 100%);z-index:-2}.ocean:after{content:"";position:absolute;inset:-20%;opacity:.2;background-image:repeating-radial-gradient(ellipse at 20% 40%,transparent 0 38px,rgba(255,255,255,.22) 40px 42px);animation:drift 20s linear infinite}@keyframes drift{to{transform:translate3d(8%,3%,0) rotate(2deg)}}
.page{width:min(1180px,calc(100% - 28px));margin:22px auto 50px;background:var(--paper);box-shadow:0 24px 80px var(--shadow);position:relative;overflow:hidden;border-radius:2px}.page:before{content:"";position:absolute;inset:0;pointer-events:none;opacity:.27;background-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='90' height='90'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='.8' numOctaves='3' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='.17'/%3E%3C/svg%3E")}
.mast{position:relative;min-height:420px;padding:42px clamp(24px,6vw,76px) 56px;color:#fff7df;background:linear-gradient(90deg,rgba(8,37,34,.97),rgba(14,56,51,.88)),radial-gradient(circle at 80% 20%,var(--sun),transparent 22%);display:grid;grid-template-columns:1.3fr .7fr;gap:28px;align-items:center}.eyebrow{font-family:'Courier New',monospace;text-transform:uppercase;letter-spacing:.18em;font-weight:bold;font-size:.76rem;color:#f5ca69}.mast h1{margin:.18em 0 .12em;font-size:clamp(3.6rem,9vw,7.7rem);line-height:.77;letter-spacing:-.055em;font-weight:normal}.mast h1 span{display:block;color:var(--sun);font-style:italic;font-size:.63em;margin-left:.62em}.intro{font-size:clamp(1rem,1.7vw,1.28rem);line-height:1.55;max-width:660px;color:#e9e5d0}.passport{justify-self:end;width:min(270px,100%);aspect-ratio:4/5;border:1px solid rgba(255,255,255,.4);padding:18px;transform:rotate(3deg);background:rgba(255,255,255,.06);display:grid;place-items:center;text-align:center}.stamp{width:170px;height:170px;border:5px double var(--coral);border-radius:50%;display:grid;place-items:center;color:#f08a70;text-transform:uppercase;font-family:'Courier New',monospace;font-weight:bold;letter-spacing:.12em;transform:rotate(-12deg)}
.rule{position:relative;background:var(--sun);padding:10px 24px;text-align:center;font-family:'Courier New',monospace;font-weight:bold;letter-spacing:.05em}.workspace{position:relative;padding:44px clamp(18px,4vw,48px) 56px}.status{display:grid;grid-template-columns:1fr auto;gap:20px;align-items:end;margin-bottom:25px}.status h2{font-weight:normal;font-size:clamp(2.1rem,5vw,4.2rem);line-height:.9;margin:0}.counter{font-size:3rem;color:var(--coral);font-variant-numeric:tabular-nums}.counter small{font-size:.9rem;color:var(--muted);display:block;text-transform:uppercase;letter-spacing:.12em}.layout{display:grid;grid-template-columns:minmax(0,1.3fr) minmax(280px,.7fr);gap:24px}.catalog,.manifest{border:1px solid rgba(41,38,31,.27);background:rgba(255,250,230,.42);padding:20px}.section-head{display:flex;gap:12px;justify-content:space-between;align-items:center;margin-bottom:16px}.section-head h3{margin:0;font-size:1.1rem;text-transform:uppercase;letter-spacing:.1em}.filters{display:flex;gap:7px;flex-wrap:wrap}.filter,.quiet,.sail,.add-btn{border:1px solid var(--ink);background:transparent;padding:8px 11px;cursor:pointer;box-shadow:2px 2px 0 var(--ink);transition:.15s}.filter:hover,.filter.active,.quiet:hover{background:var(--ink);color:var(--paper);transform:translate(-1px,-1px);box-shadow:4px 4px 0 var(--coral)}
.books{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.book{border:0;text-align:left;min-height:116px;padding:14px 14px 13px 21px;background:#f8edcf;color:var(--ink);cursor:pointer;position:relative;box-shadow:inset 7px 0 0 var(--book),0 3px 0 rgba(48,40,25,.2);transition:.17s}.book:before{content:"+";position:absolute;right:10px;top:8px;font:bold 1.3rem 'Courier New',monospace;color:var(--book)}.book:hover{transform:translateY(-3px) rotate(-.3deg);box-shadow:inset 7px 0 0 var(--book),0 7px 0 rgba(48,40,25,.16)}.book.selected{opacity:.45;filter:grayscale(.65)}.book.selected:before{content:"✓"}.book strong{display:block;font-size:1.05rem;line-height:1.15;padding-right:20px}.book em{font-size:.8rem;color:var(--muted)}.tags{display:flex;gap:4px;flex-wrap:wrap;margin-top:9px}.tag{font:700 .62rem 'Courier New',monospace;text-transform:uppercase;padding:3px 5px;border:1px solid currentColor}
.custom{display:flex;gap:8px;margin-top:16px}.custom input{min-width:0;flex:1;border:1px solid var(--ink);background:#fff8e2;padding:10px 12px}.add-btn{background:var(--coral);color:white;font-weight:bold}.add-btn:disabled{opacity:.4;cursor:not-allowed}
.manifest{position:sticky;top:12px;align-self:start;background:#e6d5aa}.slots{list-style:none;padding:0;margin:0;display:grid;gap:5px}.slot{height:48px;border-bottom:1px dotted var(--muted);display:flex;align-items:center;gap:9px}.slot .num{font:700 .72rem 'Courier New',monospace;color:var(--coral);width:22px}.slot.empty{color:#978e76;font-style:italic}.slot button{margin-left:auto;border:0;background:none;font-size:1.2rem;cursor:pointer;color:var(--coral)}.meters{margin-top:20px;padding-top:17px;border-top:2px solid var(--ink)}.meter{display:grid;grid-template-columns:72px 1fr 26px;align-items:center;gap:8px;font:700 .7rem 'Courier New',monospace;text-transform:uppercase;margin:8px 0}.track{height:8px;background:rgba(0,0,0,.12)}.fill{display:block;height:100%;width:0;background:var(--coral);transition:width .35s}.sail{width:100%;margin-top:19px;background:var(--sea);color:white;border-color:var(--deep);box-shadow:4px 4px 0 var(--coral);padding:14px;font-weight:bold;text-transform:uppercase;letter-spacing:.08em}.sail:disabled{background:#827c69;box-shadow:none;cursor:not-allowed}.hint{text-align:center;color:var(--muted);font-size:.78rem;margin:10px 0 0}
.voyage{display:none;position:relative;background:var(--deep);color:#fff7df;padding:56px clamp(20px,6vw,70px);min-height:560px}.voyage.active{display:block}.yearline{font:700 .77rem 'Courier New',monospace;text-transform:uppercase;letter-spacing:.18em;color:var(--sun)}.voyage h2{font-size:clamp(2.7rem,7vw,5.6rem);line-height:.9;font-weight:normal;margin:.2em 0}.event{max-width:720px;font-size:clamp(1.05rem,2vw,1.35rem);line-height:1.55}.survival{font:normal clamp(4rem,13vw,10rem) Georgia;color:var(--sun);line-height:1;margin-top:26px}.survival small{font:700 .7rem 'Courier New',monospace;text-transform:uppercase;letter-spacing:.15em;color:#fff7df}.shelf-glimpse{display:flex;gap:4px;align-items:end;height:130px;margin:30px 0}.spine{flex:1;max-width:48px;background:var(--c);height:var(--h);writing-mode:vertical-rl;padding:8px 5px;font-size:.68rem;overflow:hidden;color:#fff9e9;box-shadow:inset -3px 0 rgba(0,0,0,.15)}.next{border:1px solid var(--sun);color:var(--sun);background:transparent;padding:12px 20px;cursor:pointer;font-weight:bold}.next:hover{background:var(--sun);color:var(--deep)}.verdict{display:none}.verdict.active{display:block}.verdict blockquote{font-size:clamp(1.3rem,3vw,2rem);max-width:760px;margin:22px 0;border-left:5px solid var(--coral);padding-left:20px}.restart{margin-left:8px}.source{position:relative;padding:28px;text-align:center;background:#d8c497}.source a{color:var(--deep);font-weight:bold;text-underline-offset:3px}.back{position:absolute;left:18px;top:18px;color:#fff7df;text-decoration:none;font:700 .72rem 'Courier New',monospace;text-transform:uppercase;letter-spacing:.1em;z-index:2}.back:hover{text-decoration:underline}
@media(max-width:760px){.page{width:100%;margin:0}.mast{grid-template-columns:1fr;min-height:auto;padding-top:68px}.passport{display:none}.layout{grid-template-columns:1fr}.manifest{position:relative;top:auto}.books{grid-template-columns:1fr}.status{grid-template-columns:1fr}.counter{text-align:left}.custom{flex-direction:column}.add-btn{padding:11px}.mast h1 span{margin-left:.28em}.source{padding:25px 18px}}
@media(prefers-reduced-motion:reduce){*{animation:none!important;scroll-behavior:auto!important;transition:none!important}}
</style>
</head>
<body>
<div class="ocean"></div>
<main class="page">
<section class="mast">
  <a class="back" href="index.php">← Chloe Reads Jon</a>
  <div><div class="eyebrow">Personal expedition no. 10</div><h1>The Ten-Year <span>Shelf</span></h1><p class="intro">A boat leaves at dawn. You may take ten books and no internet. Food and shelter are handled. Your inner life is not. Build a library worthy of 3,650 sunsets.</p></div>
  <div class="passport"><div class="stamp">Ten books<br>Ten years<br>One island</div></div>
</section>
<div class="rule">THE LIMIT IS THE GIFT — CHOOSE FOR REREADING, NOT DISPLAY</div>
<section class="workspace" id="builder">
  <div class="status"><h2>Pack your crate.</h2><div class="counter"><span id="count">0</span>/10<small>passages claimed</small></div></div>
  <div class="layout">
    <section class="catalog"><div class="section-head"><h3>Ship's catalog</h3><div class="filters" id="filters"></div></div><div class="books" id="books"></div><form class="custom" id="custom"><input id="customTitle" maxlength="70" placeholder="Add a book of your own…" aria-label="Custom book title"><button class="add-btn" type="submit">Pack it</button></form></section>
    <aside class="manifest"><div class="section-head"><h3>Crate manifest</h3><button class="quiet" id="jonList" type="button">Try Jon's six</button></div><ol class="slots" id="slots"></ol><div class="meters" id="meters"></div><button class="sail" id="sail" type="button" disabled>Seal crate &amp; sail</button><p class="hint" id="hint">Choose 10 books to begin the voyage.</p></aside>
  </div>
</section>
<section class="voyage" id="voyage"><div id="eventView"><div class="yearline" id="yearline"></div><h2 id="eventTitle"></h2><p class="event" id="eventText"></p><div class="survival" id="score"></div><div class="shelf-glimpse" id="shelf"></div><button class="next" id="next" type="button">Turn the year →</button></div><div class="verdict" id="verdict"></div></section>
<footer class="source">Inspired by Jon's <a href="<?= htmlspecialchars($sourceUrl, ENT_QUOTES) ?>">My Desert Island Books</a>, and his question: which ten books could sustain you for ten years?</footer>
</main>
<script>
const catalog=[
 {t:'The Bible',a:'many voices',c:['faith','wisdom','story'],color:'#7b3f35'},
 {t:'The Complete Shakespeare',a:'William Shakespeare',c:['story','beauty','humor'],color:'#365e51'},
 {t:'Catechism of the Catholic Church',a:'the Church',c:['faith','wisdom'],color:'#a36a2d'},
 {t:'The Imitation of Christ',a:'Thomas à Kempis',c:['faith','solace'],color:'#5d536b'},
 {t:'Complete Jane Austen',a:'Jane Austen',c:['story','humor','beauty'],color:'#b25852'},
 {t:'An Anthology of Poetry',a:'many poets',c:['beauty','solace'],color:'#34667a'},
 {t:'The Odyssey',a:'Homer',c:['story','courage'],color:'#876727'},
 {t:'The Divine Comedy',a:'Dante Alighieri',c:['faith','story','beauty'],color:'#944b35'},
 {t:'Summa Theologica',a:'Thomas Aquinas',c:['faith','wisdom'],color:'#3c5367'},
 {t:'Confessions',a:'St. Augustine',c:['faith','solace','wisdom'],color:'#775947'},
 {t:'War and Peace',a:'Leo Tolstoy',c:['story','wisdom'],color:'#58693c'},
 {t:'Don Quixote',a:'Miguel de Cervantes',c:['story','humor'],color:'#c27638'},
 {t:'A Field Guide to Island Life',a:'the practical choice',c:['skill','courage'],color:'#40705e'},
 {t:'A Blank Book & Pencil',a:'you, eventually',c:['beauty','solace','skill'],color:'#766e5e'},
 {t:'The Lord of the Rings',a:'J. R. R. Tolkien',c:['story','courage','solace'],color:'#426143'},
 {t:'The Complete Calvin and Hobbes',a:'Bill Watterson',c:['humor','solace'],color:'#d36c37'}
];
const dimensions=['faith','wisdom','story','beauty','humor','skill','solace','courage'];
const events=[
 {title:'The novelty wears off.',text:'The island is beautiful. It is also the same island as yesterday. A book with a world inside it becomes a second coastline.',needs:['story','beauty']},
 {title:'A week of hard rain.',text:'The roof leaks. The fire sulks. You need practical nerve, or at least somebody on the page who has endured worse weather.',needs:['skill','courage']},
 {title:'The longest silence.',text:'No ship crosses the horizon for four months. Wit and companionship begin to matter more than literary prestige.',needs:['humor','solace']},
 {title:'You know every path.',text:'Familiarity could shrink the island. Wisdom makes it deeper instead: the same path, read another way.',needs:['wisdom','beauty']},
 {title:'The crate gets lighter.',text:'Salt claims a few pages. The books that remain must carry more than one kind of nourishment.',needs:['story','faith']},
 {title:'A magnificent mistake.',text:'Your ambitious irrigation channel empties directly into your sleeping place. Laughter proves unexpectedly structural.',needs:['humor','skill']},
 {title:'A question with no audience.',text:'What is all this time for? The books that can answer slowly, and differently on the tenth reading, come forward.',needs:['faith','wisdom']},
 {title:'The rescue that was not.',text:'A sail appears, then dissolves into cloud. Courage is not pretending that disappointment does not hurt.',needs:['courage','solace']},
 {title:'Your own book begins.',text:'Margins, driftwood tablets, remembered lines: after nine years of reading, you start answering back.',needs:['beauty','skill']},
 {title:'A ship on the horizon.',text:'You are going home with ten battered companions and a different idea of what a book is for.',needs:['solace','wisdom','faith']}
];
let chosen=[],year=0,total=0;const $=s=>document.querySelector(s);
function renderFilters(){ $('#filters').innerHTML=['all','faith','story','humor','skill'].map(x=>`<button class="filter ${x==='all'?'active':''}" data-f="${x}" type="button">${x}</button>`).join(''); document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderBooks(b.dataset.f)}) }
function renderBooks(filter='all'){ $('#books').innerHTML=catalog.filter(b=>filter==='all'||b.c.includes(filter)).map((b)=>{const idx=catalog.indexOf(b),selected=chosen.some(x=>x.id===idx);return `<button class="book ${selected?'selected':''}" style="--book:${b.color}" data-i="${idx}" type="button"><strong>${b.t}</strong><em>${b.a}</em><span class="tags">${b.c.map(c=>`<span class="tag">${c}</span>`).join('')}</span></button>`}).join('');document.querySelectorAll('.book').forEach(b=>b.onclick=()=>toggle(+b.dataset.i))}
function toggle(i){const pos=chosen.findIndex(x=>x.id===i);if(pos>=0)chosen.splice(pos,1);else if(chosen.length<10)chosen.push({...catalog[i],id:i});update()}
function update(){renderBooks($('.filter.active')?.dataset.f||'all');$('#count').textContent=chosen.length;$('#slots').innerHTML=Array.from({length:10},(_,i)=>{const b=chosen[i];return b?`<li class="slot"><span class="num">${String(i+1).padStart(2,'0')}</span><span>${b.t}</span><button data-r="${i}" aria-label="Remove ${b.t}">×</button></li>`:`<li class="slot empty"><span class="num">${String(i+1).padStart(2,'0')}</span>Reserved for a future companion</li>`}).join('');document.querySelectorAll('[data-r]').forEach(b=>b.onclick=()=>{chosen.splice(+b.dataset.r,1);update()});const counts=Object.fromEntries(dimensions.map(d=>[d,chosen.filter(b=>b.c.includes(d)).length]));$('#meters').innerHTML=['faith','story','wisdom','humor','skill','solace'].map(d=>`<div class="meter"><span>${d}</span><span class="track"><span class="fill" style="width:${Math.min(100,counts[d]*25)}%"></span></span><b>${counts[d]}</b></div>`).join('');$('#sail').disabled=chosen.length!==10;$('#hint').textContent=chosen.length===10?'The tide is right. Your shelf is ready.':`${10-chosen.length} passage${10-chosen.length===9?'':'s'} still unclaimed.`;localStorage.setItem('tenYearShelf',JSON.stringify(chosen))}
$('#custom').onsubmit=e=>{e.preventDefault();const t=$('#customTitle').value.trim().replace(/[<>]/g,'');if(!t||chosen.length>=10)return;chosen.push({t,a:'your selection',c:['solace','wisdom'],color:'#6d5843',id:'custom-'+Date.now()});$('#customTitle').value='';update()};
$('#jonList').onclick=()=>{chosen=catalog.slice(0,6).map((b,i)=>({...b,id:i}));update()};
$('#sail').onclick=()=>{year=0;total=0;$('#builder').style.display='none';$('#voyage').classList.add('active');$('#eventView').style.display='block';$('#verdict').classList.remove('active');showYear();$('#voyage').scrollIntoView()};
function showYear(){const ev=events[year],counts=Object.fromEntries(dimensions.map(d=>[d,chosen.filter(b=>b.c.includes(d)).length])),hit=ev.needs.reduce((n,d)=>n+Math.min(3,counts[d]),0),points=Math.min(10,4+hit);total+=points;$('#yearline').textContent=`Year ${year+1} of 10 · field note ${String(year+1).padStart(2,'0')}`;$('#eventTitle').textContent=ev.title;$('#eventText').textContent=ev.text;$('#score').innerHTML=`+${points}<small> resilience</small>`;$('#shelf').innerHTML=chosen.map((b,i)=>`<span class="spine" style="--c:${b.color};--h:${75+(i%4)*12}px">${b.t}</span>`).join('');$('#next').textContent=year===9?'Read the final log →':'Turn the year →'}
$('#next').onclick=()=>{year++;if(year<10)showYear();else finish()};
function finish(){const cats=new Set(chosen.flatMap(b=>b.c)),score=Math.round(total/10),label=score>=9?'A library with roots':score>=7?'A sturdy little civilization':'A brave, eccentric crate';$('#eventView').style.display='none';$('#verdict').classList.add('active');$('#verdict').innerHTML=`<div class="yearline">Expedition complete · 3,650 sunsets</div><h2>${label}</h2><div class="survival">${score}<small>/ 10 shelf resilience</small></div><blockquote>“You did not bring ten objects. You brought ten inexhaustible conversations.”</blockquote><p class="event">Your shelf covered ${cats.size} kinds of nourishment. Its secret strength was not variety alone, but the books capable of becoming different books as you changed.</p><button class="next" onclick="window.print()">Print manifest</button><button class="next restart" onclick="location.reload()">Pack again</button>`}
try{const saved=JSON.parse(localStorage.getItem('tenYearShelf')||'[]');if(Array.isArray(saved))chosen=saved.slice(0,10)}catch(e){}renderFilters();update();
</script>
</body>
</html>
