<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#102b3a">
<title>The Fold &amp; Sever Bureau</title>
<style>
:root{--navy:#102b3a;--blue:#17404f;--cream:#f2e8ce;--paper:#fff8df;--gold:#e2aa32;--coral:#df654e;--ink:#17272d;--muted:#697067;--line:rgba(23,39,45,.22);--shadow:0 24px 60px rgba(9,24,31,.25)}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;color:var(--ink);background:radial-gradient(circle at 12% 7%,rgba(226,170,50,.2),transparent 25rem),linear-gradient(rgba(16,43,58,.035) 1px,transparent 1px),linear-gradient(90deg,rgba(16,43,58,.035) 1px,transparent 1px),var(--cream);background-size:auto,24px 24px,24px 24px,auto;font-family:Georgia,"Times New Roman",serif}
body:before{content:"";position:fixed;inset:0;pointer-events:none;z-index:20;opacity:.12;background-image:url("data:image/svg+xml,%3Csvg viewBox='0 0 180 180' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='.85' numOctaves='3'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='.3'/%3E%3C/svg%3E");mix-blend-mode:multiply}
button{font:inherit;touch-action:manipulation}.shell{width:min(1180px,calc(100% - 28px));margin:auto}.top{background:var(--navy);border-bottom:4px solid var(--gold)}nav{height:58px;display:flex;align-items:center;justify-content:space-between;color:var(--cream);font:700 .7rem/1 "Courier New",monospace;letter-spacing:.12em;text-transform:uppercase}nav a{color:inherit;text-decoration:none}.case{color:var(--gold)}
.hero{min-height:610px;display:grid;grid-template-columns:.86fr 1.14fr;background:var(--paper);box-shadow:var(--shadow);overflow:hidden}.hero-copy{padding:clamp(42px,7vw,84px) clamp(28px,5vw,66px);display:flex;flex-direction:column;justify-content:center;position:relative}.hero-copy:after{content:"TRAINING FILE";position:absolute;right:-22px;top:36px;transform:rotate(8deg);color:var(--coral);border:3px double;padding:7px 11px 5px;font:900 .68rem/1 "Courier New",monospace;letter-spacing:.13em}.eyebrow,.section-id{margin:0 0 20px;color:var(--coral);font:900 .7rem/1.2 "Courier New",monospace;letter-spacing:.18em;text-transform:uppercase}
h1{margin:0;max-width:9ch;font:900 clamp(3.5rem,7vw,7.6rem)/.82 Rockwell,"American Typewriter",Georgia,serif;letter-spacing:-.075em;text-transform:uppercase}h1 em{color:var(--coral)}.deck{max-width:35rem;margin:28px 0 30px;font-size:clamp(1.05rem,2vw,1.28rem);line-height:1.5}.start{align-self:flex-start;background:var(--gold);color:var(--navy);padding:15px 20px 13px;text-decoration:none;box-shadow:5px 5px var(--navy);font:900 .76rem/1 "Courier New",monospace;letter-spacing:.08em;text-transform:uppercase;transition:.16s}.start:hover{transform:translate(2px,2px);box-shadow:3px 3px var(--navy)}
.hero-art{position:relative;min-height:440px;background:var(--navy)}.hero-art img{display:block;width:100%;height:100%;object-fit:cover}.hero-art:after{content:"ONE CUT · MANY FRAGMENTS";position:absolute;right:22px;bottom:22px;background:var(--navy);color:var(--cream);padding:10px 13px 8px;font:700 .68rem/1 "Courier New",monospace;letter-spacing:.12em}
main{padding:clamp(52px,8vw,94px) 0 80px}.intro{display:grid;grid-template-columns:.7fr 1.3fr;gap:clamp(28px,7vw,86px);align-items:end;margin-bottom:34px}.intro .section-id{display:block;margin:0}h2{margin:9px 0 0;font:800 clamp(2.3rem,5vw,4.6rem)/.94 Rockwell,"American Typewriter",Georgia,serif;letter-spacing:-.05em}.intro p{margin:0;max-width:48rem;font-size:1.08rem;line-height:1.65}
.bureau{display:grid;grid-template-columns:minmax(0,1.45fr) minmax(290px,.55fr);background:var(--navy);color:var(--cream);border:8px solid var(--navy);box-shadow:var(--shadow)}.bench{min-width:0;min-height:600px;position:relative;display:flex;align-items:center;justify-content:center;padding:clamp(30px,5vw,64px);overflow:hidden;background:linear-gradient(90deg,transparent 49.7%,rgba(242,232,206,.07) 50%,transparent 50.3%),linear-gradient(transparent 49.7%,rgba(242,232,206,.07) 50%,transparent 50.3%),var(--blue);background-size:42px 42px}.bench:before{content:"ASSEMBLY SURFACE / KEEP CLEAR";position:absolute;top:18px;left:22px;color:rgba(242,232,206,.45);font:700 .61rem/1 "Courier New",monospace;letter-spacing:.14em}
.paper{width:min(430px,85%);aspect-ratio:1/1.28;position:relative;padding:9%;overflow:hidden;background:var(--paper);color:var(--ink);box-shadow:16px 19px rgba(0,0,0,.18);transform-origin:center;transition:width .55s cubic-bezier(.2,.8,.2,1),transform .55s,opacity .3s}.paper:before{content:"";position:absolute;inset:0;background:repeating-linear-gradient(90deg,transparent 0 calc(var(--gap,100%) - 1px),rgba(23,39,45,.25) calc(var(--gap,100%) - 1px) var(--gap,100%));pointer-events:none}.doc-head{border-bottom:5px solid;padding-bottom:9px;display:flex;justify-content:space-between;font:900 .67rem/1 "Courier New",monospace;letter-spacing:.12em}.conf{color:var(--coral)}.doc-title{margin:8% 0 5%;font:800 clamp(1.3rem,3vw,2rem)/1 Rockwell,Georgia,serif}.record{display:grid;grid-template-columns:38% 1fr;gap:5%;margin:7% 0;font:700 clamp(.54rem,1.3vw,.77rem)/1.25 "Courier New",monospace}.record b{color:var(--muted);text-transform:uppercase}.redact{background:var(--ink);color:var(--ink)}.barcode{position:absolute;left:9%;right:9%;bottom:8%;height:9%;opacity:.65;background:repeating-linear-gradient(90deg,var(--ink) 0 2px,transparent 2px 5px,var(--ink) 5px 9px,transparent 9px 11px)}
.cut-line{position:absolute;z-index:3;width:125%;height:4px;left:-12%;top:48%;background:repeating-linear-gradient(90deg,var(--coral) 0 13px,transparent 13px 20px);transform:rotate(var(--angle,0));opacity:0}.folded .paper{width:calc(min(430px,85%)/var(--folds));transform:rotate(-1.5deg);padding-left:4%;padding-right:4%}.folded .paper>*{opacity:.4}.folded .cut-line{opacity:1}.snipped .paper{animation:snip .35s}.snipped .cut-line{height:12px;background:var(--navy);box-shadow:0 -2px var(--coral),0 2px var(--coral)}@keyframes snip{35%{transform:rotate(2deg) translateX(-8px)}70%{transform:rotate(-2deg) translateX(6px)}}
.fragments{position:absolute;inset:7%;display:none;align-content:center;justify-content:center;grid-template-columns:repeat(var(--cols),minmax(22px,62px));gap:5px;transform:rotate(-2deg)}.disposed .paper{opacity:0;transform:scale(.65)}.disposed .fragments{display:grid}.frag{aspect-ratio:1.5;background:var(--paper);border:1px solid rgba(16,43,58,.45);color:var(--ink);display:grid;place-items:center;font:700 .42rem/1 "Courier New",monospace;transform:rotate(var(--r));animation:scatter .6s both;animation-delay:var(--d)}.frag:nth-child(3n){background:#eadfbf}.frag.marked{outline:3px solid var(--coral)}@keyframes scatter{from{opacity:0;transform:translateY(-80px)}}.stamp{display:none;position:absolute;z-index:5;color:var(--gold);border:5px double;padding:14px 17px 11px;background:rgba(16,43,58,.92);font:900 clamp(1rem,3vw,1.5rem)/1 "Courier New",monospace;letter-spacing:.12em;text-transform:uppercase;transform:rotate(-7deg);text-align:center}.disposed .stamp{display:block;animation:stamp .45s cubic-bezier(.18,.9,.3,1.4) both .65s}@keyframes stamp{from{opacity:0;transform:scale(2.5) rotate(-7deg)}}
.controls{background:var(--paper);color:var(--ink);padding:30px 26px;display:flex;flex-direction:column}.step{margin-bottom:18px;color:var(--coral);font:900 .67rem/1 "Courier New",monospace;letter-spacing:.15em;text-transform:uppercase}.controls h3{margin:0;font:800 2rem/1 Rockwell,Georgia,serif;letter-spacing:-.04em}.instruction{min-height:70px;margin:13px 0 18px;color:var(--muted);line-height:1.5}.choices{display:grid;gap:8px;margin-bottom:18px}.choice{width:100%;border:1px solid var(--line);background:transparent;color:var(--ink);padding:12px 13px;text-align:left;cursor:pointer;font:700 .74rem/1.2 "Courier New",monospace;transition:.15s}.choice:hover,.choice.active{background:var(--gold);border-color:var(--ink);transform:translateX(3px)}.choice span{float:right;opacity:.6}.row{display:flex;gap:8px;margin-top:auto}.action{flex:1;border:0;background:var(--coral);color:#fff9e9;padding:14px;cursor:pointer;box-shadow:4px 4px var(--ink);font:900 .72rem/1 "Courier New",monospace;letter-spacing:.06em;text-transform:uppercase}.action:active{transform:translate(2px,2px);box-shadow:2px 2px var(--ink)}.action:disabled{opacity:.38}.reset{flex:0 0 auto;background:transparent;color:var(--ink);border:1px solid var(--line);box-shadow:none}
.meter{grid-column:1/-1;background:var(--gold);color:var(--navy);display:grid;grid-template-columns:1fr auto;gap:24px;align-items:center;padding:20px clamp(20px,4vw,44px);border-top:8px solid var(--navy)}.meter-label{font:900 .64rem/1 "Courier New",monospace;letter-spacing:.15em;text-transform:uppercase}.track{height:13px;background:rgba(16,43,58,.18);margin-top:9px;overflow:hidden}.fill{height:100%;width:4%;background:var(--navy);transition:width .65s}.score{font:900 2.4rem/1 Rockwell,Georgia,serif}
.debrief{margin-top:clamp(52px,8vw,86px);display:grid;grid-template-columns:repeat(3,1fr);gap:1px;background:var(--line);border:1px solid var(--line)}.note{background:var(--paper);padding:clamp(26px,4vw,42px)}.note-no{color:var(--coral);font:900 .67rem/1 "Courier New",monospace;letter-spacing:.14em}.note h3{margin:12px 0 10px;font:800 1.45rem/1.05 Rockwell,Georgia,serif}.note p{margin:0;line-height:1.55;color:#495257}.warning{background:var(--coral);color:#fff8e8}.warning .note-no{color:var(--gold)}.warning p{color:#fff8e8}footer{padding:38px 0 54px;text-align:center;color:var(--muted);font-size:.93rem}footer a{text-underline-offset:3px}.sr{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0,0,0,0)}
@media(max-width:820px){.hero{grid-template-columns:1fr}.hero-art{min-height:350px;order:-1}.hero-copy:after{right:18px;top:24px}.intro{grid-template-columns:1fr;gap:18px}.bureau{grid-template-columns:1fr}.bench{min-height:510px}.controls{min-height:385px}.meter{grid-column:1}.debrief{grid-template-columns:1fr}}@media(max-width:520px){.shell{width:calc(100% - 18px)}nav{font-size:.59rem}h1{font-size:clamp(3rem,18vw,5rem)}.hero-copy{padding:46px 24px 50px}.hero-art{min-height:285px}.bench{min-height:410px;padding:35px 14px 20px}.paper{width:min(340px,91%)}.folded .paper{width:calc(min(340px,91%)/var(--folds))}.controls{padding:27px 20px}.meter{grid-template-columns:1fr;gap:10px}.score{font-size:2rem}}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;animation-duration:.01ms!important;transition-duration:.01ms!important}}
</style></head>
<body>
<div class="top"><nav class="shell"><a href="./">← Chloe Reads Jon</a><span class="case">Bureau file 12·31·11</span></nav></div>
<header class="hero shell"><div class="hero-copy"><p class="eyebrow">Domestic privacy division presents</p><h1>Fold <em>&amp;</em> Sever</h1><p class="deck">One sheet. Several folds. One decisive cut. Can a kitchen-table method turn an ordinary document into a reconstruction nightmare?</p><a class="start" href="#lab">Open the training file ↓</a></div><div class="hero-art"><img src="fold-sever-bureau-hero.webp" alt="Illustrated evidence desk with a folded confidential paper, brass scissors, and two trays of fragments"></div></header>
<main class="shell">
<section class="intro"><div><span class="section-id">Field exercise 01</span><h2>Make one cut count.</h2></div><p>Jon’s trick is delightfully physical: fold a document many times, cut the packet once, then separate the two halves into different waste streams. Run the method below and watch each small choice change the reconstruction burden.</p></section>
<section class="bureau" id="lab" aria-label="Interactive paper destruction simulator"><div class="bench" id="bench"><div class="paper" id="paper"><div class="doc-head"><span>Form 14-B</span><span class="conf">Confidential</span></div><div class="doc-title">Resident Record</div><div class="record"><b>Name</b><span>Alex Example</span></div><div class="record"><b>Account</b><span class="redact">8830 4921 0052</span></div><div class="record"><b>Address</b><span>17 Cedar Lane</span></div><div class="record"><b>Passphrase</b><span class="redact">marzipan-orbit</span></div><div class="record"><b>Filed</b><span>31 DEC 2011</span></div><div class="barcode"></div><div class="cut-line"></div></div><div class="fragments" id="fragments"></div><div class="stamp" id="stamp">Pending review</div></div>
<aside class="controls"><div class="step" id="step">Step 1 of 3 · Compression</div><h3 id="title">Choose your folds</h3><p class="instruction" id="instruction">More folds put more layers beneath the blades. Pick a practical packet thickness.</p><div class="choices" id="choices"></div><div class="row"><button class="action reset" id="reset" type="button" aria-label="Reset">↺</button><button class="action" id="action" type="button">Make folds</button></div></aside>
<div class="meter" aria-live="polite"><div><div class="meter-label">Estimated reconstruction burden</div><div class="track"><div class="fill" id="fill"></div></div></div><div class="score" id="score">04 / 100</div></div></section>
<section class="debrief"><article class="note"><span class="note-no">01 / Why fold?</span><h3>Layers multiply the cut.</h3><p>A single pass through a folded packet makes matching fragment edges less obvious than one lonely tear down the middle.</p></article><article class="note"><span class="note-no">02 / Why separate?</span><h3>Distance beats neatness.</h3><p>Putting the two halves in different collections adds a retrieval problem before the paper puzzle even begins.</p></article><article class="note warning"><span class="note-no">03 / Reality check</span><h3>Clever, not classified.</h3><p>For genuinely sensitive records, use a cross-cut or micro-cut shredder and follow local disposal guidance. This is a playful model, not security certification.</p></article></section>
</main><footer class="shell">Inspired by Jon’s <a href="https://jona.ca/2011/12/how-to-shred-document-by-hand.html" target="_blank" rel="noopener">“How to shred a document by hand”</a>.</footer><div class="sr" id="announce" aria-live="assertive"></div>
<script>
(function(){
var steps=[{pill:"Step 1 of 3 · Compression",title:"Choose your folds",text:"More folds put more layers beneath the blades. Pick a practical packet thickness.",action:"Make folds",options:[["Twice","4 layers",2],["Four times","16 layers",4],["Six times","64 layers",6]]},{pill:"Step 2 of 3 · Severance",title:"Choose the cut",text:"A diagonal path crosses more lines of text. The scissors remain strictly theatrical.",action:"Make the cut",options:[["Straight across","orderly","straight"],["Diagonal","disruptive","diagonal"],["Cheeky zigzag","maximum fuss","zigzag"]]},{pill:"Step 3 of 3 · Disposal",title:"Split the evidence",text:"Where should the two groups of fragments go? Separation changes the threat model.",action:"File the report",options:[["Same recycling bin","convenient","same"],["Bin + recycling","Jon’s method","split"],["Two collection days","patient","timed"]]}],state={step:0},selections=[4,"diagonal","split"],bench=document.getElementById("bench"),paper=document.getElementById("paper"),choices=document.getElementById("choices"),action=document.getElementById("action"),fill=document.getElementById("fill"),score=document.getElementById("score");
function controls(){var d=steps[state.step];document.getElementById("step").textContent=d.pill;document.getElementById("title").textContent=d.title;document.getElementById("instruction").textContent=d.text;action.textContent=d.action;choices.innerHTML="";d.options.forEach(function(o){var b=document.createElement("button");b.type="button";b.className="choice"+(o[2]===selections[state.step]?" active":"");b.innerHTML=o[0]+"<span>"+o[1]+"</span>";b.onclick=function(){selections[state.step]=o[2];Array.from(choices.children).forEach(function(x){x.classList.remove("active")});b.classList.add("active");preview()};choices.appendChild(b)})}
function points(final){var f={2:18,4:34,6:48}[selections[0]],c={straight:9,diagonal:17,zigzag:23}[selections[1]],d={same:4,split:19,timed:27}[selections[2]],v=state.step===0?4:f;if(state.step>=1)v+=c;if(state.step>=2||final)v+=d;return Math.min(98,v)}
function setScore(v){fill.style.width=v+"%";score.textContent=String(v).padStart(2,"0")+" / 100"}function preview(){if(state.step===0)setScore(Math.round({2:18,4:34,6:48}[selections[0]]*.38));else if(state.step===1)setScore({2:18,4:34,6:48}[selections[0]]+Math.round({straight:9,diagonal:17,zigzag:23}[selections[1]]*.35));else setScore(points(true))}
function sound(){try{var C=window.AudioContext||window.webkitAudioContext,x=new C,o=x.createOscillator(),g=x.createGain();o.type="square";o.frequency.setValueAtTime(520,x.currentTime);o.frequency.exponentialRampToValueAtTime(120,x.currentTime+.08);g.gain.setValueAtTime(.055,x.currentTime);g.gain.exponentialRampToValueAtTime(.001,x.currentTime+.09);o.connect(g).connect(x.destination);o.start();o.stop(x.currentTime+.1)}catch(e){}}
function fragments(){var f=document.getElementById("fragments"),n=Math.min(36,8+selections[0]*4),s=["AC","17","EX","83","DR","LA","••","20","ID","CE"];f.innerHTML="";f.style.setProperty("--cols",selections[0]>=6?6:5);for(var i=0;i<n;i++){var x=document.createElement("span");x.className="frag"+(i%11===0?" marked":"");x.style.setProperty("--r",((i*17)%22-11)+"deg");x.style.setProperty("--d",(i*13)+"ms");x.textContent=s[i%s.length];f.appendChild(x)}}
function report(){fragments();bench.classList.add("disposed");var v=points(true),kind=selections[2];setScore(v);document.getElementById("stamp").textContent={same:"Recoverable / ",split:"Method approved / ",timed:"Very troublesome / "}[kind]+v;document.getElementById("step").textContent="Exercise complete · Debrief";document.getElementById("title").textContent=v>=80?"A formidable paper puzzle.":v>=60?"Nicely inconvenient.":"A determined snoop persists.";document.getElementById("instruction").textContent=kind==="same"?"The folds helped, but keeping every fragment together gifts the investigator a complete puzzle box.":kind==="split"?"Jon’s split-stream move adds a retrieval barrier. Simple, memorable, rather clever.":"Spacing the halves across collection days creates the strongest retrieval barrier in this tiny model.";choices.innerHTML='<button class="choice active" type="button" id="again">Run another file <span>↺</span></button>';document.getElementById("again").onclick=reset;action.textContent="Exercise complete";action.disabled=true;document.getElementById("announce").textContent="Exercise complete. Reconstruction burden "+v+" out of 100."}
action.onclick=function(){if(state.step===0){bench.classList.add("folded");bench.style.setProperty("--folds",Math.max(2,selections[0]*.72));paper.style.setProperty("--gap",(100/selections[0])+"%");setScore({2:18,4:34,6:48}[selections[0]]);state.step=1;controls()}else if(state.step===1){paper.style.setProperty("--angle",(selections[1]==="straight"?0:selections[1]==="diagonal"?-22:12)+"deg");bench.classList.add("snipped");sound();setScore(points(false));state.step=2;setTimeout(controls,280)}else report()};
function reset(){state={step:0};selections=[4,"diagonal","split"];bench.classList.remove("folded","snipped","disposed");bench.style.removeProperty("--folds");paper.style.removeProperty("--angle");paper.style.removeProperty("--gap");action.disabled=false;setScore(4);controls()}document.getElementById("reset").onclick=reset;controls();
}());
</script></body></html>