<?php declare(strict_types=1); ?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#193c32"><title>The Hundred-Year Echo</title>
<style>
@import url('https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=Fraunces:opsz,wght@9..144,600;9..144,800&display=swap');
:root{--ink:#17382e;--paper:#f2e7cc;--gold:#d8a12f;--red:#a5422d;--cream:#fff9e9;--ring:0}*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;color:var(--ink);background:var(--paper);font-family:"DM Mono",monospace;background-image:radial-gradient(#17382e20 .7px,transparent .8px);background-size:7px 7px}body:before{content:"";position:fixed;inset:0;pointer-events:none;z-index:9;opacity:.13;background:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence baseFrequency='.8' numOctaves='3'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E")}a{color:inherit}.wrap{width:min(1100px,calc(100% - 32px));margin:auto}.mast{padding:18px 0;border-bottom:1px solid #17382e66;display:flex;justify-content:space-between;gap:16px;font-size:10px;letter-spacing:.12em;text-transform:uppercase}.mast b{display:flex;align-items:center;gap:10px}.mast b:before{content:"";width:11px;height:11px;background:var(--red);transform:rotate(45deg)}
+.hero{padding:58px 0 42px;display:grid;grid-template-columns:.82fr 1.18fr;gap:28px;align-items:end}.kicker{font-size:10px;letter-spacing:.16em;text-transform:uppercase;color:var(--red);margin-bottom:16px}h1,h2,h3{font-family:"Fraunces",serif}h1{font-size:clamp(3.5rem,9vw,7.6rem);line-height:.79;letter-spacing:-.065em;margin:0;max-width:8ch}h1 em{font-style:normal;color:var(--red)}.lede{font:600 clamp(1.1rem,2vw,1.45rem)/1.45 "Fraunces";max-width:31rem}.art{margin:0;position:relative;background:var(--ink);padding:9px;box-shadow:0 18px 40px #26302b35;transform:rotate(1deg)}.art:after{content:"ARCHIVE PLATE № 100";position:absolute;right:13px;bottom:13px;background:var(--paper);padding:6px;font-size:8px}.art img{display:block;width:100%;aspect-ratio:16/9;object-fit:cover;filter:saturate(calc(.45 + var(--ring)*.009)) sepia(calc(.4 - var(--ring)*.004));transition:.8s}.rule{height:8px;background:repeating-linear-gradient(90deg,var(--ink) 0 34px,transparent 34px 41px);margin:0 0 52px}.brief{display:grid;grid-template-columns:1fr 2fr;gap:30px;margin-bottom:45px}.brief h2,.station h2{font-size:clamp(2.2rem,5vw,3.8rem);line-height:.94;letter-spacing:-.04em;margin:0}.brief p{font:600 1.15rem/1.6 "Fraunces";margin:0}.stamp{display:inline-block;color:var(--red);border:2px solid;border-radius:50%;padding:14px 10px;transform:rotate(-8deg);font-size:9px;text-align:center;letter-spacing:.1em;margin-top:22px}
+.station{background:var(--ink);color:var(--cream);margin:0 calc(50% - 50vw);padding:58px max(16px,calc((100vw - 1100px)/2))}.station-head{display:flex;justify-content:space-between;align-items:end;gap:20px;margin-bottom:32px}.counter{font:600 3rem "Fraunces";color:var(--gold)}.counter small{display:block;font:9px "DM Mono";color:var(--cream);letter-spacing:.12em;text-transform:uppercase}.workbench{display:grid;grid-template-columns:.8fr 1.2fr;gap:26px}.card{min-height:292px;background:var(--cream);color:var(--ink);border:3px solid var(--gold);box-shadow:10px 10px 0 var(--red);padding:28px;display:flex;flex-direction:column;justify-content:space-between;position:relative;animation:deal .4s both}@keyframes deal{from{opacity:0;transform:translateX(-25px) rotate(-2deg)}}.card:after{content:attr(data-no);position:absolute;right:18px;top:8px;font:600 4rem "Fraunces";color:#e7d7b5}.glyph{font-size:2.2rem;margin-bottom:22px}.card h3{font-size:clamp(1.8rem,4vw,2.6rem);line-height:1.05;margin:0;max-width:10ch}.card p{font-size:10px;line-height:1.6;color:#687063}.bins{display:grid;grid-template-columns:1fr 1fr;gap:12px}.bin{min-height:130px;border:1px solid #fff9e866;background:transparent;color:var(--cream);font:inherit;text-align:left;padding:20px;cursor:pointer;display:flex;flex-direction:column;justify-content:space-between;transition:.2s}.bin:hover,.bin:focus-visible{outline:0;border-color:var(--gold);background:#d8a12f1f;transform:translateY(-3px)}.bin span{font-size:8px;letter-spacing:.11em;text-transform:uppercase;opacity:.7}.bin strong{font:600 1.2rem "Fraunces"}.bin b{color:var(--gold);font-size:1.3rem}.bin.flash{animation:flash .5s}@keyframes flash{50%{background:var(--gold);color:var(--ink)}}.meter{margin-top:28px;border-top:1px solid #fff9e84d;padding-top:23px;display:grid;grid-template-columns:160px 1fr;align-items:center;font-size:9px;letter-spacing:.1em;text-transform:uppercase}.track{height:3px;background:#fff9e833}.track i{display:block;height:3px;width:calc(var(--ring)*1%);background:var(--gold);transition:.6s;position:relative}.track i:after{content:"";position:absolute;right:-8px;top:-7px;width:14px;height:14px;border:2px solid var(--gold);border-radius:50%;box-shadow:0 0 0 7px var(--ink),0 0 0 9px var(--gold)}
+.reflect{padding:72px 0;display:grid;grid-template-columns:1fr 1fr;gap:46px}.reflect blockquote{font:600 clamp(1.8rem,4vw,3.7rem)/1.08 "Fraunces";letter-spacing:-.035em;margin:0}.reflect em{color:var(--red)}.prompt{border-left:1px solid;padding-left:30px}.prompt label{display:block;font-size:9px;letter-spacing:.12em;text-transform:uppercase;margin-bottom:14px}textarea{width:100%;min-height:130px;border:0;border-bottom:3px solid;background:#fff6;font:600 1.05rem/1.6 "Fraunces";padding:13px;color:var(--ink);resize:vertical}textarea:focus{outline:2px solid var(--gold)}button.seal{margin-top:17px;border:0;background:var(--red);color:var(--cream);padding:16px 20px;font:500 10px "DM Mono";letter-spacing:.1em;text-transform:uppercase;box-shadow:5px 5px var(--ink);cursor:pointer}.receipt{display:none;background:var(--cream);border:1px solid;padding:36px;max-width:720px;margin:0 auto 72px;box-shadow:0 18px 40px #26302b35}.receipt.show{display:block;animation:rise .5s}@keyframes rise{from{opacity:0;transform:translateY(20px)}}.receipt h2{font-size:2.5rem;margin:0}.chosen{font:600 1.35rem/1.5 "Fraunces";margin:22px 0}.receipt small{color:#687063}footer{border-top:1px solid #17382e66;padding:28px 0 48px;display:flex;justify-content:space-between;gap:20px;font-size:9px;line-height:1.7}.source{max-width:580px}.source a{color:var(--red);font-weight:bold}
+@media(max-width:740px){.hero,.brief,.workbench,.reflect{grid-template-columns:1fr}.hero{padding-top:36px}.brief{gap:18px}.station-head{align-items:start}.station h2{max-width:8ch}.card{min-height:235px}.bins{grid-template-columns:1fr}.bin{min-height:92px}.meter{grid-template-columns:1fr;gap:15px}.prompt{border:0;border-top:1px solid;padding:28px 0 0}footer{flex-direction:column}.mast span{display:none}}@media(prefers-reduced-motion:reduce){*{animation:none!important;transition:none!important;scroll-behavior:auto!important}}
+</style></head><body><div class="wrap">
+<header class="mast"><b>Chloe’s Future Archive</b><span>Field experiment · September 2026</span><a href="./">All exhibits ↗</a></header>
+<main><section class="hero"><div><div class="kicker">A small instrument for large time</div><h1>The Hundred-Year <em>Echo</em></h1><p class="lede">Sort the urgent, the lovely, and the lasting. Then send one good thing farther than your calendar can see.</p></div><figure class="art"><img src="hundred-year-echo-hero.webp" alt="Painted clockwork errands giving way to a cedar tree, family table, learning, prayer, and golden rings"></figure></section>
+<div class="rule"></div><section class="brief"><div><h2>Time is a ruthless editor.</h2><div class="stamp">ARCHIVE TEST<br>№ 100</div></div><p>Matthew Kelly’s line, quoted by Jon, asks how much of our busyness will mean anything a century from now. This isn’t a productivity score. It’s a playful change of scale: six ordinary activities, four shelves in time, and no single correct answer.</p></section>
+<section class="station"><div class="station-head"><div><div class="kicker" style="color:var(--gold)">Part I · The sorting room</div><h2>Where does this echo end?</h2></div><div class="counter"><span id="count">0</span>/6<small>items archived</small></div></div><div class="workbench"><article class="card" id="card" data-no="01" aria-live="polite"><div><div class="glyph" id="glyph">✦</div><h3 id="activity">Loading…</h3></div><p>No answer key. Choose the horizon that feels honest today.</p></article><div class="bins">
+<button class="bin" data-years="1"><span>Shelf A · tonight</span><strong>Gone by supper</strong><b>·</b></button><button class="bin" data-years="18"><span>Shelf B · one season</span><strong>Still matters next spring</strong><b>)))</b></button><button class="bin" data-years="58"><span>Shelf C · one lifetime</span><strong>Echoes after I’m gone</strong><b>)))))</b></button><button class="bin" data-years="100"><span>Shelf D · one century</span><strong>Could matter in 100 years</strong><b>))))))))</b></button>
+</div></div><div class="meter"><label>Current echo horizon</label><div class="track"><i></i></div></div></section>
+<section class="reflect"><blockquote>Not everything must last. A cup of tea may vanish and still be <em>worth having.</em></blockquote><div class="prompt"><label for="note">Part II · One thing worth sending forward</label><textarea id="note" maxlength="180" placeholder="A tradition, kindness, skill, story, prayer, repair…"></textarea><button class="seal" id="seal">Seal in the future archive</button></div></section>
+<section class="receipt" id="receipt" aria-live="polite"><div class="kicker">Archive receipt · accepted</div><h2>A note to 2126</h2><div class="chosen" id="chosen"></div><small id="summary"></small></section></main>
+<footer><div class="source">Inspired by Jon’s <a href="https://cooltoolsforcatholics.blogspot.com/2005/01/rhythm-of-life-by-matthew-kelly.html" target="_blank" rel="noopener">“The Rhythm of Life by Matthew Kelly”</a>, especially its question about what our busyness will mean a hundred years from now.</div><div>Made for reflection, not judgement.<br>Nothing leaves this page.</div></footer></div>
+<script>
+const pool=[['Clear the last twelve notifications','▤'],['Teach a child the family recipe','♨'],['Repair a friendship after a sharp word','↝'],['Buy the slightly better charging cable','⌁'],['Write down a story only your family knows','✎'],['Sit beside someone who is lonely','◒'],['Perfect the spacing on one tiny button','⌘'],['Plant a tree you may never sit beneath','♣'],['Pray faithfully for someone by name','✦'],['Make a ridiculous joke at breakfast','☀'],['Keep a promise when nobody checks','◇'],['Build a useful thing and give it away','⚒']].sort(()=>crypto.getRandomValues(new Uint32Array(1))[0]/4294967296-.5).slice(0,6);let step=0,total=0;const card=document.querySelector('#card'),activity=document.querySelector('#activity'),glyph=document.querySelector('#glyph');
+function show(){if(step===6){activity.textContent='The shelves are full.';glyph.textContent='✓';card.dataset.no='—';document.querySelectorAll('.bin').forEach(b=>{b.disabled=true;b.style.opacity=.35});document.querySelector('.reflect').scrollIntoView({behavior:'smooth'});return}activity.textContent=pool[step][0];glyph.textContent=pool[step][1];card.dataset.no=String(step+1).padStart(2,'0');card.style.animation='none';requestAnimationFrame(()=>card.style.animation='deal .4s both')}
+document.querySelectorAll('.bin').forEach(b=>b.onclick=()=>{total+=+b.dataset.years;step++;document.querySelector('#count').textContent=step;document.documentElement.style.setProperty('--ring',Math.round(total/step));b.classList.remove('flash');void b.offsetWidth;b.classList.add('flash');setTimeout(show,230)});
+document.querySelector('#seal').onclick=()=>{const note=document.querySelector('#note').value.trim(),avg=step?Math.round(total/step):0,r=document.querySelector('#receipt');document.querySelector('#chosen').textContent=note||'I will leave one small place kinder than I found it.';document.querySelector('#summary').textContent=step?'Your choices reached an average horizon of '+avg+' years. Not a grade; simply the distance from which you looked back.':'You skipped the measuring and kept the promise. The archive respects that.';r.classList.add('show');r.scrollIntoView({behavior:'smooth',block:'center'})};show();
+</script></body></html>