<?php $today = date('Y-m-d'); ?>
<!doctype html>
<html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#10243a">
<title>The Little Rule Workshop</title>
<style>
:root{--night:#10243a;--deep:#091724;--paper:#f3ead5;--ink:#18304a;--gold:#f1bd4a;--coral:#e86f51;--mint:#91c6ad;--blue:#7eb8d4;--line:rgba(241,189,74,.35)}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--night);color:var(--paper);font-family:"Palatino Linotype",Palatino,"Book Antiqua",serif;line-height:1.5;overflow-x:hidden}button{font:inherit;touch-action:manipulation}
.hero{position:relative;min-height:min(760px,92vh);display:grid;align-items:end;overflow:hidden;border-bottom:1px solid var(--line)}
.hero:before{content:"";position:absolute;inset:0;background:linear-gradient(90deg,rgba(9,23,36,.96),rgba(9,23,36,.72) 42%,rgba(9,23,36,.08) 75%),linear-gradient(0deg,var(--night),transparent 44%),url('little-rule-workshop-hero.webp') center/cover no-repeat;transform:scale(1.01)}
.hero:after{content:"";position:absolute;inset:0;opacity:.1;pointer-events:none;background-image:url("data:image/svg+xml,%3Csvg viewBox='0 0 140 140' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='.8' numOctaves='3'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E")}
.hero-copy{position:relative;z-index:1;width:min(1160px,100%);margin:auto;padding:clamp(34px,7vw,88px) clamp(20px,5vw,68px)}
.eyebrow,.kicker{color:var(--gold);text-transform:uppercase;letter-spacing:.17em;font:800 .7rem "Trebuchet MS",sans-serif}.eyebrow{display:flex;align-items:center;gap:11px}.eyebrow:before{content:"";width:40px;height:1px;background:currentColor}
h1{font-weight:400;font-size:clamp(3.3rem,9vw,7.5rem);letter-spacing:-.065em;line-height:.79;max-width:770px;margin:.22em 0 .28em;text-wrap:balance}h1 em{font-weight:400;color:var(--gold)}
.lede{max-width:590px;font-size:clamp(1.08rem,2vw,1.35rem);color:#d8e0df;margin:0 0 26px}
.start{display:inline-flex;gap:12px;align-items:center;background:var(--coral);color:#fff7e8;border-radius:99px;padding:13px 20px;font:800 .84rem "Trebuchet MS",sans-serif;text-decoration:none;box-shadow:0 8px 0 #9c422e;transition:.2s}.start:hover{transform:translateY(-2px);box-shadow:0 10px 0 #9c422e}
main{width:min(1160px,100%);margin:auto;padding:clamp(52px,8vw,100px) clamp(18px,4vw,52px)}
.intro{display:grid;grid-template-columns:.8fr 1.2fr;gap:clamp(28px,6vw,90px);align-items:end;margin-bottom:52px}h2{font-weight:400;font-size:clamp(2.3rem,5vw,4.5rem);line-height:.95;letter-spacing:-.045em;margin:.12em 0}.intro p{font-size:1.12rem;color:#cad6d6;margin:0}
.workbench{background:var(--paper);color:var(--ink);border-radius:30px 30px 12px 12px;box-shadow:0 18px 55px rgba(3,12,22,.3);overflow:hidden}.bench-head{display:flex;justify-content:space-between;gap:15px;padding:20px clamp(18px,4vw,40px);background:#dfd1b6;border-bottom:2px solid rgba(24,48,74,.15)}.bench-head strong{font:900 .76rem "Trebuchet MS",sans-serif;text-transform:uppercase;letter-spacing:.11em}.save-state{font-style:italic;color:#65727b;font-size:.87rem}
.bench-grid{display:grid;grid-template-columns:320px 1fr;min-height:610px}.parts{padding:30px 24px;background:#eee1c8;border-right:1px dashed rgba(24,48,74,.25)}.parts h3,.day h3{font-size:1.4rem;margin:0 0 5px}.hint{font-size:.87rem;color:#65727b;margin:0 0 20px}.practice-list{display:grid;gap:10px}.practice{width:100%;border:1px solid rgba(24,48,74,.16);border-left:7px solid var(--swatch);border-radius:10px;background:#fffaf0;color:var(--ink);padding:13px;text-align:left;cursor:pointer;box-shadow:0 3px 0 rgba(24,48,74,.09);transition:.18s}.practice:hover{transform:translateX(4px)}.practice.active{outline:3px solid var(--ink);outline-offset:2px;transform:translateX(6px)}.practice strong{display:block;font:800 .85rem "Trebuchet MS",sans-serif}.practice small{color:#69747a}
.day{padding:30px clamp(18px,4vw,42px) 38px;background-image:radial-gradient(rgba(24,48,74,.1) 1px,transparent 1px);background-size:18px 18px}.timeline{position:relative;display:grid;gap:15px;margin-top:26px}.timeline:before{content:"";position:absolute;left:24px;top:24px;bottom:24px;width:3px;background:repeating-linear-gradient(to bottom,var(--ink) 0 7px,transparent 7px 13px);opacity:.25}
.anchor{position:relative;display:grid;grid-template-columns:50px 1fr auto;align-items:center;gap:13px;min-height:78px;border:1px solid rgba(24,48,74,.15);background:rgba(255,250,240,.85);border-radius:16px;padding:10px;transition:.2s}.anchor.available{box-shadow:0 0 0 3px var(--gold);transform:translateX(5px);cursor:pointer}.clock{position:relative;z-index:1;width:48px;height:48px;border:2px solid var(--ink);display:grid;place-items:center;border-radius:50%;background:var(--paper);font:800 .65rem "Trebuchet MS",sans-serif}.anchor-name strong{display:block}.anchor-name small{color:#69747a}.slot{min-width:126px;text-align:right;font:700 .72rem "Trebuchet MS",sans-serif;color:#73808a}.chip{display:inline-flex;align-items:center;gap:7px;padding:8px 10px;border-radius:99px;background:var(--chip);color:var(--ink);box-shadow:inset 0 0 0 1px rgba(24,48,74,.12)}.remove{border:0;background:none;color:var(--ink);cursor:pointer;font-weight:bold;font-size:1rem;padding:0}
.controls{display:flex;justify-content:flex-end;gap:10px;flex-wrap:wrap;padding:18px clamp(18px,4vw,40px);background:#dfd1b6;border-top:1px solid rgba(24,48,74,.12)}.btn{border:1px solid var(--ink);border-radius:99px;background:transparent;color:var(--ink);padding:11px 16px;font:800 .78rem "Trebuchet MS",sans-serif;cursor:pointer}.btn.primary{background:var(--ink);color:var(--paper)}.btn:disabled{opacity:.35}
.simulation{margin-top:60px;display:none}.simulation.show{display:block;animation:rise .6s both}@keyframes rise{from{opacity:0;transform:translateY(20px)}}.sim-grid{display:grid;grid-template-columns:.8fr 1.2fr;gap:20px;margin-top:22px}.weather{background:#08131f;border:1px solid var(--line);border-radius:22px;padding:26px;min-height:280px;position:relative;overflow:hidden}.weather:after{content:"";position:absolute;width:230px;height:230px;border:1px solid var(--line);border-radius:50%;right:-90px;bottom:-100px;box-shadow:0 0 0 30px rgba(241,189,74,.025),0 0 0 60px rgba(241,189,74,.025)}.event-icon{font-size:3rem}.weather h3{font-size:1.75rem;margin:12px 0 4px}.weather p{color:#b9c9cd}.result{background:var(--paper);color:var(--ink);border-radius:22px;padding:26px;display:grid;align-content:center}.gauge{height:14px;background:#d9ccb1;border-radius:99px;overflow:hidden;margin:14px 0}.gauge-fill{height:100%;width:0;background:linear-gradient(90deg,var(--coral),var(--gold),var(--mint));transition:width 1.2s;border-radius:inherit}.result h3{font-size:clamp(1.7rem,4vw,2.7rem);line-height:1;margin:4px 0 10px}.result p{margin:0;color:#5b6871}.survivors{display:flex;flex-wrap:wrap;gap:8px;margin-top:18px}.survivor{padding:7px 10px;border-radius:99px;background:#dcebdd;font:700 .72rem "Trebuchet MS",sans-serif}.survivor.missed{background:#ead9d0;text-decoration:line-through;opacity:.65}
.takeaway{margin:70px auto 0;max-width:820px;text-align:center}.takeaway blockquote{margin:18px 0;font-size:clamp(1.65rem,4vw,3rem);line-height:1.14}.takeaway p{color:#b8c8ca}.source{color:var(--gold);text-underline-offset:4px}footer{display:flex;justify-content:space-between;gap:20px;flex-wrap:wrap;margin-top:70px;padding-top:24px;border-top:1px solid var(--line);font:700 .7rem "Trebuchet MS",sans-serif;text-transform:uppercase;letter-spacing:.12em;color:#8fa2a9}footer a{color:inherit}.toast{position:fixed;bottom:18px;left:50%;transform:translate(-50%,120px);z-index:9;background:#fffaf0;color:var(--ink);padding:12px 17px;border-radius:99px;box-shadow:0 15px 50px #0006;font:800 .78rem "Trebuchet MS",sans-serif;transition:.35s}.toast.show{transform:translate(-50%,0)}
@media(max-width:760px){.hero{min-height:760px}.hero:before{background:linear-gradient(0deg,var(--night),rgba(9,23,36,.2) 65%),url('little-rule-workshop-hero.webp') 62% center/cover no-repeat}.hero-copy{padding-top:300px}.intro,.sim-grid{grid-template-columns:1fr}.bench-grid{grid-template-columns:1fr}.parts{border-right:0;border-bottom:1px dashed rgba(24,48,74,.25)}.practice-list{grid-template-columns:1fr 1fr}.anchor{grid-template-columns:44px 1fr}.clock{width:42px;height:42px}.slot{grid-column:2;text-align:left;min-width:0}.timeline:before{left:21px}.controls .btn{flex:1}}@media(max-width:420px){h1{font-size:3.25rem}.practice-list{grid-template-columns:1fr}.hero-copy{padding-top:340px}.bench-head{flex-direction:column;gap:3px}}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;animation:none!important;transition:none!important}}
</style></head>
<body>
<header class="hero"><div class="hero-copy"><div class="eyebrow">A tiny rhythm for an actual life</div><h1>The Little <em>Rule</em> Workshop</h1><p class="lede">Fasten prayer to the things your day already does. Then send your little rule through a realistically unruly Tuesday.</p><a class="start" href="#workshop">Open the workbench <span aria-hidden="true">↓</span></a></div></header>
<main>
<section class="intro" id="workshop"><div><span class="kicker">01 · Build</span><h2>Use the hooks already on the wall.</h2></div><p>Select a small practice, then attach it to an ordinary moment. The strongest rule is not the most heroic one. It is the one that still exists after the cereal spills.</p></section>
<section class="workbench" aria-label="Prayer rhythm builder">
<div class="bench-head"><strong>Domestic Rhythm Bench · <?php echo htmlspecialchars($today); ?></strong><span class="save-state" id="saveState">Your bench is ready.</span></div>
<div class="bench-grid"><aside class="parts"><h3>Small practices</h3><p class="hint">Choose one, then choose its home in the day.</p><div class="practice-list" id="practiceList"></div></aside><div class="day"><h3>Your ordinary day</h3><p class="hint" id="dayHint">Empty hooks are perfectly respectable.</p><div class="timeline" id="timeline"></div></div></div>
<div class="controls"><button class="btn" id="clearBtn">Clear the bench</button><button class="btn" id="copyBtn">Copy my little rule</button><button class="btn primary" id="testBtn" disabled>Test this day →</button></div>
</section>
<section class="simulation" id="simulation" aria-live="polite"><span class="kicker">02 · Stress test</span><h2>Tuesday has entered the workshop.</h2><div class="sim-grid"><article class="weather"><div class="event-icon" id="eventIcon">☂</div><h3 id="eventTitle"></h3><p id="eventText"></p></article><article class="result"><span class="kicker">Rhythm resilience</span><div class="gauge"><div class="gauge-fill" id="gaugeFill"></div></div><h3 id="resultTitle"></h3><p id="resultText"></p><div class="survivors" id="survivors"></div></article></div></section>
<section class="takeaway"><span class="kicker">The workshop principle</span><blockquote>Prayer does not need a spare life. It needs a small, faithful place in this one.</blockquote><p>Inspired by Jon's <a class="source" href="https://cooltoolsforcatholics.blogspot.com/2024/12/faith-meets-innovation-using-ai-for.html">“Faith Meets Innovation: Using AI for Spiritual Direction”</a>, especially the wonderfully practical advice to anchor prayer to routines that already happen.</p></section>
<footer><span>Built for Chloe Reads Jon</span><a href="./">Return to the collection</a></footer>
</main><div class="toast" id="toast" role="status"></div>
<script>
const practices=[
{id:'offer',name:'Morning offering',short:'Offer the day',detail:'One sentence · 20 sec',color:'#f1bd4a',weight:1},
{id:'quiet',name:'Wordless glance',short:'Be still',detail:'Quiet presence · 2 min',color:'#7eb8d4',weight:2},
{id:'psalm',name:'One line of a Psalm',short:'Read one line',detail:'Scripture · 1 min',color:'#91c6ad',weight:2},
{id:'grace',name:'Grace + one intention',short:'Bless and notice',detail:'At the table · 30 sec',color:'#e89b51',weight:1},
{id:'rose',name:'Rose, thorn & help',short:'Share the day',detail:'Together · 3 min',color:'#e86f73',weight:3}];
const anchors=[
{id:'brush',time:'7:15',name:'After brushing teeth',detail:'The tap turns off',stability:3},
{id:'mug',time:'8:05',name:'With the first drink',detail:'Kettle, coffee, or water',stability:2},
{id:'door',time:'8:40',name:'At the front door',detail:'Before the day scatters',stability:1},
{id:'table',time:'18:15',name:'When supper lands',detail:'The plates arrive',stability:3},
{id:'lamp',time:'21:20',name:'When the bedside lamp glows',detail:'The day folds up',stability:2}];
const events=[
{icon:'🥣',title:'The cereal incident',text:'Breakfast is late, one sock has vanished, and the floor has become strangely educational.',hit:['mug','door']},
{icon:'📞',title:'The surprise phone call',text:'A ten-minute call becomes forty. Supper shifts and everyone arrives at the table sideways.',hit:['table']},
{icon:'🌧',title:'Rain, traffic, detour',text:'The schedule loses twenty-five minutes and the front-door moment is mostly umbrellas.',hit:['door','table']},
{icon:'🪫',title:'The very low battery day',text:'Nothing dramatic happened. Everyone is simply operating at twelve percent.',hit:['quiet','rose']},
{icon:'✨',title:'An almost suspiciously good day',text:'The toast behaves. The traffic behaves. Even bedtime remembers its indoor voice.',hit:[]}];
let plan=JSON.parse(localStorage.getItem('littleRulePlan')||'{}'),selected=null;const $=s=>document.querySelector(s);
function render(){
 $('#practiceList').innerHTML=practices.map(p=>`<button class="practice ${selected===p.id?'active':''}" style="--swatch:${p.color}" data-practice="${p.id}" aria-pressed="${selected===p.id}"><strong>${p.name}</strong><small>${p.detail}</small></button>`).join('');
 $('#timeline').innerHTML=anchors.map(a=>{const p=practices.find(x=>x.id===plan[a.id]);return `<div class="anchor ${selected?'available':''}" data-anchor="${a.id}"><div class="clock">${a.time}</div><div class="anchor-name"><strong>${a.name}</strong><small>${a.detail}</small></div><div class="slot">${p?`<span class="chip" style="--chip:${p.color}">${p.short}<button class="remove" data-remove="${a.id}" aria-label="Remove ${p.name}">×</button></span>`:'open hook'}</div></div>`}).join('');
 $('#testBtn').disabled=!Object.keys(plan).length;$('#dayHint').textContent=selected?'Now choose an ordinary moment.':Object.keys(plan).length?'Click another practice to keep building.':'Empty hooks are perfectly respectable.'}
function save(){localStorage.setItem('littleRulePlan',JSON.stringify(plan));$('#saveState').textContent='Saved quietly on this device.'}
document.addEventListener('click',e=>{const p=e.target.closest('[data-practice]');if(p){selected=p.dataset.practice;render();return}const r=e.target.closest('[data-remove]');if(r){e.stopPropagation();delete plan[r.dataset.remove];save();render();return}const a=e.target.closest('[data-anchor]');if(a&&selected){Object.keys(plan).forEach(k=>{if(plan[k]===selected)delete plan[k]});plan[a.dataset.anchor]=selected;selected=null;save();render()}});
$('#clearBtn').onclick=()=>{plan={};selected=null;save();render();$('#simulation').classList.remove('show')};
$('#copyBtn').onclick=async()=>{if(!Object.keys(plan).length){toast('Fasten at least one practice first.');return}const lines=anchors.filter(a=>plan[a.id]).map(a=>`• ${a.name}: ${practices.find(p=>p.id===plan[a.id]).name}`);try{await navigator.clipboard.writeText(`My little rule\n${lines.join('\n')}\n\nSmall enough for an actual day.`);toast('Your little rule is copied.')}catch{toast('Copying is unavailable in this browser.')}};
$('#testBtn').onclick=()=>{const ev=events[Math.floor(Math.random()*events.length)],entries=anchors.filter(a=>plan[a.id]);let survived=0;const chips=entries.map(a=>{const p=practices.find(x=>x.id===plan[a.id]),disrupted=ev.hit.includes(a.id)||ev.hit.includes(p.id),holds=!disrupted||(a.stability+p.weight<=3&&Math.random()>.35);if(holds)survived++;return `<span class="survivor ${holds?'':'missed'}">${p.short}</span>`});const score=Math.round(survived/entries.length*100);$('#eventIcon').textContent=ev.icon;$('#eventTitle').textContent=ev.title;$('#eventText').textContent=ev.text;$('#resultTitle').textContent=score===100?'The little rule holds.':score>=50?'Bent, not broken.':'Make it smaller, not sterner.';$('#resultText').textContent=score===100?'Every practice found its way through. Ordinary anchors are doing the heavy lifting.':score>=50?'Some moments slipped, and the rhythm still has a pulse. That counts.':'A hard day is useful data, not a spiritual report card. Try one shorter practice on one sturdier hook.';$('#survivors').innerHTML=chips.join('');$('#simulation').classList.add('show');requestAnimationFrame(()=>$('#gaugeFill').style.width=score+'%');$('#simulation').scrollIntoView({behavior:'smooth'})};
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2400)}render();
</script></body></html>
