<?php
declare(strict_types=1);
header('Content-Type: text/html; charset=UTF-8');
?>
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="theme-color" content="#121311">
<title>The Three Merit Trials</title>
<style>
:root{--ink:#151613;--paper:#efe5d2;--paper2:#d8c9b0;--cyan:#58ccd1;--orange:#f06b2d;--lime:#c6d942;--muted:#a69b88;--line:rgba(239,229,210,.18)}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:#10110f;color:var(--paper);font-family:"Courier Prime","Nimbus Mono PS","Courier New",monospace;line-height:1.55;overflow-x:hidden}button,input{font:inherit}button{touch-action:manipulation}.grain{position:fixed;inset:0;z-index:20;pointer-events:none;opacity:.16;background-image:url("data:image/svg+xml,%3Csvg viewBox='0 0 180 180' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='.8' numOctaves='3' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='.27'/%3E%3C/svg%3E")}
a{color:inherit}.shell{width:min(1180px,100%);margin:auto;padding:0 24px}.eyebrow{text-transform:uppercase;letter-spacing:.18em;font-size:.72rem;color:var(--cyan);font-weight:500}.hero{min-height:92vh;position:relative;display:grid;align-items:end;padding:34px 0 64px;isolation:isolate;background:#111}.hero:before{content:"";position:absolute;inset:0;z-index:-2;background:linear-gradient(90deg,rgba(11,12,10,.95) 0%,rgba(11,12,10,.75) 46%,rgba(11,12,10,.16) 78%),linear-gradient(0deg,#10110f 0%,transparent 35%),url('mac-merit-trials-hero.webp') center/cover no-repeat}.hero:after{content:"TEST FACILITY  /  2010";position:absolute;right:28px;top:27px;padding:7px 10px;border:1px solid rgba(239,229,210,.35);font-size:.67rem;letter-spacing:.17em;transform:rotate(1deg);color:#f7ecd8;background:rgba(12,13,11,.55);backdrop-filter:blur(8px)}.hero-copy{max-width:660px}.hero h1{font-family:Baskerville,"Iowan Old Style","Palatino Linotype",serif;font-size:clamp(3.4rem,9vw,8.5rem);line-height:.78;letter-spacing:-.065em;margin:18px 0 28px}.hero h1 span{display:block;color:transparent;-webkit-text-stroke:1.5px var(--paper);margin-left:clamp(22px,9vw,112px)}.dek{max-width:570px;font-family:Baskerville,"Iowan Old Style","Palatino Linotype",serif;font-size:clamp(1.05rem,2vw,1.35rem);color:#e5dac7}.start{display:inline-flex;align-items:center;gap:13px;margin-top:25px;text-decoration:none;text-transform:uppercase;letter-spacing:.12em;font-size:.78rem;background:var(--orange);color:#17130f;padding:15px 19px;box-shadow:6px 6px 0 #f5dfbd;transition:.2s}.start:hover{transform:translate(-2px,-2px);box-shadow:9px 9px 0 #f5dfbd}.start b{font-size:1.25rem}
.manifesto{padding:90px 0;display:grid;grid-template-columns:.7fr 1.3fr;gap:70px;border-bottom:1px solid var(--line)}.manifesto blockquote{font-family:Baskerville,"Iowan Old Style","Palatino Linotype",serif;font-size:clamp(2rem,4.2vw,4.3rem);line-height:1.02;margin:0}.manifesto blockquote em{color:var(--orange);font-style:normal}.manifesto p{margin:0;color:var(--paper2);max-width:520px}.counter{display:grid;grid-template-columns:repeat(3,1fr);margin-top:38px;border-top:1px solid var(--line)}.counter div{padding:15px 5px;border-right:1px solid var(--line)}.counter div:last-child{border:0}.counter strong{display:block;font-family:Baskerville,"Iowan Old Style","Palatino Linotype",serif;font-size:2.5rem;color:var(--lime)}.counter small{text-transform:uppercase;letter-spacing:.12em;color:var(--muted)}
.trial{padding:100px 0;border-bottom:1px solid var(--line);position:relative}.trial-grid{display:grid;grid-template-columns:minmax(0,.86fr) minmax(0,1.25fr);gap:clamp(40px,8vw,110px);align-items:center}.trial:nth-of-type(even) .trial-grid{grid-template-columns:minmax(0,1.25fr) minmax(0,.86fr)}.trial:nth-of-type(even) .lab{order:-1}.num{font-family:Baskerville,"Iowan Old Style","Palatino Linotype",serif;color:var(--orange);font-size:1.1rem}.trial h2{font-family:Baskerville,"Iowan Old Style","Palatino Linotype",serif;font-size:clamp(2.6rem,6vw,5.6rem);line-height:.87;letter-spacing:-.05em;margin:14px 0 23px}.trial-copy p{color:var(--paper2);max-width:450px}.status{margin-top:26px;display:inline-flex;gap:10px;align-items:center;text-transform:uppercase;letter-spacing:.12em;font-size:.72rem;color:var(--muted)}.status i{display:block;width:10px;height:10px;border:1px solid var(--muted);border-radius:50%}.status.passed{color:var(--lime)}.status.passed i{background:var(--lime);border-color:var(--lime);box-shadow:0 0 18px var(--lime)}
.lab{position:relative;background:#201f1b;border:1px solid #565044;padding:clamp(18px,4vw,38px);box-shadow:18px 18px 0 #090a08}.lab:before{content:"";position:absolute;inset:8px;border:1px dashed rgba(239,229,210,.15);pointer-events:none}.plate{position:relative;background:var(--paper);color:var(--ink);padding:12px 16px;text-transform:uppercase;letter-spacing:.13em;font-size:.66rem;display:flex;justify-content:space-between;margin-bottom:22px}.screws:after{content:"⊙  ⊙";color:#766e61}.btn{border:1px solid var(--paper);background:transparent;color:var(--paper);padding:13px 17px;text-transform:uppercase;letter-spacing:.09em;font-size:.74rem;cursor:pointer;transition:.15s}.btn:hover,.btn:focus-visible{background:var(--paper);color:var(--ink)}.btn.hot{background:var(--orange);border-color:var(--orange);color:#17130f;font-weight:500}.btn.hot:hover{filter:brightness(1.15)}
.speed-stage{height:310px;display:grid;place-items:center;position:relative;overflow:hidden;background:radial-gradient(circle at 50% 45%,#34342e,#151613 65%);border:1px solid #4b483f}.speed-stage.ready{cursor:crosshair}.speed-stage.go{background:radial-gradient(circle at 50% 45%,#518e8d,#112b2b 62%)}.signal{width:158px;height:158px;border-radius:50%;display:grid;place-items:center;border:2px solid #625f55;box-shadow:inset 0 0 0 15px #1a1b18,0 10px 50px #000;background:#252620;color:var(--muted);font-family:Baskerville,"Iowan Old Style","Palatino Linotype",serif;font-size:1.35rem;text-align:center;transition:.12s}.go .signal{background:var(--cyan);color:#0d2525;border-color:#d9ffff;box-shadow:inset 0 0 0 15px #224748,0 0 60px rgba(88,204,209,.6);transform:scale(1.04)}.speed-result{position:absolute;bottom:17px;left:18px;right:18px;display:flex;justify-content:space-between;color:var(--muted);font-size:.72rem}.speed-result strong{color:var(--paper);font-size:1rem}.controls{display:flex;gap:11px;flex-wrap:wrap;margin-top:16px}
.terminal{background:#090d0c;border:1px solid #43645f;min-height:330px;padding:20px;color:#8be5c8;box-shadow:inset 0 0 45px rgba(63,191,157,.07)}.termhead{display:flex;justify-content:space-between;color:#5e8e80;font-size:.69rem;border-bottom:1px solid #203c34;padding-bottom:10px}.prompt{margin:24px 0 16px;color:#d1eadf}.commandline{min-height:57px;padding:12px;border:1px solid #315c50;background:#0c1512;display:flex;align-items:center;gap:6px;flex-wrap:wrap}.commandline:before{content:"$";color:var(--lime)}.slot-placeholder{color:#3e665a}.chips{display:flex;gap:8px;flex-wrap:wrap;margin-top:17px}.chip{background:#16251f;color:#9be7cf;border:1px solid #3d705f;padding:9px 11px;cursor:pointer;font-size:.75rem}.chip:hover{border-color:var(--lime);color:var(--lime)}.chip.used{opacity:.28;pointer-events:none}.term-msg{min-height:42px;margin-top:17px;font-size:.77rem;color:#6f9e90}.term-msg.good{color:var(--lime)}
.design-bench{display:grid;grid-template-columns:1.2fr .8fr;gap:24px}.poster{min-height:340px;background:#e6dbc7;position:relative;overflow:hidden;box-shadow:inset 0 0 0 1px #fff;--h:190;--gap:28px;--round:20px}.poster:before{content:"FORM /  FUNCTION";position:absolute;top:23px;left:24px;color:#262620;font-size:.62rem;letter-spacing:.16em}.shape{position:absolute;transition:.25s ease;background:hsl(var(--h) 62% 50%)}.s1{width:47%;height:41%;left:10%;top:25%;border-radius:var(--round) 50% var(--round) 50%;transform:translateX(calc((var(--gap) - 28px)*-.25)) rotate(-8deg)}.s2{width:35%;height:55%;right:8%;bottom:6%;border-radius:50% var(--round) 50% var(--round);background:#1d1e1b;transform:translateX(calc((var(--gap) - 28px)*.25)) rotate(12deg)}.s3{height:5px;left:9%;right:9%;bottom:13%;background:var(--orange);transform:rotate(-4deg)}.poster small{position:absolute;bottom:18px;left:24px;color:#34342e;letter-spacing:.1em}.knobs label{display:block;margin-bottom:24px;color:var(--paper2);font-size:.72rem;text-transform:uppercase;letter-spacing:.1em}.knobs input{display:block;width:100%;margin-top:10px;accent-color:var(--orange)}.beauty-score{border-top:1px solid var(--line);padding-top:18px;margin-top:6px}.beauty-score strong{font-family:Baskerville,"Iowan Old Style","Palatino Linotype",serif;color:var(--orange);font-size:2.5rem}
.verdict{padding:110px 0;background:var(--paper);color:var(--ink);text-align:center}.seal{width:110px;height:110px;margin:0 auto 27px;border:2px solid var(--ink);border-radius:50%;display:grid;place-items:center;font-family:Baskerville,"Iowan Old Style","Palatino Linotype",serif;font-size:3rem;box-shadow:inset 0 0 0 7px var(--paper),inset 0 0 0 9px var(--ink);transform:rotate(-7deg)}.verdict h2{font-family:Baskerville,"Iowan Old Style","Palatino Linotype",serif;font-size:clamp(3rem,7vw,7rem);line-height:.9;letter-spacing:-.055em;margin:0}.verdict p{max-width:580px;margin:25px auto;color:#504b42}.scoreline{display:flex;justify-content:center;gap:clamp(25px,7vw,90px);margin:38px 0}.scoreline strong{font-family:Baskerville,"Iowan Old Style","Palatino Linotype",serif;font-size:2.3rem;display:block}.scoreline small{text-transform:uppercase;letter-spacing:.12em}.verdict .btn{border-color:var(--ink);color:var(--ink)}.verdict .btn:hover{background:var(--ink);color:var(--paper)}
footer{padding:38px 0;color:var(--muted);font-size:.74rem}.foot{display:flex;justify-content:space-between;gap:24px;flex-wrap:wrap}footer a:hover{color:var(--cyan)}
@media(max-width:760px){.shell{padding:0 18px}.hero{min-height:820px;align-items:end}.hero:before{background:linear-gradient(0deg,#10110f 4%,rgba(11,12,10,.72) 50%,rgba(11,12,10,.18)),url('mac-merit-trials-hero.webp') 54% center/cover no-repeat}.hero h1{font-size:clamp(3.7rem,18vw,5.7rem)}.manifesto,.trial-grid,.trial:nth-of-type(even) .trial-grid{grid-template-columns:1fr;gap:38px}.trial:nth-of-type(even) .lab{order:initial}.manifesto{padding:65px 0}.trial{padding:72px 0}.lab{box-shadow:9px 9px 0 #090a08;padding:18px}.design-bench{grid-template-columns:1fr}.poster{min-height:280px}.counter strong{font-size:1.9rem}.hero:after{right:16px}.scoreline{gap:18px}.scoreline strong{font-size:1.8rem}}
@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;transition:none!important}}
</style>
</head>
<body>
<div class="grain"></div>
<header class="hero">
  <div class="shell hero-copy">
    <div class="eyebrow">A three-part proving ground</div>
    <h1>Merit <span>Trials</span></h1>
    <p class="dek">In 2010 Jon switched computers and found three things worth caring about: speed, Unixy goodness, and beauty. Enter the lab. Put all three on the bench.</p>
    <a class="start" href="#briefing">Begin inspection <b>↓</b></a>
  </div>
</header>
<main>
  <section class="shell manifesto" id="briefing">
    <div class="eyebrow">The inspection brief / 01</div>
    <div>
      <blockquote>Good tools should feel <em>swift</em>, speak the language of power, and leave the room prettier.</blockquote>
      <p style="margin-top:28px">Three compact trials await. Each earns a brass merit stamp. There are no spec sheets here, only the qualities you can actually feel.</p>
      <div class="counter"><div><strong>01</strong><small>Reflex</small></div><div><strong>02</strong><small>Command</small></div><div><strong>03</strong><small>Form</small></div></div>
    </div>
  </section>

  <section class="trial" id="speed">
    <div class="shell trial-grid">
      <div class="trial-copy"><span class="num">01 / SPEED</span><h2>The Wake Test</h2><p>A computer that is ready before your train of thought wanders off is not merely fast. It is polite. Arm the signal, wait for cyan, then strike it as quickly as you can.</p><div class="status" id="speedStatus"><i></i><span>Merit stamp pending</span></div></div>
      <div class="lab"><div class="plate"><span>Reaction chamber · ms</span><span class="screws"></span></div><div class="speed-stage" id="speedStage" role="button" tabindex="0" aria-label="Reaction speed test"><div class="signal" id="signal">Stand by</div><div class="speed-result"><span>Human wake latency</span><strong id="speedReadout">— ms</strong></div></div><div class="controls"><button class="btn hot" id="armBtn">Arm the test</button><button class="btn" id="speedReset">Reset</button></div></div>
    </div>
  </section>

  <section class="trial" id="unix">
    <div class="shell trial-grid">
      <div class="trial-copy"><span class="num">02 / UNIXY GOODNESS</span><h2>Pipe Works</h2><p>The useful sort of power is composable. Build three tiny commands from ordinary parts and send their output flowing into the next tool.</p><div class="status" id="unixStatus"><i></i><span>0 of 3 lines flowing</span></div></div>
      <div class="lab"><div class="plate"><span>Command conduit · sh</span><span class="screws"></span></div><div class="terminal"><div class="termhead"><span>MERIT-OS 10.6</span><span>PIPE PRESSURE: NOMINAL</span></div><div class="prompt" id="taskText"></div><div class="commandline" id="commandLine"><span class="slot-placeholder">choose parts below…</span></div><div class="chips" id="chips"></div><div class="term-msg" id="termMsg">Build the command from left to right.</div></div><div class="controls"><button class="btn" id="undoChip">Undo</button><button class="btn hot" id="runCommand">Run line ↵</button></div></div>
    </div>
  </section>

  <section class="trial" id="beauty">
    <div class="shell trial-grid">
      <div class="trial-copy"><span class="num">03 / BEAUTY</span><h2>The Quiet Object</h2><p>Beauty is not frosting. It is the moment the parts stop arguing. Tune the colour, breathing room, and softness until the composition feels settled, then trust your eye.</p><div class="status" id="beautyStatus"><i></i><span>Awaiting your eye</span></div></div>
      <div class="lab"><div class="plate"><span>Form calibration · subjective</span><span class="screws"></span></div><div class="design-bench"><div class="poster" id="poster"><div class="shape s1"></div><div class="shape s2"></div><div class="shape s3"></div><small>CALIBRATION PRINT / 03</small></div><div class="knobs"><label>Colour temperature<input id="hue" type="range" min="160" max="215" value="190"></label><label>Breathing room<input id="gap" type="range" min="0" max="56" value="28"></label><label>Edge character<input id="round" type="range" min="0" max="70" value="20"></label><div class="beauty-score"><small>Visual tension</small><br><strong id="tension">42</strong><small> / 100</small></div><button class="btn hot" id="approveBeauty" style="margin-top:17px;width:100%">This feels right</button></div></div></div>
    </div>
  </section>

  <section class="verdict" id="verdict"><div class="shell"><div class="seal" id="seal">?</div><div class="eyebrow" style="color:#6d6253">Final inspection</div><h2 id="verdictTitle">The jury is still out.</h2><p id="verdictText">Complete all three trials and the laboratory will issue its gloriously unofficial verdict.</p><div class="scoreline"><div><strong id="scoreSpeed">—</strong><small>Speed</small></div><div><strong id="scoreUnix">0/3</strong><small>Unix</small></div><div><strong id="scoreBeauty">—</strong><small>Beauty</small></div></div><button class="btn" id="resetAll">Reopen the lab</button></div></section>
</main>
<footer><div class="shell foot"><a href="index.php">← Chloe Reads Jon</a><span>Inspired by Jon's <a href="https://jona.ca/2010/05/3-reasons-i-like-mac.html">“3 Reasons I Like The Mac”</a></span></div></footer>
<script>
const state={speed:null,unix:0,beauty:null};
const $=s=>document.querySelector(s);
let timer=null,armedAt=0,phase='idle';
function tone(freq=440,d=.08){try{const c=new (window.AudioContext||window.webkitAudioContext)(),o=c.createOscillator(),g=c.createGain();o.frequency.value=freq;o.type='sine';g.gain.setValueAtTime(.05,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+d);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+d)}catch(e){}}
function setStatus(id,text,pass=false){const el=$(id);el.querySelector('span').textContent=text;el.classList.toggle('passed',pass)}
function arm(){clearTimeout(timer);phase='waiting';$('#speedStage').className='speed-stage ready';$('#signal').textContent='Wait…';$('#speedReadout').textContent='— ms';timer=setTimeout(()=>{phase='go';armedAt=performance.now();$('#speedStage').className='speed-stage go';$('#signal').textContent='NOW';tone(760,.09)},900+Math.random()*1900)}
function strike(){if(phase==='waiting'){clearTimeout(timer);phase='idle';$('#signal').textContent='Too soon';$('#speedStage').className='speed-stage';$('#speedReadout').textContent='false start';tone(130,.16);return}if(phase!=='go')return;const ms=Math.round(performance.now()-armedAt);phase='done';state.speed=ms;$('#speedStage').className='speed-stage';$('#signal').textContent=ms<260?'Quick!':ms<420?'Awake':'Coffee?';$('#speedReadout').textContent=ms+' ms';setStatus('#speedStatus',ms<300?'Speed merit awarded':'Speed trial complete',true);$('#scoreSpeed').textContent=ms+'ms';tone(520,.12);setTimeout(()=>tone(780,.13),80);updateVerdict()}
$('#armBtn').onclick=arm;$('#speedStage').onclick=strike;$('#speedStage').onkeydown=e=>{if(e.key===' '||e.key==='Enter'){e.preventDefault();strike()}};$('#speedReset').onclick=()=>{clearTimeout(timer);phase='idle';state.speed=null;$('#speedStage').className='speed-stage';$('#signal').textContent='Stand by';$('#speedReadout').textContent='— ms';$('#scoreSpeed').textContent='—';setStatus('#speedStatus','Merit stamp pending');updateVerdict()};
const rounds=[
 {task:'Find every note containing the word “wonder”.',parts:['grep','-ril','"wonder"','.'],answer:['grep','-ril','"wonder"','.'],noise:['sort','*.png']},
 {task:'List log files, then count the lines.',parts:['find','.','-name','"*.log"','|','wc','-l'],answer:['find','.','-name','"*.log"','|','wc','-l'],noise:['rm','open']},
 {task:'Show the five largest folders in human units.',parts:['du','-sh','*','|','sort','-hr','|','head','-5'],answer:['du','-sh','*','|','sort','-hr','|','head','-5'],noise:['cat','-x']}
];let picked=[];
function loadRound(){const r=rounds[state.unix];if(!r)return;$('#taskText').textContent=r.task;picked=[];renderLine();const all=[...r.parts,...r.noise].sort(()=>Math.random()-.5);$('#chips').innerHTML='';all.forEach((p,i)=>{const b=document.createElement('button');b.className='chip';b.textContent=p;b.dataset.id=i;b.onclick=()=>{picked.push({p,b});b.classList.add('used');renderLine()};$('#chips').appendChild(b)});$('#termMsg').className='term-msg';$('#termMsg').textContent='Build the command from left to right.'}
function renderLine(){const el=$('#commandLine');el.innerHTML='';if(!picked.length){el.innerHTML='<span class="slot-placeholder">choose parts below…</span>';return}picked.forEach(x=>{const s=document.createElement('span');s.textContent=x.p;el.appendChild(s)})}
$('#undoChip').onclick=()=>{const x=picked.pop();if(x)x.b.classList.remove('used');renderLine()};
$('#runCommand').onclick=()=>{if(state.unix>=3)return;const ok=JSON.stringify(picked.map(x=>x.p))===JSON.stringify(rounds[state.unix].answer);if(!ok){$('#termMsg').className='term-msg';$('#termMsg').textContent='⚠ No flow. Check the order and try again.';tone(150,.13);return}state.unix++;tone(430,.08);setTimeout(()=>tone(650,.08),70);$('#scoreUnix').textContent=state.unix+'/3';setStatus('#unixStatus',state.unix===3?'Unix merit awarded':state.unix+' of 3 lines flowing',state.unix===3);$('#termMsg').className='term-msg good';$('#termMsg').textContent='✓ Output flowing cleanly.';if(state.unix<3)setTimeout(loadRound,850);else{$('#taskText').textContent='All conduits are open.';$('#chips').innerHTML='';$('#commandLine').innerHTML='<span>echo "Unixy goodness confirmed"</span>';updateVerdict()}};
loadRound();
function tune(){const h=$('#hue').value,g=$('#gap').value,r=$('#round').value;$('#poster').style.setProperty('--h',h);$('#poster').style.setProperty('--gap',g+'px');$('#poster').style.setProperty('--round',r+'px');const raw=Math.abs(h-184)*.65+Math.abs(g-36)*.7+Math.abs(r-34)*.45;const t=Math.max(9,Math.min(88,Math.round(18+raw)));$('#tension').textContent=t;state.beauty=null;$('#scoreBeauty').textContent='—';setStatus('#beautyStatus','Awaiting your eye');updateVerdict()}
['hue','gap','round'].forEach(id=>$('#'+id).oninput=tune);tune();
$('#approveBeauty').onclick=()=>{const t=Number($('#tension').textContent);state.beauty=Math.max(62,104-t);$('#scoreBeauty').textContent=state.beauty+'%';setStatus('#beautyStatus','Beauty merit awarded',true);tone(392,.12);setTimeout(()=>tone(523,.15),90);updateVerdict()};
function updateVerdict(){if(state.speed===null||state.unix<3||state.beauty===null){$('#seal').textContent='?';$('#verdictTitle').textContent='The jury is still out.';$('#verdictText').textContent='Complete all three trials and the laboratory will issue its gloriously unofficial verdict.';return}const s=Math.max(40,Math.min(100,Math.round(120-state.speed/5)));const total=Math.round((s+state.beauty+100)/3);$('#seal').textContent=total;$('#verdictTitle').textContent=total>=88?'A tool with manners.':total>=73?'Three merits, well earned.':'Beautifully imperfect.';$('#verdictText').textContent=`Final merit index: ${total}/100. Fast enough to protect attention, powerful enough to reward curiosity, and composed enough to deserve a place in the room.`;$('#verdict').scrollIntoView({behavior:'smooth',block:'center'})}
$('#resetAll').onclick=()=>location.reload();
</script>
</body>
</html>
