<?php $sourceUrl = 'https://jona.ca/2011/06/how-to-carry-on-debate-in-comment.html'; ?>
<!DOCTYPE html><html lang="en"><head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#101a24">
<title>The Reply Tempering Room</title>
<style>
:root{--ink:#101a24;--paper:#f3e8ce;--cream:#fff8e8;--red:#d34a32;--teal:#397f7b;--gold:#d9a52f;--muted:#99a4a4;--line:rgba(243,232,206,.18)}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--ink);color:var(--paper);font-family:Georgia,'Times New Roman',serif;min-height:100vh;overflow-x:hidden}body:before{content:'';position:fixed;inset:0;pointer-events:none;opacity:.22;background-image:url("data:image/svg+xml,%3Csvg viewBox='0 0 180 180' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='.8' numOctaves='3' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='.13'/%3E%3C/svg%3E");z-index:10;mix-blend-mode:soft-light}a{color:inherit}button{font:inherit;touch-action:manipulation}.topbar{width:min(1120px,calc(100% - 34px));margin:auto;padding:20px 0;display:flex;justify-content:space-between;align-items:center;font-family:'Trebuchet MS',sans-serif;font-size:.78rem;letter-spacing:.12em;text-transform:uppercase}.back{text-decoration:none;opacity:.78}.back:hover{opacity:1}.stamp{border:1px solid var(--gold);color:var(--gold);padding:7px 10px;transform:rotate(1deg)}
.hero{width:min(1120px,calc(100% - 34px));margin:18px auto 0;display:grid;grid-template-columns:.92fr 1.08fr;align-items:center;min-height:570px}.hero-copy{position:relative;z-index:2;padding:60px 0 70px}.eyebrow{color:var(--gold);font-family:'Trebuchet MS',sans-serif;font-weight:800;letter-spacing:.18em;text-transform:uppercase;font-size:.74rem}h1{font-size:clamp(3.45rem,8vw,7.6rem);line-height:.8;letter-spacing:-.065em;font-weight:500;margin:26px 0 30px;max-width:760px}h1 span{color:var(--red);display:block;font-style:italic}.lede{max-width:520px;font-size:clamp(1.05rem,2vw,1.32rem);line-height:1.62;color:#dacfb9}.begin{display:inline-flex;align-items:center;gap:14px;margin-top:28px;background:var(--gold);color:var(--ink);padding:15px 19px;text-decoration:none;font-family:'Trebuchet MS',sans-serif;font-weight:900;text-transform:uppercase;letter-spacing:.08em;box-shadow:7px 7px 0 var(--red)}.hero-art{position:relative;margin-left:-74px;transform:rotate(2deg)}.hero-art:before{content:'';position:absolute;inset:17px -17px -17px 17px;border:2px solid var(--gold);z-index:-1}.hero-art img{width:100%;display:block;filter:saturate(.92) contrast(1.05);clip-path:polygon(4% 2%,100% 0,96% 97%,0 100%)}.caption{position:absolute;bottom:-38px;right:8px;color:var(--muted);font:.72rem 'Trebuchet MS',sans-serif;letter-spacing:.1em;text-transform:uppercase}
.bench{background:var(--paper);color:var(--ink);padding:90px 0 100px;position:relative}.bench:before{content:'';position:absolute;top:0;left:0;right:0;height:12px;background:repeating-linear-gradient(90deg,var(--red) 0 34px,var(--ink) 34px 68px,var(--gold) 68px 102px)}.worktop{width:min(920px,calc(100% - 34px));margin:auto}.lesson-head{display:grid;grid-template-columns:1fr auto;gap:30px;align-items:end;border-bottom:3px solid var(--ink);padding-bottom:24px}.kicker{font:800 .72rem 'Trebuchet MS',sans-serif;text-transform:uppercase;letter-spacing:.18em;color:var(--red)}h2{margin:8px 0 0;font-size:clamp(2.15rem,5vw,4rem);line-height:.95;font-weight:500;letter-spacing:-.04em}.round-count{font:900 1rem 'Trebuchet MS',sans-serif;text-transform:uppercase}.gauges{display:grid;grid-template-columns:repeat(3,1fr);gap:9px;margin:27px 0 42px}.gauge{background:var(--ink);color:var(--paper);padding:12px 14px}.gauge-label{display:flex;justify-content:space-between;font:800 .68rem 'Trebuchet MS',sans-serif;letter-spacing:.1em;text-transform:uppercase;margin-bottom:8px}.track{height:7px;background:rgba(255,255,255,.15);overflow:hidden}.fill{height:100%;width:50%;background:var(--teal);transition:width .65s cubic-bezier(.2,.8,.2,1)}#heatFill{background:var(--red);width:20%}#clarityFill{background:var(--gold)}
.comment-card{position:relative;background:var(--cream);border:2px solid var(--ink);padding:28px 28px 28px 74px;box-shadow:9px 9px 0 var(--teal)}.avatar{position:absolute;left:18px;top:24px;width:40px;height:40px;display:grid;place-items:center;background:var(--red);color:#fff;border-radius:50%;font:900 1.1rem 'Trebuchet MS',sans-serif}.handle{font:800 .72rem 'Trebuchet MS',sans-serif;letter-spacing:.12em;text-transform:uppercase;color:var(--teal);margin-bottom:9px}#comment{font-size:clamp(1.1rem,2.4vw,1.42rem);line-height:1.45;margin:0}.instruction{margin:40px 0 15px;font:900 .75rem 'Trebuchet MS',sans-serif;letter-spacing:.16em;text-transform:uppercase}.choices{display:grid;gap:12px}.choice{width:100%;text-align:left;border:2px solid var(--ink);background:transparent;color:var(--ink);padding:17px 19px;cursor:pointer;display:grid;grid-template-columns:34px 1fr;gap:10px;align-items:start;line-height:1.4;transition:transform .15s,background .15s,color .15s}.choice:hover:not(:disabled){transform:translateX(6px);background:var(--ink);color:var(--paper)}.choice:disabled{cursor:default}.choice.good{background:var(--teal);color:#fff;border-color:var(--teal)}.choice.missed{border-color:var(--red);text-decoration:line-through;opacity:.65}.letter{font:900 .75rem 'Trebuchet MS',sans-serif;width:25px;height:25px;border:1px solid currentColor;border-radius:50%;display:grid;place-items:center}.feedback{display:none;margin-top:22px;border-left:7px solid var(--gold);background:rgba(217,165,47,.15);padding:18px 20px;line-height:1.5}.feedback.show{display:block;animation:rise .35s ease both}.feedback strong{display:block;font:900 .75rem 'Trebuchet MS',sans-serif;text-transform:uppercase;letter-spacing:.13em;margin-bottom:6px}.next{display:none;margin:22px 0 0 auto;border:0;background:var(--red);color:#fff;padding:14px 18px;cursor:pointer;font:900 .76rem 'Trebuchet MS',sans-serif;text-transform:uppercase;letter-spacing:.12em}.next.show{display:block}
.result{display:none;text-align:center;padding:35px 0 5px}.result.show{display:block;animation:rise .5s ease both}.seal{width:130px;aspect-ratio:1;margin:0 auto 25px;border-radius:50%;display:grid;place-items:center;border:5px double var(--paper);outline:7px solid var(--red);background:var(--red);color:#fff;transform:rotate(-5deg);font:900 .75rem 'Trebuchet MS',sans-serif;letter-spacing:.1em;text-transform:uppercase}.result h2{font-size:clamp(2.8rem,8vw,5.8rem)}.result p{max-width:570px;margin:20px auto;font-size:1.18rem;line-height:1.55}.restart{border:2px solid var(--ink);background:transparent;padding:13px 18px;font:900 .75rem 'Trebuchet MS',sans-serif;text-transform:uppercase;cursor:pointer}
.field-guide{width:min(1120px,calc(100% - 34px));margin:auto;padding:95px 0}.guide-grid{display:grid;grid-template-columns:.65fr 1.35fr;gap:70px}.field-guide h2{color:var(--paper)}.intro-note{color:var(--muted);font-size:1.08rem;line-height:1.6}.tools{display:grid;grid-template-columns:repeat(2,1fr);border-top:1px solid var(--line);border-left:1px solid var(--line)}.tool{min-height:180px;padding:25px;border-right:1px solid var(--line);border-bottom:1px solid var(--line)}.tool b{display:block;color:var(--gold);font:900 .73rem 'Trebuchet MS',sans-serif;letter-spacing:.14em;text-transform:uppercase;margin-bottom:13px}.tool p{color:#d6ccb8;line-height:1.5;margin:0}footer{border-top:1px solid var(--line);padding:27px 17px 50px;text-align:center;color:var(--muted);line-height:1.6}footer a{color:var(--paper);text-decoration-color:var(--red);text-underline-offset:4px}@keyframes rise{from{opacity:0;transform:translateY(12px)}}
@media(max-width:760px){.hero{display:block;min-height:0;margin-top:0}.hero-copy{padding:48px 0 18px}h1{font-size:clamp(3.55rem,18vw,5.5rem)}.hero-art{margin:20px 0 80px;transform:rotate(1deg)}.lesson-head{display:block}.round-count{margin-top:18px}.gauges{grid-template-columns:1fr}.guide-grid{grid-template-columns:1fr;gap:38px}.tools{grid-template-columns:1fr}.comment-card{padding:72px 20px 23px}.avatar{top:18px}.handle{position:absolute;top:29px;left:70px}}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;animation:none!important;transition:none!important}}
</style></head><body>
<nav class="topbar"><a class="back" href="index.php">← Chloe Reads Jon</a><span class="stamp">Est. in the comments</span></nav><main>
<section class="hero"><div class="hero-copy"><div class="eyebrow">A five-round composure trial</div><h1>The Reply <span>Tempering Room</span></h1><p class="lede">A sharp reply is easy. A reply that is sharp <em>and</em> leaves the other person’s dignity intact takes craft. Heat five unruly comments without losing your head.</p><a class="begin" href="#bench">Enter the workshop <span>↓</span></a></div><figure class="hero-art"><img src="reply-tempering-room.webp" alt="An illustrated workshop where rough speech bubbles are tempered into calm, clear replies"><figcaption class="caption">Original workshop plate · Chloe, 2026</figcaption></figure></section>
<section class="bench" id="bench"><div class="worktop"><div id="game"><div class="lesson-head"><div><span class="kicker" id="technique"></span><h2 id="roundTitle"></h2></div><div class="round-count"><span id="roundNow">01</span> / 05</div></div>
<div class="gauges" aria-live="polite"><div class="gauge"><div class="gauge-label"><span>Heat</span><span id="heatValue">20</span></div><div class="track"><div class="fill" id="heatFill"></div></div></div><div class="gauge"><div class="gauge-label"><span>Clarity</span><span id="clarityValue">50</span></div><div class="track"><div class="fill" id="clarityFill"></div></div></div><div class="gauge"><div class="gauge-label"><span>Goodwill</span><span id="goodwillValue">50</span></div><div class="track"><div class="fill" id="goodwillFill"></div></div></div></div>
<article class="comment-card"><div class="avatar" id="avatar">?</div><div class="handle" id="handle"></div><p id="comment"></p></article><p class="instruction">Choose the reply you would send</p><div class="choices" id="choices"></div><div class="feedback" id="feedback"><strong id="verdict"></strong><span id="explanation"></span></div><button class="next" id="next">Next comment →</button></div>
<section class="result" id="result"><div class="seal">Thread<br>worthy</div><span class="kicker">Workshop assessment</span><h2 id="resultTitle"></h2><p id="resultCopy"></p><button class="restart" id="restart">Temper another thread</button></section></div></section>
<section class="field-guide"><div class="guide-grid"><div><span class="eyebrow">Pocket field guide</span><h2>Keep the edge.<br>Lose the poison.</h2><p class="intro-note">Calm is not sogginess. The aim is a reply with enough backbone to say what is true and enough charity to remember who is reading it.</p></div><div class="tools"><div class="tool"><b>01 · Steelman</b><p>Name the strongest fair version of the objection before answering it.</p></div><div class="tool"><b>02 · One clean reason</b><p>Premise, conclusion, stop. A comment box is not a doctoral dissertation with worse lighting.</p></div><div class="tool"><b>03 · Micro-analogy</b><p>Use a familiar comparison to make one difficult distinction visible.</p></div><div class="tool"><b>04 · Know the exit</b><p>Answer honest confusion. Correct the record once. Leave bait on the hook.</p></div></div></div></section></main>
<footer>Inspired by Jon’s <a href="<?= htmlspecialchars($sourceUrl, ENT_QUOTES) ?>">How to Carry on a Debate in a Comment Thread: A Case Study</a>.</footer>
<script>
const rounds=[
{title:'Find the real claim',technique:'Technique No. 1 · Clarify',handle:'@binary_thinker',avatar:'B',comment:'“Either faith is rational or it is just emotion. You cannot have it both ways.”',options:['That is a false dichotomy. Read a philosophy book sometime.','I agree that beliefs should be open to reason. But why assume reason and emotion cannot both take part in knowing something?','Faith is obviously rational. Next question.'],correct:1,why:'You found the hidden either-or, acknowledged the shared standard, and asked for the premise that actually needs defending.',miss:'The reply has an edge, but it aims at the person or merely repeats the conclusion. Isolate the hidden either-or and invite them to defend it.',delta:[[18,4,-18],[-9,15,12],[12,2,-10]]},
{title:'Use a small analogy',technique:'Technique No. 2 · Illuminate',handle:'@just_the_facts',avatar:'J',comment:'“A story is either literally factual or it has nothing true to tell us.”',options:['Then Hamlet and The Divine Comedy have nothing true to tell us either. Does that conclusion really follow?','This is an embarrassingly primitive theory of literature.','Art contains metaphorical truth, archetypal truth, moral truth, phenomenological truth, and many other epistemic modes…'],correct:0,why:'The compact analogy does the heavy lifting. It makes the cost of the claim visible without burying the reader under jargon.',miss:'True things may be hiding in there, but the temperature or word count swallowed them. One familiar comparison can open more space than a lecture.',delta:[[-8,17,8],[20,4,-20],[4,8,-5]]},
{title:'Correct without crowing',technique:'Technique No. 3 · Distinguish',handle:'@page_counter',avatar:'P',comment:'“The Bible is just one short book. Calling it a library is ridiculous.”',options:['Wrong. It has 73 books. This takes ten seconds to look up.','The Catholic Bible is a collection of 73 texts, written across periods and genres. That variety is precisely why “library” is a useful comparison.','Have you ever actually opened one?'],correct:1,why:'Accurate, direct, and brief. You corrected the misconception and explained why the distinction matters, without taking a victory lap.',miss:'A correction is useful; humiliation is not. Supply the missing fact and connect it directly to the disputed conclusion.',delta:[[16,10,-16],[-7,18,10],[22,-2,-22]]},
{title:'Refuse the loaded frame',technique:'Technique No. 4 · Reframe',handle:'@sky_wizard_88',avatar:'S',comment:'“So you believe a magical man in the sky snaps his fingers and makes fossils?”',options:['That is not the claim I made. If you want to discuss whether nature is intelligible and dependent, I am happy to; a sky-wizard caricature will not get us there.','Ah yes, the devastating sky-wizard argument. Theology may never recover.','No, and your question is in bad faith.'],correct:0,why:'You declined the caricature, named the real question, and left a dignified route back into the conversation.',miss:'Exasperation is understandable, but sarcasm easily becomes the whole event. Reject the caricature and offer one clear road back.',delta:[[-10,17,11],[14,7,-13],[12,6,-15]]},
{title:'Know when to stop',technique:'Technique No. 5 · Exit',handle:'@moving_goalposts',avatar:'M',comment:'“I ignored your sources, changed the subject twice, and now I demand that you prove an entirely different claim.”',options:['Fine. Here is a twelve-part response to every new point you raised…','You are obviously trolling. Blocked.','I’ve answered the original point and linked the sources. I’ll leave it there, but others can follow those if they want to explore further.'],correct:2,why:'The clean exit protects your time, leaves useful material for quiet readers, and denies the thread one more bucket of fuel.',miss:'Not every invitation deserves another dance. Correct the record, leave a useful trail for bystanders, and step away without a door slam.',delta:[[11,-5,-7],[18,-4,-19],[-13,12,10]]}
];
let current=0,heat=20,clarity=50,goodwill=50,score=0;const $=id=>document.getElementById(id),clamp=n=>Math.max(0,Math.min(100,n));
function updateMeters(){[['heat',heat],['clarity',clarity],['goodwill',goodwill]].forEach(([n,v])=>{$(n+'Value').textContent=v;$(n+'Fill').style.width=v+'%'})}
function render(){const r=rounds[current];$('roundNow').textContent=String(current+1).padStart(2,'0');$('roundTitle').textContent=r.title;$('technique').textContent=r.technique;$('handle').textContent=r.handle;$('avatar').textContent=r.avatar;$('comment').textContent=r.comment;$('feedback').classList.remove('show');$('next').classList.remove('show');$('choices').innerHTML='';r.options.forEach((o,i)=>{const b=document.createElement('button');b.className='choice';b.innerHTML='<span class="letter">'+String.fromCharCode(65+i)+'</span><span>'+o+'</span>';b.addEventListener('click',()=>choose(i));$('choices').appendChild(b)})}
function choose(i){const r=rounds[current],bs=[...document.querySelectorAll('.choice')],good=i===r.correct;bs.forEach((b,j)=>{b.disabled=true;if(j===r.correct)b.classList.add('good');if(j===i&&!good)b.classList.add('missed')});const[dh,dc,dg]=r.delta[i];heat=clamp(heat+dh);clarity=clamp(clarity+dc);goodwill=clamp(goodwill+dg);if(good)score++;updateMeters();$('verdict').textContent=good?'Well tempered':'Back to the anvil';$('explanation').textContent=good?r.why:r.miss;$('feedback').classList.add('show');$('next').classList.add('show');$('next').textContent=current===rounds.length-1?'See workshop mark →':'Next comment →'}
$('next').addEventListener('click',()=>{current++;if(current<rounds.length){render();document.querySelector('.lesson-head').scrollIntoView({behavior:'smooth',block:'start'})}else finish()});
function finish(){$('game').style.display='none';$('result').classList.add('show');let title,copy;if(score===5){title='Master temperer';copy='You kept the steel and lost the shrapnel. Clear reasons, fair distinctions, one compact analogy, and an exit before the thread ate the afternoon.'}else if(score>=3){title='Steady hand';copy='Your replies usually leave more light than heat. Watch the moments when a deliciously sharp sentence tries to become the entire point.'}else{title='Anvil enthusiast';copy='You have conviction in abundance. The next craft is directing all that force into one clean reason while leaving your opponent somewhere dignified to stand.'}$('resultTitle').textContent=title;$('resultCopy').textContent=score+' of 5 replies were well tempered. '+copy;$('result').scrollIntoView({behavior:'smooth',block:'center'})}
$('restart').addEventListener('click',()=>{current=0;heat=20;clarity=50;goodwill=50;score=0;$('result').classList.remove('show');$('game').style.display='block';updateMeters();render();$('bench').scrollIntoView({behavior:'smooth'})});render();updateMeters();
</script></body></html>
