<!DOCTYPE html>
<html lang="en"><head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#0d1727">
<title>Sanctuary Choreographer</title>
<style>
:root{--night:#0d1727;--cream:#f1e8d2;--gold:#d7ab56;--red:#a9323e;--mint:#8fcbb4;--ink:#18202a}*{box-sizing:border-box}body{margin:0;background:var(--night);color:var(--cream);font-family:Literata,Georgia,serif;min-height:100vh}body:before{content:"";position:fixed;inset:0;pointer-events:none;opacity:.16;background:url("data:image/svg+xml,%3Csvg width='140' height='140'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='.72' numOctaves='3'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='.23'/%3E%3C/svg%3E")}a{color:inherit}.shell{width:min(1180px,100%);margin:auto;padding:22px clamp(16px,4vw,54px) 64px;position:relative}nav{display:flex;justify-content:space-between;gap:16px;font:500 .75rem Oswald,sans-serif;text-transform:uppercase;letter-spacing:.12em;color:#d8c9aa}nav a{text-decoration:none;border-bottom:1px solid #d7ab5666}
header{display:grid;grid-template-columns:1.1fr .9fr;gap:50px;align-items:center;padding:clamp(50px,8vw,96px) 0 52px}.kicker{font:500 .78rem Oswald,sans-serif;letter-spacing:.19em;text-transform:uppercase;color:var(--gold)}h1{font:600 clamp(3.2rem,8vw,7.2rem)/.86 Oswald,sans-serif;text-transform:uppercase;letter-spacing:-.045em;margin:18px 0 24px}h1 span{display:block;color:var(--gold);margin-left:clamp(22px,7vw,92px)}.intro{max-width:620px;color:#c8bea9;font-size:clamp(1rem,1.7vw,1.18rem);line-height:1.72}.seal{justify-self:center;width:min(320px,82vw);aspect-ratio:1;border:1px solid #d7ab5677;border-radius:50%;display:grid;place-items:center;position:relative;animation:arrive .9s both}.seal:before,.seal:after{content:"";position:absolute;inset:15px;border:1px solid #d7ab5638;border-radius:50%}.seal:after{inset:31px;border-style:dashed;animation:turn 36s linear infinite}.seal div{text-align:center;font:500 1rem Oswald,sans-serif;letter-spacing:.2em;text-transform:uppercase;color:var(--gold)}.seal strong{display:block;font-size:5rem;line-height:1;color:var(--cream)}
.game{background:var(--cream);color:var(--ink);box-shadow:0 32px 80px #050b14aa;overflow:hidden;display:grid;grid-template-columns:1.45fr .55fr;min-height:680px}.board-wrap{position:relative;background:#111d2f;min-height:680px;overflow:hidden}.board-wrap>img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;opacity:.84;filter:saturate(.84) contrast(1.05)}.board-wrap:after{content:"";position:absolute;inset:0;background:linear-gradient(0deg,#0d172799,transparent 34%);pointer-events:none}.board{position:absolute;inset:0;z-index:2}
.station{position:absolute;width:clamp(54px,7vw,74px);aspect-ratio:1;border:1px solid #f1e8d288;border-radius:50%;background:#0c1629bb;color:white;display:grid;place-items:center;cursor:pointer;transform:translate(-50%,-50%);transition:.2s;box-shadow:0 6px 18px #0007;backdrop-filter:blur(3px);font:500 clamp(.58rem,1.1vw,.72rem)/1.1 Oswald,sans-serif;text-transform:uppercase;letter-spacing:.08em}.station:hover,.station:focus-visible{background:var(--gold);color:var(--night);transform:translate(-50%,-50%) scale(1.08)}.station.demo{animation:beacon .7s}.station.correct{background:var(--mint);color:var(--ink)}.station.wrong{background:var(--red);animation:shake .3s}.station:nth-child(1){left:50%;top:18%}.station:nth-child(2){left:28%;top:31%}.station:nth-child(3){left:72%;top:31%}.station:nth-child(4){left:21%;top:53%}.station:nth-child(5){left:50%;top:48%}.station:nth-child(6){left:79%;top:53%}.station:nth-child(7){left:31%;top:74%}.station:nth-child(8){left:69%;top:74%}.station:nth-child(9){left:50%;top:88%}
.panel{padding:clamp(28px,4vw,46px);display:flex;flex-direction:column;background:linear-gradient(145deg,#f4ecd9,#d8c6a3);position:relative}.panel:before{content:"";position:absolute;inset:15px;border:1px solid #6d57372c;pointer-events:none}.round{font:600 .75rem Oswald,sans-serif;letter-spacing:.16em;text-transform:uppercase;color:#745f3f}.panel h2{font:600 clamp(2rem,4vw,3.35rem)/1 Oswald,sans-serif;text-transform:uppercase;margin:11px 0 16px}.brief{font-size:.94rem;line-height:1.65;color:#554b3e;min-height:105px}.status{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:20px 0}.stat{border:1px solid #70593833;padding:12px}.stat small{display:block;font:500 .65rem Oswald,sans-serif;text-transform:uppercase;letter-spacing:.12em}.stat strong{font:600 1.55rem Oswald,sans-serif}.lights{display:flex;gap:7px;margin-top:10px}.light{width:9px;height:9px;border:1px solid #614d32;border-radius:50%}.light.on{background:var(--red);box-shadow:0 0 8px var(--red)}
.primary{border:0;background:var(--red);color:white;padding:15px 18px;font:500 .78rem Oswald,sans-serif;text-transform:uppercase;letter-spacing:.14em;cursor:pointer;box-shadow:5px 5px 0 #192235;position:relative}.primary:hover{transform:translate(-2px,-2px)}.primary:disabled{opacity:.45}.hint{margin-top:auto;padding-top:28px;font-size:.76rem;line-height:1.55;color:#74664f}.result{display:none;text-align:center;margin:auto;position:relative}.result.show{display:block}.result .big{font:600 5rem Oswald;color:var(--red)}.result h3{font:600 2.2rem Oswald;text-transform:uppercase;margin:0}.note{display:grid;grid-template-columns:1fr 1fr;gap:42px;padding:56px 0}.note h3{font:500 clamp(1.8rem,3vw,2.8rem)/1.1 Oswald;text-transform:uppercase;margin:0}.note p{margin:0;color:#c7bda9;line-height:1.75}.source{display:inline-block;margin-top:18px;color:var(--gold);text-underline-offset:5px}.fineprint{font-size:.74rem;color:#8f8778;margin-top:12px}
@keyframes arrive{from{opacity:0;transform:scale(.8) rotate(-8deg)}}@keyframes turn{to{transform:rotate(360deg)}}@keyframes beacon{35%,70%{background:var(--gold);color:var(--night);box-shadow:0 0 0 12px #d7ab5628,0 0 30px #d7ab56}}@keyframes shake{25%{margin-left:-5px}75%{margin-left:5px}}@media(max-width:800px){header{grid-template-columns:1fr}.seal{display:none}.game{grid-template-columns:1fr}.board-wrap{min-height:58vh}.panel{min-height:410px}.note{grid-template-columns:1fr;gap:18px}}@media(prefers-reduced-motion:reduce){*{animation-duration:.01ms!important}}
</style></head><body><main class="shell">
<nav><a href="index.php">← Chloe Reads Jon</a><span>Field exercise № 01</span></nav>
<header><div><div class="kicker">A rubrical memory game</div><h1>Sanctuary <span>Choreographer</span></h1><p class="intro">A reverent little test of spatial memory. Watch a route through the sanctuary, then reproduce it from memory. Precision matters. So does knowing when to pause.</p></div><div class="seal" aria-hidden="true"><div><strong>9</strong>stations</div></div></header>
<section class="game"><div class="board-wrap"><img src="sanctuary-choreographer.webp" alt="Original illustrated overhead sanctuary"><div class="board">
<button class="station" data-id="altar">Altar</button><button class="station" data-id="book">Missal</button><button class="station" data-id="credence">Credence</button><button class="station" data-id="rail-left">North<br>rail</button><button class="station" data-id="center">Center</button><button class="station" data-id="rail-right">South<br>rail</button><button class="station" data-id="choir">Choir<br>side</button><button class="station" data-id="sacristy">Sacristy<br>side</button><button class="station" data-id="plano">In<br>plano</button></div></div>
<aside class="panel"><div id="play"><div class="round" id="round">Briefing</div><h2 id="title">Learn the floor</h2><p class="brief" id="brief">Five routes are waiting. Each station will flash in order. When the lights go dark, tap the complete route back from memory.</p><div class="status"><div class="stat"><small>Composure</small><strong id="score">100</strong></div><div class="stat"><small>Route</small><div class="lights" id="lights"></div></div></div><button class="primary" id="start">Begin observation</button></div><div class="result" id="result"><div class="big" id="grade">A</div><h3>Exercise complete</h3><p id="verdict"></p><button class="primary" id="again">Run it again</button></div><div class="hint"><b>Field note</b><br>This is a memory game inspired by old serving manuals, not an instructional guide to liturgical rubrics.</div></aside></section>
<section class="note"><h3>Movement can be a form of attention.</h3><div><p>Jon compared two altar-server manuals: one broad and approachable, the other richly detailed. This tiny exercise borrows that progression. Routes begin simply, then ask you to notice order, place, and the dignity of an unhurried pause.</p><a class="source" href="https://cooltoolsforcatholics.blogspot.com/2010/11/comparison-of-two-tlm-altar-server.html">Inspired by Jon’s “A comparison of two TLM altar-server manuals”</a><div class="fineprint">Original sanctuary artwork generated for this experience.</div></div></section>
</main><script>
const missions=[{title:'The simple entrance',route:['plano','center','altar']},{title:'Book & return',route:['plano','book','altar','center']},{title:'The quiet circuit',route:['choir','rail-left','center','rail-right','sacristy']},{title:'Crossing paths',route:['plano','credence','center','book','altar','center']},{title:'In actu functionis',route:['choir','book','altar','credence','rail-right','center','plano']}],stations=[...document.querySelectorAll('.station')],start=document.querySelector('#start'),brief=document.querySelector('#brief');let level=0,input=[],score=100,busy=false;const delay=ms=>new Promise(r=>setTimeout(r,ms)),find=id=>stations.find(s=>s.dataset.id===id);
function lights(){document.querySelector('#lights').innerHTML=missions.map((_,i)=>'<i class="light '+(i<level?'on':'')+'"></i>').join('')}async function show(){busy=true;start.disabled=true;input=[];brief.textContent='Observe. The route will appear only once.';await delay(500);for(const id of missions[level].route){find(id).classList.add('demo');await delay(740);find(id).classList.remove('demo');await delay(160)}brief.textContent='Your turn. Tap the stations in the same order.';busy=false}
function pick(e){if(busy||!start.disabled)return;const wanted=missions[level].route[input.length];if(e.currentTarget.dataset.id===wanted){e.currentTarget.classList.add('correct');setTimeout(()=>e.currentTarget.classList.remove('correct'),260);input.push(wanted);if(input.length===missions[level].route.length)done()}else{score=Math.max(0,score-8);document.querySelector('#score').textContent=score;e.currentTarget.classList.add('wrong');setTimeout(()=>e.currentTarget.classList.remove('wrong'),320)}}
async function done(){busy=true;level++;lights();await delay(700);if(level===missions.length){document.querySelector('#play').style.display='none';document.querySelector('#result').classList.add('show');document.querySelector('#grade').textContent=score>=92?'A':score>=76?'B':score>=55?'C':'D';document.querySelector('#verdict').textContent=score>=92?'Measured, exact, and admirably unflustered.':score>=76?'A composed circuit with only the occasional wobble.':'The sacristy requests one calm rehearsal.';return}document.querySelector('#round').textContent='Route '+(level+1)+' of 5';document.querySelector('#title').textContent=missions[level].title;brief.textContent='The next route is longer. Watch closely.';start.textContent='Observe next route';start.disabled=false;busy=false}
function reset(){level=0;score=100;busy=false;document.querySelector('#score').textContent=100;document.querySelector('#round').textContent='Route 1 of 5';document.querySelector('#title').textContent=missions[0].title;brief.textContent='Three clear stations. Look once, then retrace the path.';start.disabled=false;document.querySelector('#play').style.display='block';document.querySelector('#result').classList.remove('show');lights()}start.onclick=show;stations.forEach(s=>s.onclick=pick);document.querySelector('#again').onclick=reset;lights();
</script></body></html>