<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#170d09"><title>Setlist Signal Deck</title>
<style>
@import url('https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=Rye&family=Special+Elite&display=swap');
:root{--cream:#f2dfb5;--amber:#ffb431;--red:#dc4b34;--paper:#e3c98d}*{box-sizing:border-box}body{margin:0;color:var(--cream);font-family:"DM Mono",monospace;background:#100907 radial-gradient(circle at 50% -20%,#5b2e1d,transparent 43%)}body:before{content:"";position:fixed;inset:0;z-index:20;pointer-events:none;opacity:.1;background:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence baseFrequency='.8' numOctaves='3'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E")}a{color:inherit}.wrap{width:min(1120px,calc(100% - 28px));margin:auto}.top{display:flex;justify-content:space-between;padding:18px 0;color:#c9ad86;font-size:10px;letter-spacing:.13em;text-transform:uppercase}.top a{text-decoration:none;border-bottom:1px solid #87664b}.live i{display:inline-block;width:8px;height:8px;margin-right:8px;border-radius:50%;background:var(--red);box-shadow:0 0 14px var(--red);animation:pulse 1.6s infinite}@keyframes pulse{50%{opacity:.3}}
.hero{position:relative;min-height:410px;overflow:hidden;border:1px solid #604335;border-radius:7px 7px 22px 22px;background:#21120e url('setlist-signal-deck-hero.webp') center/cover;box-shadow:0 32px 80px #0009,inset 0 0 0 7px #160d0a}.hero:after{content:"";position:absolute;inset:0;background:linear-gradient(90deg,#120907f2,#160c09d4 43%,#160c0940 75%)}.hero div{position:relative;z-index:2;padding:62px 7%;max-width:700px}.kicker{display:inline-block;padding:8px 13px;color:#2c1911;background:var(--paper);transform:rotate(-1deg);box-shadow:2px 3px #140b08;font:12px "Special Elite";letter-spacing:.16em}.hero h1{margin:28px 0 22px;color:#f9e8bd;text-shadow:4px 5px #351711;font:clamp(46px,8vw,92px)/.87 "Rye"}.hero p{max-width:530px;color:#e2cba6;font-size:14px;line-height:1.7}.hero strong{color:var(--amber)}
.case{margin:34px 0 60px;padding:12px;border:2px solid #76624e;border-radius:12px;background:linear-gradient(135deg,#321c16,#1e110e);box-shadow:0 30px 70px #0008}.panel{padding:clamp(20px,4vw,42px);background:#211713;border:1px solid #080504;box-shadow:inset 0 0 55px #0008}.head{display:grid;grid-template-columns:1fr auto;gap:24px;align-items:end;padding-bottom:24px;border-bottom:1px dashed #665044}.eyebrow{color:var(--amber);font-size:10px;letter-spacing:.2em}.song{width:min(100%,560px);padding:8px 0 2px;color:var(--cream);background:none;border:0;border-bottom:2px solid #745343;outline:0;font:clamp(25px,5vw,48px) "Special Elite"}.tempo{min-width:120px;padding:12px;text-align:center;background:#0d0b0a;border:1px solid #665747}.bpm{color:var(--amber);font-size:30px}.tempo small{display:block;color:#aa9576;font-size:8px}.tap{width:100%;margin-top:8px;padding:6px;color:#ead4aa;background:#453328;border:1px solid #76604c;cursor:pointer}
.labels{display:flex;justify-content:space-between;align-items:center;margin:30px 0 12px}.labels h2{margin:0;font:20px "Special Elite"}.labels span{color:#8f7b66;font-size:9px}.timeline{display:flex;gap:10px;overflow:auto;padding:7px 3px 18px}.section{position:relative;flex:1 0 120px;max-width:180px;min-height:148px;padding:17px 12px;color:#25150e;background:#dcc080;clip-path:polygon(2% 2%,98% 0,100% 95%,94% 100%,3% 97%,0 8%);cursor:pointer;transition:.2s;filter:drop-shadow(3px 5px 0 #0008)}.section:nth-child(even){transform:rotate(.7deg);background:#e8d6aa}.section:hover{transform:translateY(-4px)}.section.active{background:#ffd366}.section h3{margin:12px 0 8px;font:20px "Special Elite"}.section p,.num,.bars{color:#634c32;font-size:9px}.bars{position:absolute;bottom:11px;letter-spacing:.15em}.del{position:absolute;right:8px;top:7px;border:0;background:none;color:#694932;cursor:pointer}
.transport{display:grid;grid-template-columns:auto 1fr auto;gap:18px;align-items:center;margin-top:18px}.play{width:70px;height:70px;color:#fff;background:#c9442b;border:6px solid #49362a;border-radius:50%;box-shadow:0 5px #080504;cursor:pointer;font-size:20px}.play.playing{background:#6d9859}.scrub{height:12px;background:#0b0807;border:1px solid #5b493c}.scrub span{display:block;width:0;height:100%;background:linear-gradient(90deg,#c73528,var(--amber));box-shadow:0 0 16px #ff9c29}.clock{min-width:58px;color:#bda988}.controls{display:grid;grid-template-columns:1fr 1fr;gap:22px;margin-top:34px}.module{padding-top:18px;border-top:1px solid #62493c}.module h3{margin:0 0 14px;font:17px "Special Elite"}.buttons{display:flex;flex-wrap:wrap;gap:8px}.cue,.add{padding:10px 12px;color:#d8c39c;background:#37271f;border:1px solid #6f5a47;cursor:pointer;font:10px "DM Mono";text-transform:uppercase}.cue.selected{color:#25140d;background:var(--paper)}.add{color:#bcd09f;background:#182118}.hint{color:#887564;font-size:9px;line-height:1.6}.meter{display:flex;align-items:end;gap:3px;height:62px;padding:8px;background:#0c0908}.meter i{flex:1;height:var(--h);background:#725837}.playing .meter i{animation:meter .65s infinite alternate;animation-delay:var(--d)}@keyframes meter{to{height:calc(var(--h) + 30%)}}.note{margin-top:28px;padding:18px 20px;color:#332015;background:#d8c48d;transform:rotate(-.4deg);box-shadow:4px 5px #0e0807;font:14px/1.6 "Special Elite"}.note b{color:#9e2f20}.source{padding:0 15px 55px;text-align:center;color:#9a816c;font-size:11px;line-height:1.8}.source a{color:#e7c788}.toast{position:fixed;z-index:50;bottom:25px;left:50%;padding:12px 18px;color:#29160e;background:#f1ddb0;box-shadow:5px 5px #000;transform:translate(-50%,120px);transition:.35s}.toast.show{transform:translate(-50%,0)}
@media(max-width:690px){.hero{min-height:480px;background-position:62%}.hero div{padding:55px 26px}.hero h1{font-size:50px}.head,.controls{grid-template-columns:1fr}.panel{padding:30px 17px}.play{width:58px;height:58px}}@media(prefers-reduced-motion:reduce){*{animation:none!important}}
</style></head><body><div class="wrap">
<nav class="top"><a href="index.php">← Chloe Reads Jon</a><span class="live"><i></i>rehearsal line open</span></nav>
<header class="hero"><div><span class="kicker">FIELD UNIT NO. 531</span><h1>Setlist<br>Signal Deck</h1><p>Turn cryptic scraps like <strong>“v3: guitar”</strong> and <strong>“fast continuous strum”</strong> into a rehearsal map you can actually play through.</p></div></header>
<main class="case"><div class="panel" id="panel"><div class="head"><div><span class="eyebrow">NOW CHARTING / EDIT THE TITLE</span><input class="song" id="song" value="CITY IN E♭"></div><div class="tempo"><span class="bpm" id="bpm">96</span><small>BEATS / MINUTE</small><button class="tap" id="tap">TAP TEMPO</button></div></div>
<div class="labels"><h2>Arrangement tape</h2><span>TAP A CARD TO CUE IT</span></div><div class="timeline" id="timeline"></div>
<div class="transport"><button class="play" id="play">▶</button><div class="scrub"><span id="progress"></span></div><div class="clock" id="clock">0:00</div></div>
<div class="controls"><section class="module"><h3>Stamp a performance cue</h3><div class="buttons" id="cues"><button class="cue selected" data-cue="single strum">single strum</button><button class="cue" data-cue="quarter strums">quarter strums</button><button class="cue" data-cue="syncopated">syncopated</button><button class="cue" data-cue="guitar enters">guitar enters</button><button class="cue" data-cue="drop last bar">drop last bar</button><button class="cue" data-cue="build intensity">build</button></div><p class="hint">Choose a stamp, then tap an arrangement card. Your map stays in this browser.</p></section><section class="module"><h3>Add another section</h3><div class="buttons"><button class="add" data-add="VERSE">+ verse</button><button class="add" data-add="REFRAIN">+ refrain</button><button class="add" data-add="BRIDGE">+ bridge</button><button class="add" data-add="SOLO">+ solo</button></div><p class="hint">During playback, every card gets eight beats. The bright click marks the downbeat.</p></section></div>
<div class="module" style="margin-top:28px"><h3>Signal level</h3><div class="meter"><?php for($i=0;$i<24;$i++){echo '<i style="--h:'.(12+(($i*17)%48)).'%;--d:'.(($i%7)*-.08).'s"></i>';} ?></div></div>
<div class="note"><b>ORIGINAL SCRAP, DECODED:</b> “each verse: single strum → quarter strums → syncopated. Guitar on verse three. Fast continuous strum on refrain. City in E♭. Drop last bar of refrain.”</div></div></main>
<footer class="source">Built from the kind of shorthand only its author can read six months later.<br>Inspired by Jon’s <a href="https://jona.ca/2004/09/awake-guit-ps-2-eighth-notes-247-531.html" target="_blank" rel="noopener">untitled guitar rehearsal notes</a>.</footer></div><div class="toast" id="toast"></div>
<script>
const D=[{name:'COUNT IN',cue:'two eighth notes',bars:2},{name:'VERSE 1',cue:'single strum',bars:8},{name:'VERSE 2',cue:'quarter strums',bars:8},{name:'REFRAIN',cue:'fast continuous strum',bars:8},{name:'VERSE 3',cue:'guitar enters',bars:8},{name:'REFRAIN',cue:'drop last bar',bars:7}];let S;try{S=JSON.parse(localStorage.deck)||D}catch(e){S=D}let cue='single strum',playing=false,timer,beat=0,bpm=96,taps=[],audio;const q=s=>document.querySelector(s),line=q('#timeline'),play=q('#play'),prog=q('#progress'),clock=q('#clock'),panel=q('#panel');function esc(s){let d=document.createElement('div');d.textContent=s;return d.innerHTML}function save(){localStorage.deck=JSON.stringify(S);localStorage.deckTitle=q('#song').value}function render(a=-1){line.innerHTML=S.map((s,i)=>`<article class="section ${i==a?'active':''}" data-i="${i}"><button class="del" data-del="${i}">×</button><span class="num">${String(i+1).padStart(2,'0')}</span><h3>${esc(s.name)}</h3><p>${esc(s.cue)}</p><span class="bars">${s.bars} BARS</span></article>`).join('')}function flash(x){let t=q('.toast');t.textContent=x;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1200)}
line.onclick=e=>{let d=e.target.closest('[data-del]');if(d){e.stopPropagation();S.splice(+d.dataset.del,1);save();render();return}let c=e.target.closest('.section');if(c){S[+c.dataset.i].cue=cue;save();render(+c.dataset.i);flash('Stamped: '+cue)}};q('#cues').onclick=e=>{if(e.target.dataset.cue){cue=e.target.dataset.cue;document.querySelectorAll('.cue').forEach(b=>b.classList.toggle('selected',b==e.target))}};document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{S.push({name:b.dataset.add,cue:'open arrangement',bars:8});save();render();line.scrollTo({left:line.scrollWidth,behavior:'smooth'})});q('#song').value=localStorage.deckTitle||'CITY IN E♭';q('#song').oninput=save;
function click(ac){try{audio=audio||new(AudioContext||webkitAudioContext)();let o=audio.createOscillator(),g=audio.createGain();o.frequency.value=ac?880:520;g.gain.setValueAtTime(.0001,audio.currentTime);g.gain.exponentialRampToValueAtTime(ac?.14:.06,audio.currentTime+.004);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+.065);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.07)}catch(e){}}function tick(){let total=Math.max(1,S.length*8),sec=Math.min(S.length-1,Math.floor(beat/8));render(sec);prog.style.width=beat/total*100+'%';let x=beat*60/bpm;clock.textContent=Math.floor(x/60)+':'+String(Math.floor(x%60)).padStart(2,'0');click(beat%4==0);if(++beat>total)stop()}function start(){if(!S.length)return;playing=true;beat=0;play.textContent='■';play.classList.add('playing');panel.classList.add('playing');tick();timer=setInterval(tick,60000/bpm)}function stop(){playing=false;clearInterval(timer);play.textContent='▶';play.classList.remove('playing');panel.classList.remove('playing');prog.style.width=0;clock.textContent='0:00';render()}play.onclick=()=>playing?stop():start();q('#tap').onclick=()=>{let n=performance.now();taps=taps.filter(t=>n-t<2200);taps.push(n);if(taps.length>1){let g=taps.slice(1).map((t,i)=>t-taps[i]);bpm=Math.max(45,Math.min(220,Math.round(60000/(g.reduce((a,b)=>a+b)/g.length))));q('#bpm').textContent=bpm}};render();
</script></body></html>