<?php declare(strict_types=1); ?>
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Shower Thought Salvage</title>
<style>
@import url('https://fonts.googleapis.com/css2?family=Kalam:wght@400;700&family=Oswald:wght@500;700&display=swap');
:root{--tile:#d8f1ee;--deep:#073c45;--aqua:#5bc7c5;--paper:#f4df59;--graphite:#263237;--red:#ef5a46}
*{box-sizing:border-box}html{min-height:100%;background:var(--tile)}body{margin:0;color:var(--deep);font-family:Kalam,cursive;min-height:100vh;background-color:var(--tile);background-image:linear-gradient(#ffffff55 2px,transparent 2px),linear-gradient(90deg,#ffffff55 2px,transparent 2px);background-size:72px 72px;overflow-x:hidden}
body:before{content:"";position:fixed;inset:0;pointer-events:none;background:radial-gradient(circle at 15% 8%,#fff 0 2px,transparent 3px),radial-gradient(circle at 78% 20%,#fff9 0 3px,transparent 4px);background-size:90px 110px;opacity:.7}
.pipe{height:18px;background:linear-gradient(#b7c5c4,#fafafa 44%,#899a99 48%,#dce5e4);box-shadow:0 4px 8px #073c4533}.wrap{width:min(1060px,92vw);margin:auto;padding:38px 0 60px}.top{display:grid;grid-template-columns:1.2fr .8fr;gap:28px;align-items:end}.eyebrow{font:700 13px Oswald,sans-serif;letter-spacing:.2em;text-transform:uppercase;color:#177f83}.title{font:700 clamp(3.4rem,10vw,7.6rem)/.8 Oswald,sans-serif;text-transform:uppercase;letter-spacing:-.055em;margin:10px 0;text-shadow:3px 3px 0 #fff}.title span{display:block;color:var(--red);transform:rotate(-2deg);transform-origin:left}.intro{font-size:1.15rem;line-height:1.45;max-width:44ch;margin:24px 0}.badge{justify-self:end;background:var(--deep);color:white;width:190px;height:190px;border-radius:50%;display:grid;place-content:center;text-align:center;transform:rotate(7deg);box-shadow:8px 8px 0 #fff,12px 12px 0 var(--aqua);font:700 20px/1.1 Oswald,sans-serif;text-transform:uppercase}.badge b{font-size:55px;color:var(--paper)}
.station{margin-top:35px;background:#8dd5d2;border:12px solid #fff;border-radius:28px;box-shadow:0 22px 50px #073c4535,inset 0 0 80px #fff8;min-height:490px;position:relative;padding:30px;overflow:hidden}.station:after{content:"";position:absolute;inset:0;pointer-events:none;background:linear-gradient(115deg,transparent 20%,#fff8 21%,transparent 27%,transparent 65%,#fff5 66%,transparent 72%)}
.drops{position:absolute;inset:0;pointer-events:none}.drop{position:absolute;width:8px;height:18px;background:#fff9;border-radius:50% 50% 60% 60%;animation:drip var(--speed) linear infinite;left:var(--x);top:-25px}@keyframes drip{to{transform:translateY(560px)}}
.panel{position:relative;z-index:2;display:grid;grid-template-columns:1.1fr .9fr;gap:28px}.paper{background:var(--paper);color:var(--graphite);padding:28px 28px 22px;min-height:360px;transform:rotate(-1deg);box-shadow:9px 12px 0 #073c4540;background-image:repeating-linear-gradient(transparent 0 35px,#ae9b3755 36px)}
.paper label{display:block;font:700 14px Oswald,sans-serif;letter-spacing:.15em;text-transform:uppercase}.paper textarea{display:block;width:100%;height:210px;border:0;resize:none;background:transparent;color:var(--graphite);font:700 clamp(1.45rem,4vw,2.2rem)/1.45 Kalam,cursive;padding:12px 4px;outline:0}.counter{text-align:right;font:700 13px Oswald,sans-serif;letter-spacing:.08em}.controls{display:flex;gap:10px;flex-wrap:wrap}.btn{border:0;padding:14px 18px;background:var(--deep);color:white;font:700 14px Oswald,sans-serif;text-transform:uppercase;letter-spacing:.06em;cursor:pointer;box-shadow:4px 4px 0 #fff;transition:.15s}.btn:hover,.btn:focus{transform:translate(-2px,-2px);box-shadow:6px 6px 0 #fff}.btn.secondary{background:var(--red)}
.rescue{background:#073c45e8;color:white;padding:26px;border-radius:0 28px 0 28px;align-self:center;min-height:310px}.rescue h2{font:700 28px Oswald,sans-serif;text-transform:uppercase;margin:0 0 8px}.rescue p{line-height:1.45}.chips{display:flex;flex-wrap:wrap;gap:8px;margin:16px 0}.chip{border:1px solid #77dad6;border-radius:99px;padding:5px 10px;color:#cafffc}.next{border-left:4px solid var(--paper);padding-left:14px;font-size:1.15rem;min-height:60px}.shelf{margin-top:26px}.shelf h2{font:700 24px Oswald,sans-serif;text-transform:uppercase}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.card{background:#fff;padding:17px;box-shadow:5px 5px 0 #5bb8b5;position:relative}.card button{position:absolute;right:8px;top:7px;border:0;background:none;color:#888;cursor:pointer}.card small{font:700 11px Oswald,sans-serif;color:#18868a;text-transform:uppercase}.empty{color:#42777a}.source{display:inline-block;margin-top:32px;color:var(--deep);font-weight:700;text-underline-offset:4px}.tip{font-size:.92rem;color:#376f72}
@media(max-width:720px){.top,.panel{grid-template-columns:1fr}.badge{display:none}.station{padding:17px;border-width:7px}.paper{padding:22px 18px}.cards{grid-template-columns:1fr}.title{font-size:18vw}.wrap{padding-top:26px}}
@media(prefers-reduced-motion:reduce){.drop{animation:none}.btn{transition:none}}
</style>
</head>
<body><div class="pipe"></div><main class="wrap">
<section class="top"><div><div class="eyebrow">Field station 07 · ideas under pressure</div><h1 class="title">Shower Thought <span>Salvage</span></h1><p class="intro">The best idea of the day has arrived at the least pencil-friendly moment. Catch its bones now. Make it legible later.</p></div><div class="badge"><b>45</b> seconds<br>to save it</div></section>
<section class="station"><div class="drops" id="drops"></div><div class="panel">
<div class="paper"><label for="thought">Water-resistant field note</label><textarea id="thought" maxlength="180" placeholder="Type the scrappy version…" autofocus></textarea><div class="counter"><span id="count">0</span>/180 · fragments welcome</div><div class="controls"><button class="btn" id="salvage">Salvage thought</button><button class="btn secondary" id="prompt">Give me a spark</button></div></div>
<aside class="rescue"><h2>Dry-land decoding</h2><p class="tip">Your note will be reduced to its memorable anchors, then given one small landing step.</p><div class="chips" id="chips"><span class="chip">waiting</span><span class="chip">for</span><span class="chip">brainwave</span></div><div class="next" id="next">The towel is ready. The notebook is suspiciously optimistic.</div></aside>
</div></section>
<section class="shelf"><h2>Behind the shampoo bottle</h2><div class="cards" id="cards"><p class="empty">No rescued thoughts yet. This is either serenity or a systems failure.</p></div></section>
<a class="source" href="https://jona.ca/2007/07/rite-in-rain-notebooks-for-shower-idea.html">Inspired by Jon's “Rite-In-The-Rain notebooks for shower idea capture” →</a>
</main>
<script>
const $=s=>document.querySelector(s), thought=$('#thought'), prompts=['A tiny game where Nathan…','A Catholic tool that makes it easier to…','What if this annoying thing had one excellent button?','A blog post comparing the old way with…','The feature I wish existed is…','A joke that becomes useful if…'];
for(let i=0;i<18;i++){let d=document.createElement('i');d.className='drop';d.style.setProperty('--x',Math.random()*100+'%');d.style.setProperty('--speed',(3+Math.random()*6)+'s');d.style.animationDelay=(-Math.random()*8)+'s';$('#drops').append(d)}
thought.oninput=()=>$('#count').textContent=thought.value.length;
$('#prompt').onclick=()=>{thought.value=prompts[Math.floor(Math.random()*prompts.length)];thought.dispatchEvent(new Event('input'));thought.focus()};
const stop=new Set('a an and are as at be but by for from had has have i if in is it its of on or that the this to was were what when where which who will with you your'.split(' '));
function anchor(text){return [...new Set((text.toLowerCase().match(/[a-z0-9’'-]+/g)||[]).filter(w=>w.length>2&&!stop.has(w)))].slice(0,5)}
function render(){let notes=JSON.parse(localStorage.getItem('showerSalvage')||'[]');$('#cards').innerHTML=notes.length?notes.map((n,i)=>`<article class="card"><button aria-label="Delete note" onclick="del(${i})">×</button><small>${n.date}</small><div>${esc(n.text)}</div></article>`).join(''):'<p class="empty">No rescued thoughts yet. This is either serenity or a systems failure.</p>'}
function esc(s){let d=document.createElement('div');d.textContent=s;return d.innerHTML}
window.del=i=>{let n=JSON.parse(localStorage.getItem('showerSalvage')||'[]');n.splice(i,1);localStorage.setItem('showerSalvage',JSON.stringify(n));render()};
$('#salvage').onclick=()=>{let text=thought.value.trim();if(!text){thought.focus();return}let words=anchor(text);$('#chips').innerHTML=(words.length?words:['idea','saved']).map(w=>`<span class="chip">${esc(w)}</span>`).join('');let verb=/^(build|make|write|ask|try|fix|call|read|create)/i.test(text)?'Do the first two-minute piece':'Open a fresh note and write three sentences';$('#next').textContent=verb+': '+text.replace(/[.!?]*$/,'.');let notes=JSON.parse(localStorage.getItem('showerSalvage')||'[]');notes.unshift({text,date:new Date().toLocaleDateString(undefined,{month:'short',day:'numeric'})});localStorage.setItem('showerSalvage',JSON.stringify(notes.slice(0,9)));thought.value='';thought.dispatchEvent(new Event('input'));render()};render();
</script></body></html>
