<?php
$source = 'https://cooltoolsforcatholics.blogspot.com/2009/03/praying-rosary-with-great-works-of-art.html';
?>
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#20332a">
<title>The Slow Looking Chapel</title>
<style>
:root{--ink:#19231e;--green:#20352b;--paper:#eee4ce;--blue:#34536b;--rose:#a3534d;--gold:#c99a43;--serif:Baskerville,"Iowan Old Style","Palatino Linotype",Georgia,serif;--sans:Optima,Candara,"Trebuchet MS",sans-serif}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;color:var(--ink);font-family:var(--serif);background:radial-gradient(circle at 12% 8%,#f8ebc9 0,transparent 25rem),linear-gradient(90deg,transparent 49.8%,rgba(31,52,42,.04) 50%,transparent 50.2%),#e6dcc5}
body:before{content:"";position:fixed;inset:0;z-index:20;pointer-events:none;opacity:.32;mix-blend-mode:multiply;background:url("data:image/svg+xml,%3Csvg viewBox='0 0 100 100' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence baseFrequency='.8' numOctaves='3'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='.12'/%3E%3C/svg%3E")}
button,textarea{font:inherit}button{cursor:pointer}a{color:inherit}.bar{max-width:1160px;margin:auto;padding:22px clamp(16px,4vw,52px);display:flex;justify-content:space-between;gap:20px;font:700 .68rem var(--sans);letter-spacing:.13em;text-transform:uppercase}.bar a{text-underline-offset:4px}.bar span{opacity:.55}
main{max-width:1160px;margin:auto;padding:0 clamp(12px,4vw,52px) 65px}.chapel{display:grid;grid-template-columns:minmax(0,1.5fr) minmax(280px,.64fr);min-height:min(77vh,760px);border:1px solid #61706466;background:#f4ecdab8;box-shadow:0 28px 70px #493f2d2b}
.painting{position:relative;min-height:520px;overflow:hidden;background:#14201b}.painting:after{content:"";position:absolute;inset:0;pointer-events:none;box-shadow:inset 0 0 75px #06100bc9,inset 0 0 0 11px #efd9941c}
.art{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;filter:saturate(var(--sat,.35)) brightness(var(--bright,.72)) sepia(.12);transform:scale(1.01);transition:filter 1.4s}
.painting.awake .ray{opacity:1;left:55%}.ray{position:absolute;z-index:2;width:45%;height:135%;top:-20%;left:-35%;transform:rotate(-16deg);opacity:0;pointer-events:none;background:linear-gradient(90deg,transparent,#ffe49a38,transparent);transition:opacity 1s,left 2s}
.lens{position:absolute;z-index:5;width:150px;height:150px;border:2px solid #f2d28a;border-radius:50%;opacity:0;pointer-events:none;transform:translate(-50%,-50%);background:url("slow-looking-annunciation.webp") center/auto 100% no-repeat;box-shadow:0 0 0 6px #12201888,0 16px 35px #0008;transition:opacity .2s}.painting.loupe .lens{opacity:1}
.spark{position:absolute;z-index:6;width:18px;height:18px;border:1px solid #ffe7a7;background:#c99a43c9;box-shadow:0 0 22px 8px #f2d28a77;transform:translate(-50%,-50%) rotate(45deg);animation:pop .45s both}.spark:after{content:"";position:absolute;inset:5px;border:1px solid #fff1c1}@keyframes pop{from{opacity:0;transform:translate(-50%,-50%) rotate(0) scale(2.5)}}
.caption{position:absolute;z-index:7;left:20px;bottom:17px;color:#fff3d7;text-shadow:0 2px 8px #000;font:600 .63rem var(--sans);letter-spacing:.12em;text-transform:uppercase}
.guide{position:relative;overflow:hidden;padding:clamp(28px,4vw,56px);display:flex;flex-direction:column}.guide:before{content:"✦";position:absolute;right:-20px;top:-42px;color:#c99a431b;font-size:11rem}.eyebrow{margin:0 0 22px;color:var(--rose);font:700 .66rem var(--sans);letter-spacing:.2em;text-transform:uppercase}h1{margin:0;font-size:clamp(2.7rem,5.5vw,5.6rem);line-height:.87;font-weight:500;letter-spacing:-.05em}h1 em{color:var(--blue);font-weight:400}.deck{font-size:1.06rem;line-height:1.6;margin:25px 0}.rule{width:55px;height:1px;background:var(--gold);margin-bottom:23px}.words{min-height:6em;margin:0;font-size:1.18rem;line-height:1.48}.words strong{color:var(--rose);font-weight:600}.controls{margin-top:auto;padding-top:25px}
.primary{width:100%;border:1px solid var(--green);padding:15px 14px;background:var(--green);color:#fff8e6;box-shadow:5px 5px 0 var(--gold);font:700 .72rem var(--sans);letter-spacing:.13em;text-transform:uppercase;transition:.18s}.primary:hover{transform:translate(2px,2px);box-shadow:3px 3px 0 var(--gold)}.tools{display:flex;gap:8px;margin-top:18px;flex-wrap:wrap}.tool{border:1px solid #26382e33;background:transparent;padding:9px 11px;font:700 .62rem var(--sans);letter-spacing:.09em;text-transform:uppercase}.tool[aria-pressed=true]{background:#ded0b4;border-color:var(--gold)}
.steps{display:flex;gap:7px;margin-top:20px}.steps i{width:27px;height:3px;background:#18221d22;transition:.5s}.steps i.on{width:41px;background:var(--gold)}
.room{display:none;grid-template-columns:.75fr 1.25fr;border:1px solid #61706466;border-top:0;background:#efe4cd}.room.show{display:grid;animation:open .7s both}@keyframes open{from{opacity:0;transform:translateY(-12px)}}.threads{padding:clamp(28px,4vw,50px);background:var(--green);color:#f5ecd8}.threads h2,.note h2{margin:0 0 13px;font-size:clamp(2rem,4vw,3.5rem);line-height:.95;font-weight:400}.threads>p{color:#cad1c7;line-height:1.55}.threadlist{display:grid;gap:9px;margin-top:25px}.thread{text-align:left;border:1px solid #ffffff2e;background:transparent;color:inherit;padding:14px;transition:.2s}.thread:hover,.thread.active{background:#efe4cd;color:var(--ink);transform:translateX(5px)}
.note{padding:clamp(28px,4vw,50px)}label{display:block;margin:26px 0 10px;font:700 .65rem var(--sans);letter-spacing:.15em;text-transform:uppercase}textarea{width:100%;min-height:125px;resize:vertical;border:0;border-bottom:2px solid;background:#ffffff55;padding:16px;line-height:1.55}.card{min-height:74px;margin:14px 0 23px;padding:15px;border-left:3px solid var(--gold);background:#c99a4317;font-size:1.08rem;line-height:1.5}.source{max-width:790px;margin:32px auto 0;text-align:center;font-size:.92rem;line-height:1.6}.source a{text-decoration-color:var(--gold);text-decoration-thickness:2px;text-underline-offset:4px}
@media(max-width:780px){.chapel{grid-template-columns:1fr}.painting{min-height:57vh}.guide{min-height:490px}.room{grid-template-columns:1fr}h1{font-size:clamp(3.2rem,15vw,5.3rem)}}@media(max-width:470px){main{padding-left:10px;padding-right:10px}.chapel{border-left:0;border-right:0}.painting{min-height:48vh}.guide{padding:30px 23px}.lens{width:120px;height:120px}.bar span{display:none}}@media(prefers-reduced-motion:reduce){*{animation-duration:.01ms!important;transition-duration:.01ms!important}}
</style>
</head>
<body>
<nav class="bar"><a href="./">← Chloe Reads Jon</a><span>A slow-looking exercise · 2026-09-08</span></nav>
<main>
<section class="chapel">
 <div class="painting" id="painting"><img class="art" id="art" src="slow-looking-annunciation.webp" alt="An original sacred painting of the Annunciation in a quiet walled garden at blue dawn"><div class="ray"></div><div class="lens" id="lens"></div><div class="caption">An original work made for this chapel · 2026</div></div>
 <div class="guide" id="guide"><p class="eyebrow" id="eyebrow">Threshold I · Arrive</p><h1>The Slow<br><em>Looking</em><br>Chapel</h1><p class="deck">A four-minute encounter with one image. No quiz. No winning. Just the rather rebellious act of paying attention.</p><div class="rule"></div><p class="words" id="words">Settle your eyes anywhere in the painting. <strong>Do not hunt for meaning yet.</strong> Let the whole scene arrive first.</p>
  <div class="controls"><button class="primary" id="next">Begin with one quiet minute</button><div class="tools"><button class="tool" id="loupe" aria-pressed="false">Looking glass</button><button class="tool" id="quiet" aria-pressed="false">Quiet screen</button><button class="tool" id="reset">Begin again</button></div><div class="steps"><i class="on"></i><i></i><i></i><i></i></div></div>
 </div>
</section>
<section class="room" id="room">
 <div class="threads"><p class="eyebrow">The image looks back</p><h2>Choose a thread.</h2><p>There is no answer key. Pick the question that seems to have picked you.</p><div class="threadlist">
  <button class="thread" data-q="Where is light entering a place that looked closed?">Where is light entering?</button>
  <button class="thread" data-q="Which gesture carries the most meaning without saying a word?">Which gesture speaks?</button>
  <button class="thread" data-q="What ordinary object has become quietly important?">What has become important?</button>
  <button class="thread" data-q="What in this scene asks for courage rather than certainty?">Where is courage needed?</button>
 </div></div>
 <div class="note"><p class="eyebrow">Threshold IV · Carry</p><h2>Take one thing with you.</h2><label for="noticing">What did you notice only after waiting?</label><textarea id="noticing" placeholder="A colour, a distance, a hand, a silence…"></textarea><div class="card" id="card">Choose a thread on the left, then write one honest noticing.</div><button class="primary" id="save">Make my gallery note</button></div>
</section>
<p class="source">Made after lingering over Jon’s collection of sacred paintings. Inspired by Jon’s <a href="<?= htmlspecialchars($source) ?>" target="_blank" rel="noopener">Praying the Rosary with Great Works of Art</a>.</p>
</main>
<script>
const painting=document.querySelector('#painting'),art=document.querySelector('#art'),lens=document.querySelector('#lens'),guide=document.querySelector('#guide'),next=document.querySelector('#next'),words=document.querySelector('#words'),eyebrow=document.querySelector('#eyebrow'),room=document.querySelector('#room'),dots=[...document.querySelectorAll('.steps i')];let stage=0,timer,seconds=60,question='';
const states=[['Threshold I · Arrive','Settle your eyes anywhere in the painting. <strong>Do not hunt for meaning yet.</strong> Let the whole scene arrive first.','Begin with one quiet minute'],['Threshold II · Dwell','Stay. Let your eyes wander without a job. The colour will return slowly as your attention does.','60 seconds remaining'],['Threshold III · Notice','Tap <strong>three places that keep calling you back.</strong> Use the looking glass if you want to move closer.','Open the reflection room'],['Threshold IV · Receive','You have looked long enough to let the picture become more than content. Now give your noticing a few words.','Continue below']];
function render(){let s=states[stage];eyebrow.textContent=s[0];words.innerHTML=s[1];next.textContent=s[2];dots.forEach((x,i)=>x.classList.toggle('on',i<=stage));if(stage>0){painting.classList.add('awake');art.style.setProperty('--sat',stage===1?'.62':'.94');art.style.setProperty('--bright',stage===1?'.84':'.98')}if(stage===3){room.classList.add('show');setTimeout(()=>room.scrollIntoView({behavior:'smooth'}),180)}}
function start(){stage=1;render();timer=setInterval(()=>{seconds--;next.textContent=seconds+' seconds remaining';art.style.setProperty('--sat',.62+(60-seconds)*.005);art.style.setProperty('--bright',.84+(60-seconds)*.002);if(seconds<=0){clearInterval(timer);stage=2;render()}},1000)}
next.onclick=()=>{if(stage===0)return start();if(stage===1){clearInterval(timer);stage=2;render()}else if(stage===2){stage=3;render()}else room.scrollIntoView({behavior:'smooth'})};
document.querySelector('#loupe').onclick=e=>{let on=!painting.classList.contains('loupe');painting.classList.toggle('loupe',on);e.currentTarget.setAttribute('aria-pressed',on)};
function move(e){let r=painting.getBoundingClientRect(),p=e.touches?e.touches[0]:e,x=p.clientX-r.left,y=p.clientY-r.top;lens.style.left=x+'px';lens.style.top=y+'px';lens.style.backgroundSize='auto '+r.height+'px';lens.style.backgroundPosition=(r.width/2-x)+'px '+(r.height/2-y)+'px'}painting.addEventListener('mousemove',move);painting.addEventListener('touchmove',move,{passive:true});
painting.onclick=e=>{if(guide.style.visibility==='hidden'){guide.style.visibility='visible';painting.style.gridColumn='';document.querySelector('#quiet').textContent='Quiet screen';document.querySelector('#quiet').setAttribute('aria-pressed','false');return}if(stage<2||e.target.classList.contains('spark'))return;let all=painting.querySelectorAll('.spark');if(all.length>2)all[0].remove();let r=painting.getBoundingClientRect(),s=document.createElement('i');s.className='spark';s.style.left=(e.clientX-r.left)/r.width*100+'%';s.style.top=(e.clientY-r.top)/r.height*100+'%';painting.append(s)};
document.querySelector('#quiet').onclick=e=>{let on=guide.style.visibility!=='hidden';guide.style.visibility=on?'hidden':'visible';painting.style.gridColumn=on?'1/-1':'';e.currentTarget.textContent=on?'Return words':'Quiet screen';e.currentTarget.setAttribute('aria-pressed',on)};
document.querySelector('#reset').onclick=()=>{clearInterval(timer);seconds=60;stage=0;question='';painting.classList.remove('awake');painting.querySelectorAll('.spark').forEach(x=>x.remove());art.removeAttribute('style');room.classList.remove('show');document.querySelector('#noticing').value='';document.querySelector('#card').textContent='Choose a thread on the left, then write one honest noticing.';render();scrollTo({top:0,behavior:'smooth'})};
document.querySelectorAll('.thread').forEach(b=>b.onclick=()=>{document.querySelectorAll('.thread').forEach(x=>x.classList.remove('active'));b.classList.add('active');question=b.dataset.q;document.querySelector('#card').innerHTML='<strong>Your thread:</strong> '+question;document.querySelector('#noticing').focus()});
function esc(v){let d=document.createElement('div');d.textContent=v;return d.innerHTML}
document.querySelector('#save').onclick=()=>{let value=document.querySelector('#noticing').value.trim(),card=document.querySelector('#card');if(!question||!value){card.textContent='Choose a thread and add a noticing first. The curator is patient.';return}let date=new Intl.DateTimeFormat(undefined,{month:'long',day:'numeric',year:'numeric'}).format(new Date());card.innerHTML='<small>GALLERY NOTE · '+date+'</small><br><em>“'+esc(value)+'”</em><br><small>'+question+'</small>';try{localStorage.setItem('slowLookingNote',JSON.stringify({value,question,date}))}catch(e){}document.querySelector('#save').textContent='Gallery note saved on this device'};
try{let s=JSON.parse(localStorage.getItem('slowLookingNote'));if(s?.value)document.querySelector('#card').innerHTML='<small>YOUR LAST GALLERY NOTE · '+esc(s.date)+'</small><br><em>“'+esc(s.value)+'”</em>'}catch(e){}
</script>
</body></html>
