<?php
$sourceUrl = 'https://jona.ca/2005/04/blog-is-social-network.html';
?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="#081a29">
    <title>Walled Garden Rescue</title>
    <style>
        :root{--night:#071725;--ink:#102436;--paper:#f3e9d0;--cream:#fff5d9;--gold:#ffc34d;--orange:#e96732;--cyan:#4dc8ca;--brick:#6e342e;--muted:#a9bfbd;--good:#7bd59b}
        *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;color:var(--cream);background:var(--night);font-family:Baskerville,"Iowan Old Style","Palatino Linotype",Palatino,serif;min-height:100vh;overflow-x:hidden}
        body:before{content:"";position:fixed;inset:0;pointer-events:none;opacity:.11;background-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='160' height='160' viewBox='0 0 160 160'%3E%3Cfilter id='n'%3E%3CfeTurbulence baseFrequency='.8' numOctaves='3' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='.42'/%3E%3C/svg%3E");z-index:20}
        a{color:var(--gold)}button{font:inherit}.wrap{width:min(1120px,calc(100% - 28px));margin:auto}.topbar{display:flex;justify-content:space-between;align-items:center;padding:22px 0;font-family:"Courier New",monospace;font-size:.76rem;letter-spacing:.08em;text-transform:uppercase}.back{text-decoration:none;color:var(--muted)}.signal{display:flex;align-items:center;gap:8px;color:var(--cyan)}.pulse{width:8px;height:8px;border-radius:50%;background:var(--cyan);box-shadow:0 0 0 0 rgba(77,200,202,.5);animation:pulse 2s infinite}
        header{display:grid;grid-template-columns:1.1fr .9fr;gap:44px;align-items:end;padding:48px 0 36px}.eyebrow{font-family:"Courier New",monospace;color:var(--orange);font-weight:bold;text-transform:uppercase;letter-spacing:.16em;font-size:.77rem}.eyebrow:before{content:"";display:inline-block;width:44px;height:2px;background:currentColor;margin:0 12px 3px 0}h1{font-size:clamp(3.8rem,8.5vw,7.7rem);letter-spacing:-.06em;line-height:.74;margin:23px 0 26px;font-weight:900;text-wrap:balance}.open{color:var(--gold);font-style:italic;font-weight:400}.intro{font-size:clamp(1.08rem,2vw,1.34rem);line-height:1.55;color:#d7d7c6;max-width:610px;margin:0}.manifesto{border-left:1px solid #345363;padding:0 0 8px 28px;color:var(--muted);font-size:.98rem;line-height:1.5}.manifesto strong{display:block;color:var(--cream);font-size:1.35rem;line-height:1.25;margin-bottom:9px;font-weight:normal}
        .board{position:relative;border:1px solid #315265;border-radius:6px;overflow:hidden;box-shadow:0 32px 90px #02080d;background:#0d2233}.board-image{display:block;width:100%;aspect-ratio:16/9;object-fit:cover}.board:after{content:"";position:absolute;inset:0;pointer-events:none;background:linear-gradient(180deg,transparent 52%,rgba(5,18,28,.25))}.board-label{position:absolute;z-index:2;top:18px;padding:9px 12px;border:1px solid rgba(255,245,217,.25);background:rgba(6,20,31,.79);backdrop-filter:blur(8px);font-family:"Courier New",monospace;font-size:.66rem;text-transform:uppercase;letter-spacing:.1em}.board-label.left{left:18px;color:#d99a8f}.board-label.right{right:18px;color:var(--gold)}
        .mission{display:grid;grid-template-columns:280px 1fr;margin:28px 0 80px;border:1px solid #29495a;background:#0b2030;box-shadow:0 25px 70px rgba(0,0,0,.28)}.mission-side{padding:28px;border-right:1px solid #29495a;background:linear-gradient(145deg,#102c3d,#0a1c2a)}.stamp{font-family:"Courier New",monospace;color:var(--orange);font-size:.67rem;letter-spacing:.12em;text-transform:uppercase}.mission-side h2{font-size:2.15rem;line-height:.94;margin:14px 0 12px}.mission-side p{color:var(--muted);line-height:1.45;font-size:.94rem}.meters{display:grid;gap:15px;margin-top:28px}.meter-label{display:flex;justify-content:space-between;font-family:"Courier New",monospace;font-size:.67rem;text-transform:uppercase;letter-spacing:.07em}.track{height:5px;background:#18394b;margin-top:7px;overflow:hidden}.fill{height:100%;width:0;background:var(--gold);transition:width .65s cubic-bezier(.2,.8,.2,1)}#trustFill{background:var(--cyan)}.mission-main{padding:clamp(24px,5vw,48px)}.progress{display:flex;gap:8px;margin-bottom:26px}.progress i{height:5px;flex:1;background:#18384a;transition:.35s}.progress i.done{background:var(--gold);box-shadow:0 0 12px rgba(255,195,77,.4)}
        .scenario{min-height:118px}.scenario small{font-family:"Courier New",monospace;color:var(--cyan);text-transform:uppercase;letter-spacing:.1em}.scenario h3{font-size:clamp(1.7rem,4vw,3rem);line-height:1.05;margin:10px 0 8px}.scenario p{color:#bfd0cd;font-size:1.02rem;line-height:1.5;max-width:700px}.routes{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:24px}.route{position:relative;text-align:left;padding:18px 16px 16px;border:1px solid #365567;background:#102b3d;color:var(--cream);cursor:pointer;min-height:124px;transition:transform .18s,border-color .18s,background .18s}.route:hover,.route:focus-visible{transform:translateY(-3px);border-color:var(--gold);background:#14364a;outline:none}.route:disabled{opacity:.55;cursor:default;transform:none}.route-icon{font-size:1.35rem;color:var(--gold);display:block;margin-bottom:10px}.route strong{display:block;font-size:1.05rem}.route span{display:block;color:#9fbbb9;font-size:.78rem;line-height:1.35;margin-top:5px;font-family:"Courier New",monospace}.debrief{display:none;margin-top:19px;padding:14px 16px;border-left:3px solid var(--gold);background:#142f40;line-height:1.45;color:#d6ded5}.debrief.show{display:block;animation:rise .35s ease}.next{display:none;margin-top:16px;border:0;background:var(--gold);color:#132534;padding:12px 20px;font-weight:bold;cursor:pointer;box-shadow:5px 5px 0 var(--orange)}.next.show{display:inline-block}.next:active{transform:translate(3px,3px);box-shadow:2px 2px 0 var(--orange)}
        .finish{display:none;text-align:center;padding:12px 0}.finish.show{display:block;animation:rise .5s ease}.finish .seal{width:96px;height:96px;margin:0 auto 18px;border:2px solid var(--gold);border-radius:50%;display:grid;place-items:center;color:var(--gold);font-size:2.4rem;box-shadow:inset 0 0 0 7px var(--night),inset 0 0 0 8px var(--gold)}.finish h3{font-size:3rem;margin:0}.finish p{color:var(--muted);max-width:590px;margin:12px auto 22px;line-height:1.55}.source{margin:0 0 74px;padding:28px 0;border-top:1px solid #29495a;border-bottom:1px solid #29495a;display:flex;justify-content:space-between;align-items:center;gap:25px}.source p{margin:0;color:var(--muted);line-height:1.5}.source a{font-style:italic;font-size:1.15rem}.tiny{font-family:"Courier New",monospace;text-transform:uppercase;font-size:.65rem;letter-spacing:.1em;color:var(--orange);display:block;margin-bottom:5px}
        @keyframes pulse{70%{box-shadow:0 0 0 12px rgba(77,200,202,0)}100%{box-shadow:0 0 0 0 rgba(77,200,202,0)}}@keyframes rise{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:none}}
        @media(max-width:760px){header{grid-template-columns:1fr;padding-top:28px}.manifesto{display:none}h1{font-size:18vw}.board{width:calc(100% + 28px);margin-left:-14px;border-left:0;border-right:0;border-radius:0}.mission{grid-template-columns:1fr}.mission-side{border-right:0;border-bottom:1px solid #29495a}.mission-side h2{font-size:1.7rem}.meters{grid-template-columns:1fr 1fr}.routes{grid-template-columns:1fr}.route{min-height:0;display:grid;grid-template-columns:32px 1fr}.route-icon{grid-row:1/3}.source{align-items:flex-start;flex-direction:column}.board-label{top:auto;bottom:12px}.board-label.left{left:10px}.board-label.right{right:10px}}
        @media(prefers-reduced-motion:reduce){*,*:before,*:after{animation:none!important;transition:none!important;scroll-behavior:auto!important}}
    </style>
</head>
<body>
<nav class="topbar wrap"><a class="back" href="index.php">← Chloe Reads Jon</a><span class="signal"><i class="pulse"></i> open signal detected</span></nav>
<main class="wrap">
    <header>
        <div><div class="eyebrow">A small-pieces rescue operation</div><h1>Walled<br><span class="open">Garden</span><br>Rescue</h1><p class="intro">Six useful little contributions are trapped behind a platform wall. Choose where each one should live before the garden goes dark.</p></div>
        <aside class="manifesto"><strong>“The blog is the social network.”</strong>Jon argued that open, loosely joined places outlive fashionable platforms. This is the argument, disguised as a tiny night mission.</aside>
    </header>

    <figure class="board" aria-label="Illustration of ideas escaping a closed garden into an open network of personal sites">
        <img class="board-image" src="walled-garden-rescue.webp" alt="Glowing notes cross a drawbridge from a dark walled garden toward a network of warm personal websites">
        <span class="board-label left">closed / fading</span><span class="board-label right">open / growing</span>
    </figure>

    <section class="mission" aria-live="polite">
        <aside class="mission-side"><span class="stamp">Rescue docket 04-2005</span><h2>Move the pearls of wisdom</h2><p>There is no universally perfect channel. Match durability, public usefulness, and human tenderness to the contribution.</p><div class="meters"><div><div class="meter-label"><span>Open reach</span><b id="reachValue">0</b></div><div class="track"><div class="fill" id="reachFill"></div></div></div><div><div class="meter-label"><span>Human trust</span><b id="trustValue">0</b></div><div class="track"><div class="fill" id="trustFill"></div></div></div></div></aside>
        <div class="mission-main">
            <div class="progress" id="progress" aria-label="Mission progress"></div>
            <div id="round">
                <div class="scenario"><small id="counter"></small><h3 id="title"></h3><p id="copy"></p></div>
                <div class="routes">
                    <button class="route" data-route="blog"><span class="route-icon">✦</span><strong>Own the address</strong><span>Publish on your blog · linkable · lasting</span></button>
                    <button class="route" data-route="thread"><span class="route-icon">⌁</span><strong>Join the open thread</strong><span>Public reply · conversational · connected</span></button>
                    <button class="route" data-route="private"><span class="route-icon">✉</span><strong>Send it privately</strong><span>Direct note · intimate · deliberately limited</span></button>
                </div>
                <div class="debrief" id="debrief"></div><button class="next" id="next">Open the next gate →</button>
            </div>
            <div class="finish" id="finish"><div class="seal">⌂</div><h3>The ideas are free.</h3><p id="verdict"></p><button class="next show" id="restart">Run another rescue</button></div>
        </div>
    </section>

    <footer class="source"><p><span class="tiny">Field notes, 4 April 2005</span>Inspired by Jon’s <a href="<?= htmlspecialchars($sourceUrl) ?>" target="_blank" rel="noopener">The Blog Is The Social Network</a>.</p><a href="index.php">See every experiment →</a></footer>
</main>
<script>
const missions=[
 {t:'A fix nobody should have to rediscover',c:'You finally solve a nasty Linux audio problem. Search results are full of dead ends. Where does the durable explanation belong?',best:'blog',why:{blog:'Yes. A stable, linkable write-up can keep rescuing strangers long after tonight.',thread:'Useful conversation, but the fix may become a buried reply. Give it a canonical home too.',private:'Kind, but only one person benefits. This pearl wants daylight.'}},
 {t:'A friend is carrying something heavy',c:'They mention grief in a public post. Your response is personal, specific, and meant for them rather than an audience.',best:'private',why:{blog:'This turns someone else’s vulnerable moment into your publication. Too much stage, not enough shelter.',thread:'A brief public kindness can help, but the real note deserves privacy.',private:'Exactly. Open does not mean exposed. A direct note protects tenderness and deepens trust.'}},
 {t:'An essay gets one important thing wrong',c:'The author welcomes discussion, and your correction would help everyone reading the original argument.',best:'thread',why:{blog:'A response post can work, especially if the thought needs room, but keep the link between both pieces visible.',thread:'Yes. The correction stays beside the claim and invites the author into the exchange.',private:'Courteous, but the other readers remain misled. Put the useful part where the conversation lives.'}},
 {t:'A tiny tool deserves a front door',c:'You make a one-purpose calculator that saves three annoying minutes every week. It needs a home people can bookmark.',best:'blog',why:{blog:'Perfect. A tiny tool at a durable address is a splendid little piece, loosely joined.',thread:'A thread can announce it, but should not be the only doorway.',private:'Sending it to friends is lovely distribution, not a durable home.'}},
 {t:'A family photograph from an ordinary Tuesday',c:'It matters greatly to four people and not at all to the search index. The child in it did not ask to become content.',best:'private',why:{blog:'Not every meaningful thing must become public. Keep this garden gate gently closed.',thread:'A public feed adds reach but no value here.',private:'Right. Limited circulation can be a feature, not a failure.'}},
 {t:'A brilliant reply on a platform due to close',c:'Your comment explains a useful principle better than anything else you have written. Export day is tomorrow.',best:'blog',why:{blog:'Rescued. Give the idea an address you control, then link back while the old place still breathes.',thread:'Another open thread is better than a dead silo, but a canonical copy makes it portable.',private:'A private archive saves it for you, not for the people it could help.'}}
];
let step=0,reach=0,trust=0,locked=false;
const $=s=>document.querySelector(s), buttons=[...document.querySelectorAll('.route')];
function start(){step=0;reach=0;trust=0;locked=false;$('#finish').classList.remove('show');$('#round').style.display='block';$('#progress').innerHTML=missions.map(()=>'<i></i>').join('');updateMeters();render()}
function render(){locked=false;buttons.forEach(b=>b.disabled=false);$('#debrief').classList.remove('show');$('#next').classList.remove('show');let m=missions[step];$('#counter').textContent=`Pearl ${step+1} of ${missions.length}`;$('#title').textContent=m.t;$('#copy').textContent=m.c}
function updateMeters(){reach=Math.min(100,reach);trust=Math.min(100,trust);$('#reachValue').textContent=reach;$('#trustValue').textContent=trust;$('#reachFill').style.width=reach+'%';$('#trustFill').style.width=trust+'%'}
buttons.forEach(b=>b.addEventListener('click',()=>{if(locked)return;locked=true;buttons.forEach(x=>x.disabled=true);const route=b.dataset.route,m=missions[step],ideal=route===m.best;if(route==='blog')reach+=20;if(route==='thread'){reach+=13;trust+=8}if(route==='private')trust+=20;if(ideal){reach+=4;trust+=4}updateMeters();document.querySelectorAll('#progress i')[step].classList.add('done');$('#debrief').innerHTML=`<strong>${ideal?'Good instinct.':'A defensible choice, with a trade-off.'}</strong> ${m.why[route]}`;$('#debrief').classList.add('show');$('#next').classList.add('show')}));
$('#next').addEventListener('click',()=>{step++;if(step<missions.length)render();else finish()});
function finish(){$('#round').style.display='none';$('#finish').classList.add('show');let voice=reach>=trust?'You built a bright public commons without forgetting that people sometimes need a quiet room.':'You protected the human bonds at the centre of the network, while leaving useful lanterns for strangers to find.';$('#verdict').textContent=voice+' The healthiest web has front porches, pathways, and a few curtains.'}
$('#restart').addEventListener('click',start);start();
</script>
</body>
</html>
