<?php
$sourceUrl = 'https://cooltoolsforcatholics.blogspot.com/2004/12/ts-eliot-reading-waste-land.html';
?>
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#162b2a">
<title>The Waste Land Signal Cabinet</title>
<style>
:root{--ink:#151513;--paper:#e9e0ca;--teal:#163b39;--orange:#f07839;--cream:#fff4d5;--glow:rgba(240,120,57,.42)}
*{box-sizing:border-box}html{background:#0d1716;color:var(--cream);font-family:"Baskerville","Iowan Old Style",Georgia,serif}body{margin:0;min-height:100vh;overflow-x:hidden;background:radial-gradient(circle at 72% 12%,#285654 0,transparent 31rem),linear-gradient(145deg,#0b1312,#182c2a 54%,#0d1716)}
body:before{content:"";position:fixed;inset:0;pointer-events:none;opacity:.16;background-image:url("data:image/svg+xml,%3Csvg viewBox='0 0 180 180' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='.6'/%3E%3C/svg%3E")}
a{color:inherit}.shell{width:min(1180px,100%);margin:auto;padding:24px clamp(18px,4vw,54px) 70px;position:relative}.topline{display:flex;justify-content:space-between;gap:20px;align-items:center;text-transform:uppercase;letter-spacing:.2em;font:700 11px/1.2 "Avenir Next",sans-serif;color:#d6c9aa}.back{text-decoration:none;border-bottom:1px solid #806e50;padding-bottom:4px}.issue{opacity:.7}
header{display:grid;grid-template-columns:1.08fr .92fr;align-items:end;gap:clamp(28px,6vw,80px);padding:clamp(44px,8vw,100px) 0 38px}h1{font-family:"Bodoni 72","Didot",serif;font-size:clamp(58px,10vw,138px);font-weight:400;letter-spacing:-.065em;line-height:.75;margin:0;max-width:720px}h1 em{display:block;color:var(--orange);font-size:.56em;letter-spacing:-.03em;padding-left:12%;font-style:italic}.dek{font-size:clamp(18px,2.2vw,26px);line-height:1.42;margin:0 0 8px;border-left:2px solid var(--orange);padding-left:22px;color:#eadfca}
.visual{position:relative;border:1px solid #786d57;background:#111;box-shadow:0 30px 80px #0008;overflow:hidden}.visual:after{content:"TRANSMISSION 1922";position:absolute;bottom:14px;right:16px;font:700 9px/1 sans-serif;letter-spacing:.23em;color:#fff9}.visual img{width:100%;display:block;aspect-ratio:16/9;object-fit:cover;filter:saturate(.82) contrast(1.04)}.visual .scan{position:absolute;inset:0;background:repeating-linear-gradient(0deg,transparent 0 3px,#dcebe80b 4px);mix-blend-mode:screen;animation:scan 8s linear infinite}@keyframes scan{to{transform:translateY(12px)}}
.cabinet{margin-top:-1px;background:linear-gradient(100deg,#37291c,#17140f 45%,#2b2117);border:1px solid #786d57;padding:clamp(22px,5vw,50px);box-shadow:0 35px 80px #0009,inset 0 0 0 8px #0d0b0877}.radio-top{display:grid;grid-template-columns:1fr auto;gap:22px;align-items:start}.eyebrow{font:800 10px/1 sans-serif;letter-spacing:.25em;text-transform:uppercase;color:#bfab7e}.status{font:700 11px/1 sans-serif;letter-spacing:.12em;color:var(--orange)}.dial-wrap{margin:28px 0 22px}.frequency{font-family:"Bodoni 72",serif;font-size:clamp(52px,8vw,90px);line-height:1;color:#ffd98e;text-shadow:0 0 18px var(--glow)}.frequency small{font:700 11px/1 sans-serif;letter-spacing:.2em;color:#b5a580}
input[type=range]{width:100%;height:42px;appearance:none;background:transparent;cursor:ew-resize}input[type=range]::-webkit-slider-runnable-track{height:6px;background:repeating-linear-gradient(90deg,#6f5b37 0 1px,transparent 1px 5%),linear-gradient(90deg,#9c8b69,#f07839);border:1px solid #b2a47f}input[type=range]::-webkit-slider-thumb{appearance:none;width:7px;height:42px;margin-top:-19px;background:#fff0bb;box-shadow:0 0 12px var(--orange)}input[type=range]::-moz-range-track{height:6px;background:#8f7c57;border:1px solid #b2a47f}input[type=range]::-moz-range-thumb{width:7px;height:42px;border:0;border-radius:0;background:#fff0bb}.scale{display:flex;justify-content:space-between;font:700 9px/1 sans-serif;letter-spacing:.13em;color:#8d8064;padding:0 4px}
.signal-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:32px}.station{min-height:128px;background:#100e0b;border:1px solid #5e5037;padding:16px;text-align:left;color:#82765f;transition:.35s;position:relative;overflow:hidden}.station.found{background:#f0e2bf;color:#252018;border-color:#f2c15a;box-shadow:0 0 24px #e57d2530}.station:before{content:attr(data-n);font:italic 34px/1 "Bodoni 72",serif;position:absolute;right:10px;top:8px;opacity:.22}.station b{display:block;font:800 9px/1 sans-serif;text-transform:uppercase;letter-spacing:.16em;margin-bottom:12px}.station span{display:block;font-size:17px;line-height:1.18}.station:not(.found) span{filter:blur(4px);user-select:none}.meter{display:flex;align-items:center;gap:12px;margin:22px 0 0;font:700 9px/1 sans-serif;letter-spacing:.18em;color:#9b8c6e}.meter-track{height:4px;flex:1;background:#0d0c09}.meter-fill{height:100%;width:0;background:var(--orange);box-shadow:0 0 10px var(--orange);transition:width .15s}.instructions{font-size:15px;color:#b9ac91;line-height:1.5;margin-top:12px}.instructions kbd{font:700 10px sans-serif;border:1px solid #75694f;padding:2px 6px}
.field-note{display:none;background:var(--paper);color:var(--ink);margin-top:24px;padding:clamp(22px,5vw,45px);position:relative}.field-note.show{display:grid;grid-template-columns:.7fr 1.3fr;gap:35px;animation:unfold .7s cubic-bezier(.2,.8,.2,1)}@keyframes unfold{from{opacity:0;transform:translateY(18px) rotateX(12deg)}}.field-note h2{font:400 clamp(34px,6vw,65px)/.9 "Bodoni 72",serif;margin:0}.field-note p{font-size:18px;line-height:1.55;margin:0}.choices{display:flex;flex-wrap:wrap;gap:8px;margin-top:18px}.choice,.copy{border:1px solid #4c4436;background:transparent;color:var(--ink);font:700 11px/1.2 sans-serif;letter-spacing:.08em;text-transform:uppercase;padding:10px 12px;cursor:pointer}.choice.active{background:var(--teal);color:var(--cream)}.dispatch{border-top:1px solid #aaa084;margin-top:22px;padding-top:18px;font-style:italic;min-height:68px}.copy{margin-top:12px}.copy.done{background:var(--teal);color:#fff}
footer{display:flex;justify-content:space-between;gap:24px;align-items:end;margin-top:42px;color:#bcae8e;font-size:14px;line-height:1.45}.source{max-width:580px}.source a{color:#ffd98e;text-underline-offset:4px}.sig{font:italic 16px "Bodoni 72",serif}
@media(max-width:720px){header{grid-template-columns:1fr;padding-top:54px}.dek{max-width:520px}.signal-grid{grid-template-columns:1fr 1fr}.field-note.show{grid-template-columns:1fr}.station{min-height:116px}footer{display:block}.sig{margin-top:24px}.topline{align-items:flex-start}.issue{text-align:right}}@media(prefers-reduced-motion:reduce){*,*:before,*:after{animation:none!important;transition:none!important}}
</style>
</head>
<body><main class="shell">
<div class="topline"><a class="back" href="index.php">← Chloe Reads Jon</a><span class="issue">A listening experiment · No. 04</span></div>
<header><h1>The Waste Land <em>Signal Cabinet</em></h1><p class="dek">Four fragments are drifting through the static. Tune slowly. Recover the broadcast. Leave with a weather report from the interior.</p></header>
<div class="visual"><img src="waste-land-signal.webp" alt="A linocut radio glowing beside a fractured, rain-dark London river"><i class="scan"></i></div>
<section class="cabinet" aria-label="Radio tuning game">
<div class="radio-top"><span class="eyebrow">Long-wave literary receiver</span><span class="status" id="status">0 / 4 signals held</span></div>
<div class="dial-wrap"><div class="frequency"><span id="freq">61.0</span> <small>kHz</small></div><input id="dial" type="range" min="610" max="1460" value="610" step="1" aria-label="Tuning frequency"><div class="scale"><span>61</span><span>80</span><span>100</span><span>120</span><span>146</span></div></div>
<div class="meter"><span>signal</span><div class="meter-track"><div class="meter-fill" id="meter"></div></div><span id="quality">static</span></div>
<p class="instructions">Drag the pale needle or use <kbd>←</kbd> <kbd>→</kbd>. A signal locks when the orange meter reaches its edge. Tap anywhere first if you want the radio to hum.</p>
<div class="signal-grid"><article class="station" data-n="I"><b>April band</b><span>Winter kept us warm.</span></article><article class="station" data-n="II"><b>Memory band</b><span>These fragments I have shored.</span></article><article class="station" data-n="III"><b>Thunder band</b><span>Datta. Dayadhvam. Damyata.</span></article><article class="station" data-n="IV"><b>Peace band</b><span>Shantih shantih shantih.</span></article></div>
</section>
<section class="field-note" id="note" aria-live="polite"><h2>File your weather report.</h2><div><p>The broadcast is never quite complete. Choose what the air feels like where you are, and the cabinet will make a small dispatch.</p><div class="choices" id="choices"><button class="choice" data-line="There is rain in the wires, but the lamps are staying lit.">rain / lamps</button><button class="choice" data-line="The thunder has passed; something green is thinking underground.">thunder / green</button><button class="choice" data-line="Fragments everywhere, and still enough timber for a little shelter.">fragments / shelter</button></div><div class="dispatch" id="dispatch">Choose a pair above.</div><button class="copy" id="copy">Copy field note</button></div></section>
<footer><div class="source">This cabinet was inspired by Jon’s <a href="<?= htmlspecialchars($sourceUrl, ENT_QUOTES) ?>" target="_blank" rel="noopener">T.S. Eliot reading <cite>The Waste Land</cite> (HarperAudio online)</a>, and by the odd intimacy of hearing a poet transmit his own words through old computer speakers.</div><div class="sig">Designed in the static, 2026</div></footer>
</main>
<script>
(()=>{const dial=document.querySelector('#dial'),freq=document.querySelector('#freq'),meter=document.querySelector('#meter'),quality=document.querySelector('#quality'),status=document.querySelector('#status'),cards=[...document.querySelectorAll('.station')],note=document.querySelector('#note');const targets=[686,874,1127,1384],found=new Set();let ctx,osc,gain,noise,noiseGain;
function audio(){if(ctx)return;ctx=new (window.AudioContext||window.webkitAudioContext)();osc=ctx.createOscillator();gain=ctx.createGain();osc.type='sine';gain.gain.value=.018;osc.connect(gain).connect(ctx.destination);osc.start();const buf=ctx.createBuffer(1,ctx.sampleRate*2,ctx.sampleRate),d=buf.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=Math.random()*2-1;noise=ctx.createBufferSource();noise.buffer=buf;noise.loop=true;noiseGain=ctx.createGain();noiseGain.gain.value=.035;noise.connect(noiseGain).connect(ctx.destination);noise.start()}
function tune(){const v=+dial.value;freq.textContent=(v/10).toFixed(1);let nearest=0,dist=999;targets.forEach((t,i)=>{const d=Math.abs(v-t);if(d<dist){dist=d;nearest=i}});const power=Math.max(0,100-dist*4);meter.style.width=power+'%';quality.textContent=power>92?'holding':power>55?'voice':power>20?'faint':'static';if(ctx){osc.frequency.setTargetAtTime(120+power*2.1,ctx.currentTime,.04);noiseGain.gain.setTargetAtTime(.008+(100-power)/2300,ctx.currentTime,.04)}if(dist<=2&&!found.has(nearest)){found.add(nearest);cards[nearest].classList.add('found');cards[nearest].setAttribute('aria-label','Recovered signal: '+cards[nearest].innerText);if(navigator.vibrate)navigator.vibrate(35);status.textContent=found.size+' / 4 signals held';if(found.size===4){status.textContent='BROADCAST RESTORED';note.classList.add('show');setTimeout(()=>note.scrollIntoView({behavior:'smooth',block:'center'}),550)}}}
dial.addEventListener('input',()=>{audio();tune()});document.addEventListener('pointerdown',audio,{once:true});tune();document.querySelector('#choices').addEventListener('click',e=>{const b=e.target.closest('.choice');if(!b)return;document.querySelectorAll('.choice').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('#dispatch').textContent='FIELD NOTE — '+b.dataset.line+' Signal recovered at '+new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})+'.'});document.querySelector('#copy').addEventListener('click',async e=>{const t=document.querySelector('#dispatch').textContent;if(t.startsWith('Choose'))return;try{await navigator.clipboard.writeText(t);e.target.textContent='Copied to pocket';e.target.classList.add('done')}catch(_){e.target.textContent='Select the note and copy'}})})();
</script></body></html>